import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Database } from '../data/database';

const bookingStatus = (status) => { const value = String(status || '').toLowerCase(); if (value.includes('xác nhận')) return 'ĐÃ XÁC NHẬN'; if (value.includes('hoàn thành')) return 'ĐÃ HOÀN THÀNH'; if (value.includes('hủy')) return 'ĐÃ HỦY'; return 'CHỜ XÁC NHẬN'; };

export default function DirectMessage({ mentorName, mentorEmail, menteeName, booking = null, currentUserName, currentUserEmail, currentUserRole = 'MENTEE', onBack }) {
  const roomId = useMemo(() => `mentor-chat-${encodeURIComponent(mentorEmail || mentorName || 'mentor')}-${encodeURIComponent(menteeName || 'mentee')}`, [mentorEmail, mentorName, menteeName]);
  const [messages, setMessages] = useState([]); const [draft, setDraft] = useState(''); const [loading, setLoading] = useState(true); const scrollRef = useRef(null);
  const status = bookingStatus(booking?.status);
  const starterMessages = useMemo(() => [{ user: mentorName || 'Mentor PSIFU', role: 'MENTOR', text: status === 'CHỜ XÁC NHẬN' ? `Chào ${menteeName || 'bạn'}! Mình đã nhận được yêu cầu lịch hẹn, sẽ phản hồi bạn sớm nhé.` : `Chào ${menteeName || 'bạn'}! Mình sẵn sàng hỗ trợ bạn cho buổi ${booking?.course || 'mentoring'} này.`, createdAt: '2026-10-02T06:40:00.000Z' }], [mentorName, menteeName, booking?.course, status]);
  const load = async () => { try { setMessages(await Database.getChatMessages(roomId, starterMessages)); } finally { setLoading(false); } };
  useEffect(() => { load(); const timer = setInterval(load, 4000); return () => clearInterval(timer); }, [roomId]);
  const senderName = currentUserName || menteeName || 'Bạn';
  const send = async () => { const text = draft.trim(); if (!text) return; const message = { user: senderName, authorEmail: currentUserEmail || '', role: currentUserRole, text, createdAt: new Date().toISOString() }; setDraft(''); setMessages(items => [...items, message]); try { await Database.saveChatMessage(roomId, message); } catch { setMessages(items => items.filter(item => item !== message)); } };
  return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.header}><TouchableOpacity style={styles.back} onPress={onBack}><Ionicons name="chevron-back" size={22} color="#102A56" /></TouchableOpacity><View style={styles.avatar}><Text style={styles.avatarText}>{(mentorName || 'M').slice(0, 1)}</Text></View><View style={{flex:1}}><Text style={styles.name}>{mentorName || 'Mentor PSIFU'}</Text><Text style={styles.online}>● Online</Text></View><Ionicons name="videocam-outline" size={20} color="#155EEF" /></View>
    {booking ? <View style={styles.session}><View style={styles.sessionTop}><View><Text style={styles.sessionLabel}>UPCOMING SESSION</Text><Text style={styles.sessionCourse}>{booking.course || 'Phiên mentoring'}</Text></View><View style={[styles.status, status === 'ĐÃ XÁC NHẬN' && styles.statusConfirmed]}><Text style={[styles.statusText, status === 'ĐÃ XÁC NHẬN' && styles.statusTextConfirmed]}>{status}</Text></View></View><View style={styles.sessionMeta}><Ionicons name="calendar-outline" size={13} color="#526F98"/><Text style={styles.sessionMetaText}>{booking.dateTime || 'Đang cập nhật thời gian'}</Text></View><Text style={styles.privateNote}>🔒 Cuộc trò chuyện riêng tư chỉ giữa bạn và {mentorName}.</Text></View> : <View style={styles.notice}><Ionicons name="shield-checkmark-outline" size={16} color="#1976D2" /><Text style={styles.noticeText}>Trao đổi riêng tư về buổi mentoring của bạn.</Text></View>}
    {loading ? <ActivityIndicator style={{marginTop:30}} color="#1976D2" /> : <ScrollView ref={scrollRef} onContentSizeChange={() => scrollRef.current?.scrollToEnd({animated:true})} contentContainerStyle={styles.messages}>{messages.map((item,index) => { const mine = (item.authorEmail && item.authorEmail === currentUserEmail) || item.user === senderName; return <View key={item._id || `${index}-${item.createdAt}`} style={[styles.messageRow, mine && styles.messageRowMine]}>{!mine && <View style={styles.messageAvatar}><Text style={styles.messageAvatarText}>{String(item.user || mentorName).slice(0,1)}</Text></View>}<View style={[styles.bubble, mine ? styles.mine : styles.theirs]}>{!mine && <View style={styles.senderRow}><Text style={styles.sender}>{item.user || mentorName}</Text><Text style={styles.senderRole}>{item.role || 'MENTOR'}</Text></View>}<Text style={[styles.messageText, mine && styles.mineText]}>{item.text}</Text><Text style={[styles.messageTime, mine && styles.mineTime]}>{new Date(item.createdAt || Date.now()).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}</Text></View></View>; })}</ScrollView>}
    <View style={styles.composer}><Ionicons name="attach-outline" size={19} color="#607795"/><TextInput value={draft} onChangeText={setDraft} placeholder={`Nhắn cho ${mentorName || 'mentor'}…`} placeholderTextColor="#8A9BB5" style={styles.input} multiline /><TouchableOpacity style={styles.send} onPress={send}><Ionicons name="send" size={18} color="#FFFFFF" /></TouchableOpacity></View></KeyboardAvoidingView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#FFFFFF'},header:{paddingHorizontal:15,paddingVertical:11,flexDirection:'row',alignItems:'center',gap:9,borderBottomWidth:1,borderColor:'#E4ECF7'},back:{width:32,height:32,borderRadius:12,alignItems:'center',justifyContent:'center',backgroundColor:'#F2F6FC'},avatar:{width:35,height:35,borderRadius:13,alignItems:'center',justifyContent:'center',backgroundColor:'#155EEF'},avatarText:{color:'#FFFFFF',fontWeight:'900'},name:{color:'#102A56',fontSize:12,fontWeight:'900'},online:{color:'#248C62',fontSize:8,fontWeight:'700',marginTop:2},session:{margin:12,padding:11,borderRadius:12,backgroundColor:'#F5F8FF',borderWidth:1,borderColor:'#DCE7FA'},sessionTop:{flexDirection:'row',justifyContent:'space-between',gap:8},sessionLabel:{fontSize:7,color:'#4E73A7',fontWeight:'900'},sessionCourse:{color:'#102A56',fontSize:12,fontWeight:'900',marginTop:3},status:{alignSelf:'flex-start',backgroundColor:'#FFF3DD',paddingHorizontal:6,paddingVertical:4,borderRadius:7},statusConfirmed:{backgroundColor:'#DCFCE7'},statusText:{color:'#B45309',fontSize:7,fontWeight:'900'},statusTextConfirmed:{color:'#16803C'},sessionMeta:{flexDirection:'row',alignItems:'center',gap:5,marginTop:8},sessionMetaText:{color:'#526F98',fontSize:8},privateNote:{color:'#71829D',fontSize:8,marginTop:8},notice:{margin:14,padding:10,borderRadius:12,backgroundColor:'#EFF7FF',flexDirection:'row',gap:7,alignItems:'center'},noticeText:{flex:1,color:'#38618D',fontSize:10,lineHeight:14},messages:{padding:14,gap:10,flexGrow:1},messageRow:{flexDirection:'row',gap:7,alignItems:'flex-end'},messageRowMine:{justifyContent:'flex-end'},messageAvatar:{width:25,height:25,borderRadius:13,backgroundColor:'#E3EAF8',alignItems:'center',justifyContent:'center'},messageAvatarText:{color:'#155EEF',fontSize:9,fontWeight:'900'},bubble:{maxWidth:'82%',padding:10,borderRadius:13},mine:{backgroundColor:'#155EEF',borderBottomRightRadius:3},theirs:{backgroundColor:'#F0F4FA',borderBottomLeftRadius:3},senderRow:{flexDirection:'row',alignItems:'center',gap:4,marginBottom:3},sender:{color:'#17365F',fontSize:8,fontWeight:'900'},senderRole:{backgroundColor:'#155EEF',color:'#FFF',fontSize:6,fontWeight:'900',paddingHorizontal:4,paddingVertical:1,borderRadius:3},messageText:{color:'#17365F',fontSize:11,lineHeight:16},mineText:{color:'#FFFFFF'},messageTime:{color:'#71829D',fontSize:7,marginTop:4,textAlign:'right'},mineTime:{color:'#D9E7FF'},composer:{flexDirection:'row',gap:8,padding:10,borderTopWidth:1,borderColor:'#E4ECF7',alignItems:'center'},input:{flex:1,maxHeight:90,minHeight:38,backgroundColor:'#F2F6FC',borderRadius:12,paddingHorizontal:11,paddingTop:10,color:'#102A56',fontSize:11},send:{width:38,height:38,borderRadius:19,backgroundColor:'#155EEF',alignItems:'center',justifyContent:'center'}});
