import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Database } from '../data/database';

export default function DirectMessage({ mentorName, mentorEmail, menteeName, onBack }) {
  const roomId = useMemo(() => `mentor-chat-${encodeURIComponent(mentorEmail || mentorName || 'mentor')}-${encodeURIComponent(menteeName || 'mentee')}`, [mentorEmail, mentorName, menteeName]);
  const [messages, setMessages] = useState([]); const [draft, setDraft] = useState(''); const [loading, setLoading] = useState(true); const scrollRef = useRef(null);
  const starterMessages = useMemo(() => [{ user: mentorName || 'Mentor PSIFU', text: `Chào ${menteeName || 'bạn'}! Lịch hẹn của bạn đã được xác nhận, mình sẵn sàng hỗ trợ nhé.`, createdAt: '2026-09-25T08:00:00.000Z' }, { user: mentorName || 'Mentor PSIFU', text: 'Bạn có thể gửi trước câu hỏi hoặc nội dung muốn trao đổi để buổi mentoring hiệu quả hơn.', createdAt: '2026-09-25T08:02:00.000Z' }], [mentorName, menteeName]);
  const load = async () => { try { setMessages(await Database.getChatMessages(roomId, starterMessages)); } finally { setLoading(false); } };
  useEffect(() => { load(); const timer = setInterval(load, 4000); return () => clearInterval(timer); }, [roomId]);
  const send = async () => { if (!draft.trim()) return; const message = { user: menteeName || 'Bạn', authorEmail: '', text: draft.trim(), createdAt: new Date().toISOString() }; setDraft(''); setMessages(items => [...items, message]); try { await Database.saveChatMessage(roomId, message); } catch { setMessages(items => items.filter(item => item !== message)); } };
  return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.header}><TouchableOpacity style={styles.back} onPress={onBack}><Ionicons name="chevron-back" size={22} color="#102A56" /></TouchableOpacity><View style={styles.avatar}><Text style={styles.avatarText}>{(mentorName || 'M').slice(0, 1)}</Text></View><View style={{flex:1}}><Text style={styles.name}>{mentorName || 'Mentor PSIFU'}</Text><Text style={styles.online}>● Có thể nhắn tin</Text></View></View><View style={styles.notice}><Ionicons name="shield-checkmark-outline" size={16} color="#1976D2" /><Text style={styles.noticeText}>Trao đổi riêng tư về buổi mentoring của bạn.</Text></View>{loading ? <ActivityIndicator style={{marginTop:30}} color="#1976D2" /> : <ScrollView ref={scrollRef} onContentSizeChange={() => scrollRef.current?.scrollToEnd({animated:true})} contentContainerStyle={styles.messages}>{messages.length ? messages.map((item,index) => { const mine = item.user === (menteeName || 'Bạn'); return <View key={item._id || `${index}-${item.createdAt}`} style={[styles.bubble, mine ? styles.mine : styles.theirs]}>{!mine && <Text style={styles.sender}>{item.user || mentorName}</Text>}<Text style={[styles.messageText, mine && styles.mineText]}>{item.text}</Text></View>; }) : <View style={styles.empty}><Ionicons name="chatbubbles-outline" size={35} color="#1976D2" /><Text style={styles.emptyTitle}>Bắt đầu cuộc trò chuyện</Text><Text style={styles.emptyCopy}>Hỏi mentor về lịch hẹn, cách chuẩn bị hoặc nội dung cần hỗ trợ.</Text></View>}</ScrollView>}<View style={styles.composer}><TextInput value={draft} onChangeText={setDraft} placeholder="Nhắn cho mentor…" placeholderTextColor="#8A9BB5" style={styles.input} multiline /><TouchableOpacity style={styles.send} onPress={send}><Ionicons name="send" size={18} color="#FFFFFF" /></TouchableOpacity></View></KeyboardAvoidingView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#FFFFFF'},header:{paddingHorizontal:16,paddingTop:12,paddingBottom:13,flexDirection:'row',alignItems:'center',gap:10,borderBottomWidth:1,borderColor:'#E4ECF7'},back:{width:38,height:38,borderRadius:12,alignItems:'center',justifyContent:'center',backgroundColor:'#F2F6FC'},avatar:{width:38,height:38,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:'#7C4DFF'},avatarText:{color:'#FFFFFF',fontWeight:'900'},name:{color:'#102A56',fontSize:13,fontWeight:'900'},online:{color:'#248C62',fontSize:9,fontWeight:'700',marginTop:2},notice:{margin:14,padding:10,borderRadius:12,backgroundColor:'#EFF7FF',flexDirection:'row',gap:7,alignItems:'center'},noticeText:{flex:1,color:'#38618D',fontSize:10,lineHeight:14},messages:{padding:16,gap:9,flexGrow:1},bubble:{maxWidth:'82%',padding:11,borderRadius:15},mine:{alignSelf:'flex-end',backgroundColor:'#1976D2',borderBottomRightRadius:4},theirs:{alignSelf:'flex-start',backgroundColor:'#F0F4FA',borderBottomLeftRadius:4},sender:{color:'#4B6390',fontSize:9,fontWeight:'800',marginBottom:3},messageText:{color:'#17365F',fontSize:12,lineHeight:17},mineText:{color:'#FFFFFF'},empty:{alignItems:'center',marginTop:65,paddingHorizontal:32},emptyTitle:{color:'#102A56',fontWeight:'900',marginTop:10},emptyCopy:{color:'#64748B',fontSize:11,lineHeight:17,textAlign:'center',marginTop:5},composer:{flexDirection:'row',gap:9,padding:12,borderTopWidth:1,borderColor:'#E4ECF7',alignItems:'flex-end'},input:{flex:1,maxHeight:90,minHeight:42,backgroundColor:'#F2F6FC',borderRadius:14,paddingHorizontal:13,paddingTop:11,color:'#102A56',fontSize:12},send:{width:42,height:42,borderRadius:14,backgroundColor:'#1976D2',alignItems:'center',justifyContent:'center'}});
