import React, { useState } from 'react';
import { Linking, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';

export default function DocumentReader({ document, onBack, onQuiz }) {
  const [page, setPage] = useState(5);
  if (document.fileUri) return <View style={s.screen}><View style={s.top}><TouchableOpacity onPress={onBack}><Ionicons name="chevron-back" size={24} color="#102A56" /></TouchableOpacity><Text style={s.topTitle} numberOfLines={1}>{document.name || document.title}</Text><Ionicons name="cloud-done-outline" size={20} color="#155EEF" /></View><View style={s.loading}><Ionicons name="document-text-outline" size={36} color="#155EEF"/><Text style={s.loadingText}>Tài liệu PDF được lưu an toàn trên cloud.</Text><TouchableOpacity style={s.quiz} onPress={()=>Linking.openURL(document.fileUri)}><Text style={s.quizText}>MỞ PDF</Text></TouchableOpacity></View></View>;
  const total = 24; const pct = Math.round(page / total * 100);
  return <ScrollView style={s.screen} contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
    <View style={s.top}><TouchableOpacity onPress={onBack}><Ionicons name="chevron-back" size={24} color="#102A56" /></TouchableOpacity><Text style={s.topTitle} numberOfLines={1}>{document.name || document.title}</Text><Ionicons name="bookmark-outline" size={20} color="#102A56" /></View>
    <View style={s.chapter}><Text style={s.chip}>{document.code || document.course || 'STUDY GUIDE'}</Text><Text style={s.chapterText}>Chương 3: Cấp phát bộ nhớ</Text></View><View style={s.track}><View style={[s.fill,{width:`${pct}%`}]} /></View><Text style={s.pageProgress}>{pct}% · {page}/{total} trang</Text>
    <View style={s.paper}><Text style={s.crumb}>{document.code || document.course || 'PSIFU'} — Tài liệu học tập · Trang {page}/{total}</Text><Text style={s.section}>3.2 Quản lý vùng nhớ Heap & lỗi thường gặp</Text><Text style={s.copy}>Trong ngôn ngữ C, vùng nhớ Heap được quản lý thủ công bởi lập trình viên. Khi một biến cục bộ trên Stack ra khỏi phạm vi, dữ liệu trên Heap vẫn tồn tại cho đến khi được thu hồi đúng cách.</Text><Text style={s.copy}>So sánh hai hàm cấp phát phổ biến để hiểu cách dùng an toàn trong bài Practical Exam.</Text><View style={s.compare}><Box title="malloc(size_t size)" copy="Cấp phát vùng nhớ theo số byte yêu cầu. Giá trị ô nhớ ban đầu có thể chưa xác định."/><Box title="calloc(n, size)" copy="Cấp phát mảng phần tử đồng thời khởi tạo toàn bộ về 0."/></View><View style={s.code}><Text style={s.codeText}>int *arr = (int*) calloc(n, sizeof(int));{`\n`}if (arr == NULL) return -1;{`\n`}...{`\n`}free(arr); arr = NULL;</Text></View><View style={s.note}><Ionicons name="alert-circle" size={17} color="#C76B00"/><Text style={s.noteText}>Luôn giải phóng bộ nhớ sau khi dùng để tránh memory leak.</Text></View><Text style={s.footer}>Giáo trình chính thức PSIFU · {page} / {total}</Text></View>
    <View style={s.pager}><TouchableOpacity disabled={page === 1} onPress={() => setPage(p => Math.max(1,p-1))}><Ionicons name="chevron-back" size={22} color="#fff" /></TouchableOpacity><Text style={s.pagerText}>{page} / {total}</Text><TouchableOpacity disabled={page === total} onPress={() => setPage(p => Math.min(total,p+1))}><Ionicons name="chevron-forward" size={22} color="#fff" /></TouchableOpacity></View>
    <View style={s.ai}><View style={s.aiHead}><View style={s.aiIcon}><Ionicons name="sparkles" size={20} color="#155EEF" /></View><View style={{flex:1}}><Text style={s.aiTitle}>Practice with AI</Text><Text style={s.aiSub}>Tạo bài luyện tập từ các trang bạn vừa đọc.</Text></View><Text style={s.aiTag}>AI STUDY TOOL</Text></View><View style={s.badges}><Text style={s.badge}>10 câu trắc nghiệm</Text><Text style={s.badge}>15 phút làm bài</Text></View><TouchableOpacity style={s.quiz} onPress={onQuiz}><Ionicons name="sparkles" size={17} color="#fff"/><Text style={s.quizText}>Generate AI Quiz</Text></TouchableOpacity></View>
  </ScrollView>;
}
function Box({title,copy}){return <View style={s.box}><Text style={s.boxTitle}>{title}</Text><Text style={s.boxCopy}>{copy}</Text></View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#FAFAFF'},content:{padding:15,paddingBottom:32},top:{height:42,flexDirection:'row',alignItems:'center',gap:12,paddingHorizontal:15},topTitle:{flex:1,color:'#102A56',fontWeight:'900',fontSize:14},loading:{flex:1,alignItems:'center',justifyContent:'center'},loadingText:{color:'#64748B',fontSize:12},chapter:{marginTop:13,flexDirection:'row',alignItems:'center',gap:7},chip:{fontSize:8,fontWeight:'900',color:'#155EEF',backgroundColor:'#DDE8FF',paddingHorizontal:8,paddingVertical:4,borderRadius:8},chapterText:{color:'#64748B',fontSize:10},track:{height:5,borderRadius:5,backgroundColor:'#DFE8F8',overflow:'hidden',marginTop:10},fill:{height:'100%',backgroundColor:'#155EEF'},pageProgress:{color:'#71829D',fontSize:9,textAlign:'right',marginTop:4},paper:{marginTop:13,backgroundColor:'#fff',borderRadius:14,padding:16,borderWidth:1,borderColor:'#E1E8F4'},crumb:{fontSize:9,color:'#536E99'},section:{fontSize:21,lineHeight:28,fontWeight:'900',color:'#102A56',marginTop:12},copy:{fontSize:13,color:'#344965',lineHeight:21,marginTop:11},compare:{flexDirection:'row',gap:8,marginTop:12},box:{flex:1,backgroundColor:'#EEF2FF',borderRadius:9,padding:9},boxTitle:{fontSize:10,color:'#155EEF',fontWeight:'900'},boxCopy:{fontSize:10,lineHeight:15,color:'#40536F',marginTop:5},code:{marginTop:13,borderRadius:10,padding:13,backgroundColor:'#102033'},codeText:{color:'#EAF2FF',fontFamily:'monospace',fontSize:11,lineHeight:18},note:{backgroundColor:'#FFF5DC',borderRadius:9,padding:10,flexDirection:'row',gap:7,marginTop:12},noteText:{flex:1,fontSize:10,color:'#875E12',lineHeight:15},footer:{marginTop:15,fontSize:9,color:'#71829D'},pager:{height:48,backgroundColor:'#233B62',borderRadius:25,marginTop:15,flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingHorizontal:20},pagerText:{color:'#fff',fontWeight:'900',fontSize:12},ai:{backgroundColor:'#EAF0FF',borderRadius:15,padding:14,marginTop:16},aiHead:{flexDirection:'row',gap:9,alignItems:'center'},aiIcon:{width:37,height:37,borderRadius:11,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},aiTitle:{fontSize:16,color:'#102A56',fontWeight:'900'},aiSub:{fontSize:10,color:'#536E99',marginTop:2},aiTag:{fontSize:7,color:'#fff',backgroundColor:'#155EEF',borderRadius:7,paddingHorizontal:6,paddingVertical:4,fontWeight:'900'},badges:{flexDirection:'row',gap:7,marginTop:12},badge:{fontSize:9,color:'#355476',backgroundColor:'#fff',borderRadius:7,paddingHorizontal:7,paddingVertical:5},quiz:{height:45,borderRadius:11,backgroundColor:'#155EEF',marginTop:13,justifyContent:'center',alignItems:'center',flexDirection:'row',gap:7},quizText:{color:'#fff',fontWeight:'900',fontSize:12}});
