import React, { useMemo, useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import MentorProfile from './MentorProfile';

const postSamples=['Mẹo ôn nhanh trước quiz: bắt đầu từ đề cũ, đánh dấu những dạng hay sai rồi mới đọc lại lý thuyết.','Đừng học một mình quá lâu. Hãy viết câu hỏi cụ thể và đưa vào Community, bạn sẽ nhận được cách nhìn khác.','Lộ trình làm project hiệu quả: chia nhỏ scope, có demo sớm và xin feedback từng tuần.'];
export default function FindMentor({ mentors=[], courses=[], currentTerm, onBook, bookings=[] }) {
  const [search,setSearch]=useState(''); const [course,setCourse]=useState('all'); const [selectedMentor,setSelectedMentor]=useState(null);
  const courseList=courses.filter(item=>item.term===currentTerm).slice(0,5); const filtered=useMemo(()=>mentors.filter(item=>`${item.name} ${item.role} ${(item.courses||[]).join(' ')}`.toLowerCase().includes(search.toLowerCase())&&(course==='all'||(item.courses||[]).includes(course))),[mentors,search,course]);
  if(selectedMentor) return <MentorProfile mentor={selectedMentor} onBack={()=>setSelectedMentor(null)} onBook={onBook}/>;
  return <ScrollView style={s.screen} contentContainerStyle={s.content}><View style={s.hero}><Text style={s.eyebrow}>MENTOR NETWORK</Text><Text style={s.title}>Học nhanh hơn,{`\n`}đúng người hơn.</Text><Text style={s.heroCopy}>Kết nối mentor có kinh nghiệm và xem các chia sẻ hữu ích cho kỳ học của bạn.</Text><View style={s.stats}><Text style={s.stat}>✦ {mentors.length || 3} mentor</Text><Text style={s.stat}>● {currentTerm}</Text></View></View><View style={s.search}><Ionicons name="search-outline" size={18} color="#536E99"/><TextInput value={search} onChangeText={setSearch} placeholder="Tìm mentor, môn học..." placeholderTextColor="#71829D" style={s.input}/></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}><TouchableOpacity onPress={()=>setCourse('all')} style={[s.chip,course==='all'&&s.chipOn]}><Text style={[s.chipText,course==='all'&&s.chipTextOn]}>Tất cả</Text></TouchableOpacity>{courseList.map(item=><TouchableOpacity key={item.code} onPress={()=>setCourse(item.code)} style={[s.chip,course===item.code&&s.chipOn]}><Text style={[s.chipText,course===item.code&&s.chipTextOn]}>{item.code}</Text></TouchableOpacity>)}</ScrollView><Text style={s.heading}>Mentor đề xuất</Text>{filtered.map((mentor,index)=>{const slots=mentor.availableSlots||[];return <View key={mentor.id} style={s.card}><View style={s.cardHead}><View style={[s.avatar,{backgroundColor:['#2563EB','#7C3AED','#0F766E'][index%3]}]}><Text style={s.avatarText}>{mentor.initials||mentor.name?.split(' ').slice(-2).map(p=>p[0]).join('')}</Text></View><View style={{flex:1}}><Text style={s.name}>{mentor.name} <Text style={s.verified}>●</Text></Text><Text style={s.role}>{mentor.role}</Text><Text style={s.meta}>★ 4.9 · {(mentor.courses||[]).slice(0,2).join(' · ')}</Text></View><View style={s.price}><Text style={s.priceNum}>{mentor.fee||50}</Text><Text style={s.priceLabel}>Xu/buổi</Text></View></View><View style={s.post}><View style={s.postTop}><Ionicons name="sparkles" size={15} color="#7C3AED"/><Text style={s.postLabel}>CHIA SẺ TỪ MENTOR</Text></View><Text style={s.postText}>{mentor.post||postSamples[index%postSamples.length]}</Text><Text style={s.postTime}>Vừa cập nhật · 3 phút đọc</Text></View><View style={s.actions}><TouchableOpacity style={s.outline} onPress={()=>setSelectedMentor(mentor)}><Text style={s.outlineText}>Xem hồ sơ</Text></TouchableOpacity><TouchableOpacity disabled={!slots.length} style={[s.primary,!slots.length&&s.disabled]} onPress={()=>onBook(mentor,course==='all'?(mentor.courses||[])[0]:course)}><Ionicons name="calendar-outline" size={16} color="#fff"/><Text style={s.primaryText}>{slots.length?'Đặt lịch':'Chưa mở lịch'}</Text></TouchableOpacity></View></View>})}{!filtered.length?<View style={s.empty}><Ionicons name="people-outline" size={35} color="#1976D2"/><Text style={s.emptyTitle}>Chưa có mentor phù hợp</Text><Text style={s.emptyText}>Thử một môn học khác hoặc quay lại sau nhé.</Text></View>:null}</ScrollView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#FAFCFF'},content:{padding:16,paddingBottom:32},hero:{backgroundColor:'#102A56',borderRadius:20,padding:19},eyebrow:{color:'#83C5FF',fontWeight:'900',fontSize:9,letterSpacing:.8},title:{color:'#fff',fontSize:25,fontWeight:'900',lineHeight:30,marginTop:6},heroCopy:{color:'#D7E5F7',fontSize:11,lineHeight:16,marginTop:8,maxWidth:'90%'},stats:{flexDirection:'row',gap:8,marginTop:15},stat:{color:'#fff',fontSize:10,fontWeight:'800',backgroundColor:'rgba(255,255,255,.13)',paddingHorizontal:9,paddingVertical:6,borderRadius:12},search:{height:48,backgroundColor:'#fff',borderWidth:1,borderColor:'#D6E2F2',borderRadius:14,flexDirection:'row',alignItems:'center',paddingHorizontal:13,gap:8,marginTop:15},input:{flex:1,color:'#102A56',fontSize:12},chips:{gap:8,paddingVertical:12},chip:{borderWidth:1,borderColor:'#D6E2F2',borderRadius:12,paddingHorizontal:12,paddingVertical:8,backgroundColor:'#fff'},chipOn:{backgroundColor:'#1976D2',borderColor:'#1976D2'},chipText:{color:'#536E99',fontSize:10,fontWeight:'800'},chipTextOn:{color:'#fff'},heading:{color:'#102A56',fontSize:15,fontWeight:'900',marginBottom:10},card:{backgroundColor:'#fff',borderWidth:1,borderColor:'#DCE6F4',borderRadius:17,padding:13,marginBottom:12},cardHead:{flexDirection:'row',gap:10},avatar:{width:45,height:45,borderRadius:15,alignItems:'center',justifyContent:'center'},avatarText:{color:'#fff',fontWeight:'900'},name:{color:'#102A56',fontSize:13,fontWeight:'900'},verified:{color:'#1976D2',fontSize:9},role:{color:'#526E98',fontSize:10,marginTop:3},meta:{color:'#7488A4',fontSize:9,marginTop:4},price:{alignItems:'flex-end'},priceNum:{color:'#102A56',fontSize:17,fontWeight:'900'},priceLabel:{color:'#71829D',fontSize:8},post:{backgroundColor:'#F7F4FF',borderRadius:12,padding:11,marginTop:12},postTop:{flexDirection:'row',gap:5,alignItems:'center'},postLabel:{fontSize:8,fontWeight:'900',color:'#6D45C8'},postText:{color:'#263C66',fontSize:11,lineHeight:16,marginTop:5},postTime:{color:'#7A6B9B',fontSize:8,marginTop:6},actions:{flexDirection:'row',gap:8,marginTop:11},outline:{height:42,flex:1,borderRadius:11,borderWidth:1,borderColor:'#BFD0E7',alignItems:'center',justifyContent:'center'},outlineText:{color:'#173F83',fontSize:11,fontWeight:'900'},primary:{height:42,flex:1,borderRadius:11,backgroundColor:'#1976D2',alignItems:'center',justifyContent:'center',flexDirection:'row',gap:6},disabled:{backgroundColor:'#AAB9CC'},primaryText:{color:'#fff',fontSize:11,fontWeight:'900'},empty:{alignItems:'center',paddingVertical:45},emptyTitle:{color:'#102A56',fontWeight:'900',marginTop:10},emptyText:{color:'#64748B',fontSize:11,marginTop:4}});
