import React, { useEffect, useState } from 'react';
import { Modal, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Database } from '../data/database';

const ROOM = 'homepage-live';
const asTime = value => { try { return new Date(value).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'}); } catch { return ''; } };

export default function HomeLiveChat({ name, email, role = 'MENTEE' }) {
  const [messages, setMessages] = useState([]); const [draft, setDraft] = useState(''); const [open, setOpen] = useState(false); const [sending, setSending] = useState(false);
  const load = async () => { try { const rows = await Database.getChatMessages(ROOM); setMessages(rows); } catch {} };
  useEffect(() => { load(); const timer = setInterval(load, 3000); return () => clearInterval(timer); }, []);
  const send = async () => { const text = draft.trim(); if (!text || sending) return; setSending(true); const optimistic={user:name || 'Bạn',authorEmail:email,role,text,createdAt:new Date().toISOString()}; setDraft(''); setMessages(rows => [...rows,optimistic]); try { const saved=await Database.saveChatMessage(ROOM,optimistic); setMessages(rows => rows.map(row => row===optimistic ? saved : row)); } catch { setMessages(rows => rows.filter(row => row!==optimistic)); } finally { setSending(false); } };
  const feed = <>{messages.length ? messages.slice(open ? -50 : -4).map((item,index) => <View key={item.id || item._id || `${item.createdAt}-${index}`} style={s.message}><View style={s.messageHead}><Text style={s.user}>{item.user || 'Thành viên'}</Text><Text style={[s.badge,item.role === 'MENTOR' && s.mentorBadge]}>{item.role === 'MENTOR' ? 'MENTOR' : 'MENTEE'}</Text><Text style={s.time}>{asTime(item.createdAt)}</Text></View><Text style={s.messageText}>{item.text}</Text></View>) : <Text style={s.empty}>Chưa có tin nhắn. Hãy mở đầu cuộc trò chuyện.</Text>}</>;
  const composer = <View style={s.composer}><TextInput value={draft} onChangeText={setDraft} onSubmitEditing={send} placeholder="Nhắn tin với mọi người…" placeholderTextColor="#93A1BE" style={s.input} maxLength={1000}/><TouchableOpacity disabled={!draft.trim() || sending} onPress={send} style={[s.send,(!draft.trim() || sending) && s.sendDisabled]}><Ionicons name="send" size={16} color="#fff"/></TouchableOpacity></View>;
  return <><View style={s.card}><View style={s.head}><View><View style={s.titleRow}><Text style={s.title}>PSIFU Chat</Text><Text style={s.live}>● LIVE</Text></View><Text style={s.copy}>Phòng chat chung theo thời gian thực.</Text></View><TouchableOpacity onPress={() => setOpen(true)}><Text style={s.open}>Open full chat</Text></TouchableOpacity></View><View style={s.feed}>{feed}</View>{composer}<TouchableOpacity style={s.expand} onPress={() => setOpen(true)}><Text style={s.expandText}>Open Full Chat Room →</Text></TouchableOpacity></View><Modal visible={open} animationType="slide" onRequestClose={() => setOpen(false)}><View style={s.modal}><View style={s.modalHead}><View><Text style={s.modalTitle}>PSIFU Chat</Text><Text style={s.copy}>Sảnh chung · cập nhật tự động mỗi 3 giây</Text></View><TouchableOpacity style={s.exit} onPress={() => setOpen(false)}><Ionicons name="close" size={20} color="#102A56"/><Text style={s.exitText}>Exit</Text></TouchableOpacity></View><ScrollView contentContainerStyle={s.fullFeed}>{feed}</ScrollView>{composer}</View></Modal></>;
}
const s=StyleSheet.create({card:{backgroundColor:'#fff',borderRadius:14,borderWidth:1,borderColor:'#E0E8F5',padding:12},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},titleRow:{flexDirection:'row',alignItems:'center',gap:6},title:{fontSize:15,color:'#102A56',fontWeight:'900'},live:{fontSize:8,color:'#E11D48',fontWeight:'900',backgroundColor:'#FFE7E7',paddingHorizontal:6,paddingVertical:3,borderRadius:5},copy:{fontSize:9,color:'#64748B',lineHeight:14,marginTop:3},open:{fontSize:9,color:'#155EEF',fontWeight:'900'},feed:{gap:7,marginTop:10},message:{backgroundColor:'#F3F6FD',borderRadius:9,padding:8},messageHead:{flexDirection:'row',alignItems:'center',gap:5},user:{fontSize:9,color:'#102A56',fontWeight:'900'},badge:{fontSize:7,color:'#64748B',fontWeight:'900',backgroundColor:'#E5E7EB',paddingHorizontal:4,paddingVertical:2,borderRadius:4},mentorBadge:{color:'#155EEF',backgroundColor:'#DCE8FF'},time:{fontSize:7,color:'#94A3B8',marginLeft:'auto'},messageText:{fontSize:10,color:'#364A69',lineHeight:15,marginTop:3},empty:{fontSize:10,color:'#71829D',paddingVertical:10,textAlign:'center'},composer:{height:40,marginTop:10,borderWidth:1,borderColor:'#DCE6F4',borderRadius:9,flexDirection:'row',alignItems:'center',paddingLeft:10},input:{flex:1,color:'#102A56',fontSize:11},send:{width:38,height:'100%',borderRadius:8,backgroundColor:'#155EEF',alignItems:'center',justifyContent:'center'},sendDisabled:{backgroundColor:'#A8B9D7'},expand:{height:31,alignItems:'center',justifyContent:'center',backgroundColor:'#EAF1FF',borderRadius:7,marginTop:8},expandText:{color:'#155EEF',fontSize:9,fontWeight:'900'},modal:{flex:1,backgroundColor:'#F8FAFF'},modalHead:{paddingHorizontal:16,paddingVertical:13,borderBottomWidth:1,borderColor:'#E0E8F5',flexDirection:'row',justifyContent:'space-between',alignItems:'center'},modalTitle:{fontSize:18,color:'#102A56',fontWeight:'900'},exit:{flexDirection:'row',alignItems:'center',gap:3,backgroundColor:'#EAF1FF',paddingHorizontal:10,paddingVertical:7,borderRadius:8},exitText:{fontSize:10,color:'#102A56',fontWeight:'900'},fullFeed:{padding:14,gap:8,flexGrow:1}});
