import React, { useEffect, useState } from 'react';
import { Modal, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Database } from '../data/database';

const fallbackMentors = [
  { id: 'm1', name: 'Minh Anh', role: 'Software Engineering', initials: 'MA', color: '#2563eb' },
  { id: 'm2', name: 'Gia Hân', role: 'Data Science & AI', initials: 'GH', color: '#173F83' },
  { id: 'm3', name: 'Quốc Bảo', role: 'Digital Marketing', initials: 'QB', color: '#315A9D' }
];
const liveSeed = [
  { user: 'Minh Anh', role: 'MENTEE', text: 'Mọi người tối nay ai học PRF192 không?', createdAt: '2026-10-02T10:02:00.000Z' },
  { user: 'Nguyễn Văn An', role: 'MENTOR', text: 'Bạn nào cần hỗ trợ PRF192 thì mình đang online nhé.', createdAt: '2026-10-02T10:04:00.000Z' },
  { user: 'Hoàng', role: 'MENTEE', text: 'DBI202 tuần này mọi người học tới đâu rồi?', createdAt: '2026-10-02T10:05:00.000Z' },
];
const onlinePeople = [{ name: 'Nguyễn Văn An', role: 'MENTOR' }, { name: 'Minh Anh', role: 'MENTEE' }, { name: 'Lan', role: 'MENTEE' }, { name: 'Trần Minh', role: 'MENTOR' }];

export default function HomeDashboard({ fullName, userEmail = '', userXu, hasCheckedInToday = false, mentors = [], bookings = [], courses = [], recentDocuments = [], currentTerm = 'Kỳ 1', onNavigate, onBook, onNotifications }) {
  const [sheet, setSheet] = useState(null);
  const [liveMessages, setLiveMessages] = useState(liveSeed); const [liveDraft, setLiveDraft] = useState('');
  const loadLiveMessages = async () => { try { setLiveMessages(await Database.getChatMessages('homepage-live', liveSeed)); } catch { setLiveMessages(liveSeed); } };
  useEffect(() => { loadLiveMessages(); const timer = setInterval(loadLiveMessages, 5000); return () => clearInterval(timer); }, []);
  const sendLiveMessage = async () => { const text = liveDraft.trim(); if (!text) return; const message = { user: fullName || 'Bạn', authorEmail: userEmail, role: 'MENTEE', text, createdAt: new Date().toISOString() }; setLiveDraft(''); setLiveMessages(previous => [...previous, message]); try { await Database.saveChatMessage('homepage-live', message); } catch { /* local preview remains available while offline */ } };
  const mentorList = mentors.length ? mentors.slice(0, 3).map((item, index) => ({ ...item, initials: item.name.split(' ').slice(-2).map(part => part[0]).join(''), color: ['#102A56', '#173F83', '#315A9D'][index] })) : fallbackMentors;
  const nextBooking = [...bookings].sort((a, b) => String(a.dateTime).localeCompare(String(b.dateTime)))[0];
  const termCourses = courses.filter(course => !course.term || course.term === currentTerm).slice(0, 3);
  const documents = recentDocuments.filter(doc => !doc.term || doc.term === currentTerm).slice(0, 2);

  return <ScrollView style={styles.screen} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.topRow}>
      <View><Text style={styles.brand}>PSIFU · {currentTerm}</Text><Text style={styles.greeting}>Chào, {fullName?.split(' ').slice(-1)[0] || 'bạn'} 👋</Text><Text style={styles.eyebrow}>Hôm nay bạn muốn học gì?</Text></View>
      <View style={styles.topActions}><TouchableOpacity accessibilityLabel="Thông báo" style={styles.calendarButton} onPress={onNotifications}><Ionicons name="notifications-outline" size={18} color="#155EEF" /><View style={styles.notificationDot}/></TouchableOpacity><TouchableOpacity accessibilityLabel="Mở lịch mentoring" style={styles.calendarButton} onPress={() => onNavigate('schedule')}><Ionicons name="calendar-outline" size={18} color="#155EEF" /></TouchableOpacity><View style={styles.xu}><Ionicons name="wallet-outline" size={15} color="#173F83" /><Text style={styles.xuText}>{userXu} Xu</Text></View></View>
    </View>

    <View style={styles.quickRow}>
      <QuickAction icon="people-outline" label="Mentor" color="#E8F1FF" iconColor="#2563EB" onPress={() => onNavigate('mentor')} />
      <QuickAction icon="book-outline" label="Tài liệu" color="#EAF8F3" iconColor="#0F766E" onPress={() => onNavigate('docs')} />
      <QuickAction icon="chatbubbles-outline" label="Community" color="#F2EDFF" iconColor="#7C3AED" onPress={() => onNavigate('community')} />
      <QuickAction icon="calendar-outline" label="Lịch hẹn" color="#FFF1E6" iconColor="#C2410C" onPress={() => onNavigate('schedule')} />
    </View>

    <Text style={styles.nextTitle}>Việc tiếp theo</Text>
    <View style={styles.sessionCard}>
      <View style={styles.sessionTop}><Text style={styles.sessionBadge}>LỊCH MENTORING GẦN NHẤT</Text><Ionicons name="calendar-outline" size={18} color="#D7E5F7" /></View>
      {nextBooking ? <><Text style={styles.sessionTitle}>{nextBooking.course || 'Phiên mentoring'} · {nextBooking.mentorName}</Text><Text style={styles.sessionSub}>{nextBooking.dateTime}</Text><View style={styles.sessionFooter}><Text style={styles.time}>{nextBooking.status || 'Đang chờ xác nhận'}</Text><TouchableOpacity style={styles.sessionButton} onPress={() => onNavigate('schedule')}><Text style={styles.sessionButtonText}>Xem lịch  →</Text></TouchableOpacity></View></> : <View style={styles.emptyInverted}><View style={styles.emptyIconInverted}><Ionicons name="calendar-clear-outline" size={21} color="#FFFFFF" /></View><View style={{ flex: 1 }}><Text style={styles.sessionTitle}>Bạn chưa có lịch hẹn</Text><Text style={styles.sessionSub}>Tìm mentor phù hợp và chọn khung giờ đang trống.</Text></View><TouchableOpacity style={styles.sessionButton} onPress={() => onNavigate('mentor')}><Text style={styles.sessionButtonText}>Tìm mentor</Text></TouchableOpacity></View>}
    </View>

    <TouchableOpacity style={styles.streakCard} activeOpacity={.9} onPress={() => onNavigate('profile')}>
      <View style={styles.streakHeader}><View style={styles.streakTitleWrap}><View style={styles.fireIcon}><Text style={styles.fireText}>🔥</Text></View><View><Text style={styles.streakTitle}>{hasCheckedInToday ? '4 ngày liên tiếp!' : 'Bắt đầu streak hôm nay!'}</Text><Text style={styles.streakCopy}>Tiếp tục học mỗi ngày để duy trì chuỗi.</Text></View></View><View style={styles.streakReward}><Text style={styles.streakRewardText}>{hasCheckedInToday ? '+2 Xu hôm nay' : '+1 Xu hôm nay'}</Text></View></View>
      <View style={styles.streakDays}>{['T2','T3','T4','T5','T6','T7','CN'].map((day, index) => { const complete = hasCheckedInToday ? index < 4 : index < 3; const today = hasCheckedInToday ? index === 3 : index === 2; return <View key={day} style={styles.streakDay}><View style={[styles.streakDot, complete && styles.streakDotComplete, today && styles.streakDotToday]}><Text style={[styles.streakMark, complete && styles.streakMarkComplete]}>{complete ? (today ? '🔥' : '✓') : index > 4 ? '🔒' : index + 1}</Text></View><Text style={[styles.streakDayText, today && styles.streakDayTextToday]}>{today ? 'Hôm nay' : day}</Text></View>; })}</View>
      <View style={styles.streakFooter}><Text style={styles.streakFooterText}>Phần thưởng đã sẵn sàng mở khóa</Text><View style={styles.claimPill}><Ionicons name="gift-outline" size={13} color="#fff"/><Text style={styles.claimText}>{hasCheckedInToday ? 'Đã nhận' : 'Nhận Xu'}</Text></View></View>
    </TouchableOpacity>

    <View style={styles.liveChatCard}>
      <View style={styles.liveChatHeader}><View><View style={styles.liveTitleRow}><Text style={styles.liveTitle}>PSIFU Chat</Text><View style={styles.liveBadge}><Text style={styles.liveBadgeText}>● LIVE</Text></View><View style={styles.onlineBadge}><Text style={styles.onlineBadgeText}>{onlinePeople.length + 28} Online</Text></View></View><Text style={styles.liveSubtitle}>Trò chuyện cùng mọi người đang online.</Text></View><Text style={styles.fullscreenText}>Kênh chung</Text></View>
      <View style={styles.liveContent}><View style={styles.liveFeed}>{liveMessages.slice(-4).map((message, index) => <View key={message._id || `${message.createdAt}-${index}`} style={styles.liveMessage}><View style={styles.liveMessageHead}><Text style={styles.liveAuthor}>{message.user}</Text><Text style={[styles.liveRole, message.role === 'MENTOR' && styles.liveRoleMentor]}>{message.role || 'MENTEE'}</Text></View><Text numberOfLines={2} style={styles.liveText}>{message.text}</Text></View>)}</View><View style={styles.onlineList}>{onlinePeople.map(person => <View key={person.name} style={styles.onlinePerson}><View style={styles.onlineAvatar}><Text style={styles.onlineAvatarText}>{person.name.slice(0, 1)}</Text></View><View style={{flex:1}}><Text numberOfLines={1} style={styles.onlineName}>{person.name}</Text><Text style={styles.onlineRole}>● {person.role}</Text></View></View>)}<Text style={styles.moreOnline}>+27 khác</Text></View></View>
      <View style={styles.liveComposer}><TextInput value={liveDraft} onChangeText={setLiveDraft} placeholder="Nhắn tin với mọi người…" placeholderTextColor="#8A9AB5" style={styles.liveInput} onSubmitEditing={sendLiveMessage} /><TouchableOpacity style={styles.liveSend} onPress={sendLiveMessage}><Ionicons name="send" size={16} color="#FFFFFF" /></TouchableOpacity></View>
    </View>

    <View style={styles.heading}><Text style={styles.sectionTitle}>Môn đang học · {currentTerm}</Text><TouchableOpacity onPress={() => setSheet({type:'courses',title:`Môn học · ${currentTerm}`,items:courses.filter(course => !course.term || course.term === currentTerm)})}><Text style={styles.seeAll}>Xem tất cả  ›</Text></TouchableOpacity></View>
    {termCourses.length ? <View style={styles.courseList}>{termCourses.map((course, index) => <TouchableOpacity key={course.code} style={styles.learningCourse} onPress={() => setSheet({type:'course',title:course.code,item:course})}><View style={styles.learningCourseIcon}><Text style={styles.learningCourseCode}>{course.code?.slice(0, 3)}</Text></View><View style={{ flex: 1 }}><Text style={styles.learningCourseTitle}>{course.code} · {course.name}</Text><Text style={styles.learningCourseSub}>Tài liệu và thảo luận môn học</Text></View><Ionicons name="chevron-forward" size={18} color="#173F83" /></TouchableOpacity>)}</View> : <EmptyState icon="book-outline" title="Chưa có môn học cho kỳ này" description="Hoàn tất thông tin học tập để PSIFU gợi ý đúng môn của bạn." action="Thiết lập hồ sơ" onPress={() => onNavigate('profile')} />}

    <View style={styles.heading}><Text style={styles.sectionTitle}>Tài liệu gần đây</Text><TouchableOpacity onPress={() => setSheet({type:'documents',title:'Tài liệu đề xuất',items:documents})}><Text style={styles.seeAll}>Khám phá  ›</Text></TouchableOpacity></View>
    {documents.length ? <View style={styles.docRow}>{documents.map((doc, index) => <TouchableOpacity key={doc.id || doc._id || index} style={styles.docCard} onPress={() => setSheet({type:'document',title:'Chi tiết tài liệu',item:doc})}><View style={styles.docIcon}><Ionicons name="document-text-outline" color="#173F83" size={25} /></View><Text style={styles.course}>{doc.course || currentTerm}</Text><Text numberOfLines={2} style={styles.docName}>{doc.title || doc.fileName}</Text><Text style={styles.documentMentor}>{doc.mentorName || 'Tài liệu PSIFU'}</Text></TouchableOpacity>)}</View> : <EmptyState icon="document-text-outline" title="Chưa có tài liệu gần đây" description="Mở hoặc lưu tài liệu để truy cập nhanh tại đây." action="Khám phá tài liệu" onPress={() => setSheet({type:'documents',title:'Tài liệu đề xuất',items:[]})} compact />}

    <View style={styles.heading}><Text style={styles.sectionTitle}>Mentor đề xuất</Text><TouchableOpacity onPress={() => setSheet({type:'mentors',title:'Mentor phù hợp với bạn',items:mentorList})}><Text style={styles.seeAll}>Xem tất cả  ›</Text></TouchableOpacity></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.mentorRow}>
      {mentorList.map(mentor => <TouchableOpacity key={mentor.id} style={styles.mentorCard} onPress={() => onBook(mentor)}>
        <View style={[styles.avatar, { backgroundColor: mentor.color }]}><Text style={styles.avatarText}>{mentor.initials}</Text></View>
        <Text numberOfLines={1} style={styles.mentorName}>{mentor.name}</Text><Text numberOfLines={1} style={styles.mentorRole}>{mentor.role}</Text>
        <View style={styles.rating}><Ionicons name="star" color="#173F83" size={12} /><Text style={styles.ratingText}>4.8</Text></View>
      </TouchableOpacity>)}
    </ScrollView>

    <Text style={styles.sectionTitle}>Cộng đồng</Text>
    <TouchableOpacity style={styles.communityCard} onPress={() => onNavigate('community')}><View style={styles.circleIcon}><Ionicons name="chatbubble-outline" color="#fff" size={22} /></View><View style={{ flex: 1 }}><Text style={styles.communityLabel}>CỘNG ĐỒNG PSIFU</Text><Text style={styles.communityTitle}>Kết nối cùng sinh viên</Text><Text style={styles.communitySub}>Chia sẻ câu hỏi, tài liệu và kinh nghiệm.</Text></View><Ionicons name="arrow-forward-circle" color="#fff" size={30} /></TouchableOpacity>

    <TouchableOpacity style={styles.progressCard} onPress={() => onNavigate('docs')}><View style={styles.progressIcon}><Ionicons name="school-outline" color="#155eef" size={23} /></View><View style={{ flex: 1 }}><Text style={styles.progressTitle}>Lộ trình {currentTerm}</Text><Text style={styles.progressSub}>Xem môn học, tài liệu và tiến độ của bạn.</Text><View style={styles.progressTrack}><View style={styles.progressFill} /></View></View><Ionicons name="chevron-forward" color="#155eef" size={22} /></TouchableOpacity>
    <HomeSheet sheet={sheet} onClose={() => setSheet(null)} onBook={onBook} />
  </ScrollView>;
}

function HomeSheet({ sheet, onClose, onBook }) { if (!sheet) return null; const item=sheet.item; const list=sheet.items || []; return <Modal transparent animationType="fade" visible onRequestClose={onClose}><View style={styles.sheetOverlay}><TouchableOpacity style={styles.sheetBackdrop} activeOpacity={1} onPress={onClose}/><View style={styles.sheet}><View style={styles.sheetHandle}/><View style={styles.sheetHeader}><View><Text style={styles.sheetEyebrow}>{sheet.type === 'mentors' ? 'KẾT NỐI 1–1' : 'PSIFU LEARNING'}</Text><Text style={styles.sheetTitle}>{sheet.title}</Text></View><TouchableOpacity style={styles.sheetClose} onPress={onClose}><Ionicons name="close" size={20} color="#102A56"/></TouchableOpacity></View>{item ? <View style={styles.detailBlock}><View style={styles.sheetIcon}><Ionicons name={sheet.type === 'document' ? 'document-text-outline' : 'book-outline'} size={24} color="#1976D2"/></View><Text style={styles.detailTitle}>{item.name || item.title || item.fileName}</Text><Text style={styles.detailCopy}>{item.code ? `${item.code} · ` : ''}{item.course || item.term || 'Tài liệu học tập'}. Nội dung, tài liệu và hoạt động liên quan được tổng hợp cho bạn tại đây.</Text><TouchableOpacity style={styles.sheetPrimary} onPress={onClose}><Text style={styles.sheetPrimaryText}>ĐÃ HIỂU</Text></TouchableOpacity></View> : list.length ? <ScrollView style={styles.sheetList} showsVerticalScrollIndicator={false}>{list.map((entry,index)=><TouchableOpacity key={entry.id || entry.code || index} style={styles.sheetRow} onPress={() => sheet.type === 'mentors' ? onBook(entry) : undefined}><View style={[styles.sheetRowIcon,{backgroundColor:sheet.type === 'mentors' ? '#F2EDFF' : '#EEF7FF'}]}><Ionicons name={sheet.type === 'mentors' ? 'person-outline' : sheet.type === 'documents' ? 'document-text-outline' : 'book-outline'} size={18} color={sheet.type === 'mentors' ? '#7C3AED' : '#1976D2'}/></View><View style={{flex:1}}><Text style={styles.sheetRowTitle}>{entry.name || entry.title || entry.fileName}</Text><Text style={styles.sheetRowSub}>{entry.code || entry.role || entry.course || 'Nội dung học tập'}</Text></View>{sheet.type === 'mentors' ? <Text style={styles.bookText}>Đặt lịch</Text> : <Ionicons name="chevron-forward" size={18} color="#5D7BA5"/>}</TouchableOpacity>)}</ScrollView> : <View style={styles.sheetEmpty}><Ionicons name="sparkles-outline" size={30} color="#1976D2"/><Text style={styles.sheetEmptyTitle}>Đang chọn lọc nội dung</Text><Text style={styles.sheetEmptyCopy}>Các gợi ý mới sẽ xuất hiện ngay tại đây.</Text></View>}</View></View></Modal>; }

function EmptyState({ icon, title, description, action, onPress, compact = false }) {
  return <View style={[styles.emptyState, compact && styles.emptyStateCompact]}><View style={styles.emptyStateIcon}><Ionicons name={icon} size={22} color="#173F83" /></View><View style={{ flex: 1 }}><Text style={styles.emptyStateTitle}>{title}</Text><Text style={styles.emptyStateDescription}>{description}</Text>{action ? <TouchableOpacity onPress={onPress}><Text style={styles.emptyStateAction}>{action}  →</Text></TouchableOpacity> : null}</View></View>;
}
function QuickAction({ icon, label, color, iconColor, onPress }) { return <TouchableOpacity style={styles.quickAction} onPress={onPress}><View style={[styles.quickIcon, { backgroundColor: color }]}><Ionicons name={icon} size={20} color={iconColor} /></View><Text style={styles.quickLabel}>{label}</Text></TouchableOpacity>; }

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#FAFCFF' }, content: { padding: 20, paddingBottom: 28 }, topRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 17 }, topActions:{flexDirection:'row',alignItems:'center',gap:8}, calendarButton:{width:35,height:35,borderRadius:12,backgroundColor:'#EAF1FF',alignItems:'center',justifyContent:'center',position:'relative'},notificationDot:{position:'absolute',width:7,height:7,borderRadius:4,backgroundColor:'#F04438',right:7,top:7,borderWidth:1,borderColor:'#fff'}, brand: { fontSize: 10, color: '#173F83', fontWeight: '900', letterSpacing: .7, marginBottom: 3 }, eyebrow: { fontSize: 11, color: '#64748b', marginTop: 3 }, greeting: { fontSize: 25, color: '#102a56', fontWeight: '900' }, xu: { flexDirection: 'row', gap: 6, alignItems: 'center', backgroundColor: '#E8EFF8', borderRadius: 20, paddingHorizontal: 11, paddingVertical: 8 }, xuText: { color: '#102A56', fontSize: 12, fontWeight: '800' }, quickRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 23 }, quickAction: { alignItems: 'center', width: '23%' }, quickIcon: { width: 48, height: 48, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, quickLabel: { color: '#355476', fontSize: 10, fontWeight: '800', marginTop: 6 },
  nextTitle: { color: '#102A56', fontSize: 15, fontWeight: '900', marginBottom: 10 }, sessionCard: { backgroundColor: '#102A56', borderRadius: 16, padding: 16, shadowColor: '#102A56', shadowOpacity: .2, shadowRadius: 12, elevation: 3, marginBottom: 22 }, sessionTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, sessionBadge: { color: '#D7E5F7', fontSize: 10, fontWeight: '800' }, sessionTitle: { color: '#fff', fontSize: 17, fontWeight: '800', marginTop: 10 }, sessionSub: { color: '#D7E5F7', fontSize: 12, marginTop: 4, lineHeight: 17 }, sessionFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 15 }, time: { color: '#E8EFF8', fontSize: 12 }, sessionButton: { backgroundColor: '#fff', paddingHorizontal: 12, paddingVertical: 7, borderRadius: 15 }, sessionButtonText: { color: '#102A56', fontWeight: '800', fontSize: 11 }, emptyInverted: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 12 }, emptyIconInverted: { width: 40, height: 40, borderRadius: 12, backgroundColor: '#315A9D', justifyContent: 'center', alignItems: 'center' },
  streakCard:{backgroundColor:'#FFFFFF',borderRadius:15,borderWidth:1,borderColor:'#E7ECF7',padding:13,marginTop:-10,marginBottom:22,shadowColor:'#183B73',shadowOpacity:.06,shadowRadius:9,elevation:1},streakHeader:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},streakTitleWrap:{flexDirection:'row',alignItems:'center',gap:8,flex:1},fireIcon:{width:35,height:35,borderRadius:12,backgroundColor:'#FFF2DC',alignItems:'center',justifyContent:'center'},fireText:{fontSize:18},streakTitle:{color:'#102A56',fontSize:14,fontWeight:'900'},streakCopy:{color:'#64748B',fontSize:9,marginTop:2},streakReward:{backgroundColor:'#FFF7E7',borderRadius:12,paddingHorizontal:8,paddingVertical:6},streakRewardText:{color:'#C76B00',fontSize:8,fontWeight:'800'},streakDays:{flexDirection:'row',justifyContent:'space-between',marginTop:14},streakDay:{alignItems:'center',width:'14%'},streakDot:{width:27,height:27,borderRadius:14,backgroundColor:'#EEF1FB',alignItems:'center',justifyContent:'center'},streakDotComplete:{backgroundColor:'#155EEF'},streakDotToday:{backgroundColor:'#FF9D00'},streakMark:{fontSize:9,color:'#8291AB',fontWeight:'800'},streakMarkComplete:{color:'#FFF',fontSize:12},streakDayText:{fontSize:8,color:'#71809A',marginTop:5},streakDayTextToday:{color:'#155EEF',fontWeight:'800'},streakFooter:{borderTopWidth:1,borderTopColor:'#F0F3F8',marginTop:12,paddingTop:10,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},streakFooterText:{color:'#64748B',fontSize:9},claimPill:{flexDirection:'row',alignItems:'center',gap:4,backgroundColor:'#FF9D00',borderRadius:7,paddingHorizontal:8,paddingVertical:5},claimText:{color:'#FFF',fontSize:8,fontWeight:'800'},
  liveChatCard:{backgroundColor:'#FFFFFF',borderRadius:15,borderWidth:1,borderColor:'#E7ECF7',padding:12,marginBottom:22},liveChatHeader:{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:'#EEF2F8',paddingBottom:10},liveTitleRow:{flexDirection:'row',alignItems:'center',gap:5},liveTitle:{color:'#102A56',fontSize:14,fontWeight:'900'},liveBadge:{backgroundColor:'#FFF0F0',borderRadius:6,paddingHorizontal:5,paddingVertical:2},liveBadgeText:{color:'#E11D48',fontSize:7,fontWeight:'900'},onlineBadge:{backgroundColor:'#EAF1FF',borderRadius:7,paddingHorizontal:6,paddingVertical:2},onlineBadgeText:{color:'#155EEF',fontSize:7,fontWeight:'800'},liveSubtitle:{color:'#64748B',fontSize:9,marginTop:3},fullscreenText:{color:'#155EEF',fontSize:8,fontWeight:'800',marginTop:3},liveContent:{flexDirection:'row',gap:8,paddingTop:10},liveFeed:{flex:1,gap:7},liveMessage:{backgroundColor:'#F1F4FC',borderRadius:8,padding:7},liveMessageHead:{flexDirection:'row',alignItems:'center',gap:4},liveAuthor:{color:'#102A56',fontSize:8,fontWeight:'900'},liveRole:{backgroundColor:'#E4EAF7',color:'#587093',fontSize:6,fontWeight:'800',paddingHorizontal:4,paddingVertical:1,borderRadius:4},liveRoleMentor:{backgroundColor:'#155EEF',color:'#FFFFFF'},liveText:{color:'#40536F',fontSize:9,lineHeight:13,marginTop:3},onlineList:{width:90,borderLeftWidth:1,borderLeftColor:'#EEF2F8',paddingLeft:7,gap:6},onlinePerson:{flexDirection:'row',alignItems:'center',gap:4},onlineAvatar:{width:18,height:18,borderRadius:9,backgroundColor:'#DDE8FF',alignItems:'center',justifyContent:'center'},onlineAvatarText:{color:'#155EEF',fontSize:7,fontWeight:'900'},onlineName:{color:'#233B62',fontSize:7,fontWeight:'800'},onlineRole:{color:'#20A46A',fontSize:6},moreOnline:{color:'#64748B',fontSize:7,textAlign:'center',marginTop:2},liveComposer:{flexDirection:'row',alignItems:'center',gap:7,borderTopWidth:1,borderTopColor:'#EEF2F8',paddingTop:9,marginTop:9},liveInput:{flex:1,height:31,borderRadius:8,backgroundColor:'#F1F4FC',paddingHorizontal:9,color:'#102A56',fontSize:9},liveSend:{width:31,height:31,borderRadius:16,backgroundColor:'#155EEF',alignItems:'center',justifyContent:'center'},
  heading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, sectionTitle: { color: '#102a56', fontSize: 15, fontWeight: '800', marginBottom: 11 }, seeAll: { color: '#2563eb', fontSize: 11, fontWeight: '700', marginBottom: 11 }, mentorRow: { gap: 10, paddingBottom: 22 }, mentorCard: { width: 118, minHeight: 135, backgroundColor: '#fff', borderWidth: 1, borderColor: '#dbe5f6', borderRadius: 13, padding: 11, alignItems: 'center' }, avatar: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', marginBottom: 8 }, avatarText: { color: '#fff', fontWeight: '800', fontSize: 12 }, mentorName: { color: '#102a56', fontSize: 11, fontWeight: '800', maxWidth: 94 }, mentorRole: { color: '#64748b', fontSize: 9, marginTop: 4, maxWidth: 94 }, rating: { flexDirection: 'row', alignItems: 'center', gap: 3, marginTop: 7 }, ratingText: { color: '#64748b', fontSize: 10 },
  communityCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#173F83', borderRadius: 13, padding: 14, gap: 12, marginBottom: 23 }, circleIcon: { backgroundColor: 'rgba(255,255,255,.2)', width: 42, height: 42, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, communityLabel: { color: '#D7E5F7', fontWeight: '800', fontSize: 9 }, communityTitle: { color: '#fff', fontWeight: '800', fontSize: 14, marginTop: 2 }, communitySub: { color: '#E8EFF8', fontSize: 10, marginTop: 3 },
  courseList: { gap: 9, marginBottom: 22 }, learningCourse: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DCE6F4', borderRadius: 13, padding: 11 }, learningCourseIcon: { width: 42, height: 42, borderRadius: 11, backgroundColor: '#EEF4FC', justifyContent: 'center', alignItems: 'center' }, learningCourseCode: { color: '#173F83', fontWeight: '900', fontSize: 10 }, learningCourseTitle: { color: '#102A56', fontWeight: '800', fontSize: 12 }, learningCourseSub: { color: '#64748B', fontSize: 10, marginTop: 4 }, docRow: { flexDirection: 'row', gap: 10, marginBottom: 22 }, docCard: { flex: 1, backgroundColor: '#fff', borderRadius: 13, borderColor: '#dbe5f6', borderWidth: 1, padding: 10, minHeight: 132 }, docIcon: { height: 44, borderRadius: 10, backgroundColor: '#EEF4FC', alignItems: 'center', justifyContent: 'center', marginBottom: 9 }, course: { color: '#173F83', fontSize: 9, fontWeight: '800' }, docName: { color: '#102a56', fontWeight: '700', fontSize: 11, marginTop: 3 }, documentMentor: { color: '#64748B', fontSize: 9, marginTop: 7 }, emptyState: { flexDirection: 'row', gap: 12, alignItems: 'center', backgroundColor: '#F8FAFD', borderWidth: 1, borderStyle: 'dashed', borderColor: '#B8CDF0', borderRadius: 13, padding: 15, marginBottom: 22 }, emptyStateCompact: { marginBottom: 22 }, emptyStateIcon: { width: 42, height: 42, borderRadius: 12, backgroundColor: '#EEF4FC', justifyContent: 'center', alignItems: 'center' }, emptyStateTitle: { color: '#102A56', fontWeight: '800', fontSize: 12 }, emptyStateDescription: { color: '#64748B', fontSize: 10, lineHeight: 15, marginTop: 3 }, emptyStateAction: { color: '#173F83', fontSize: 11, fontWeight: '800', marginTop: 8 },
  progressCard: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: '#eaf2ff', borderWidth: 1, borderColor: '#c7ddff', padding: 14, borderRadius: 13 }, progressIcon: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: '#dbeafe' }, progressTitle: { color: '#102a56', fontWeight: '800', fontSize: 13 }, progressSub: { color: '#64748b', fontSize: 10, marginTop: 3 }, progressTrack: { height: 5, borderRadius: 3, backgroundColor: '#bfdbfe', marginTop: 9, overflow: 'hidden' }, progressFill: { width: '35%', height: '100%', backgroundColor: '#2563eb', borderRadius: 3 },
  sheetOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(8,25,55,.35)' }, sheetBackdrop: { ...StyleSheet.absoluteFillObject }, sheet: { maxHeight: '74%', backgroundColor: '#FFFFFF', borderTopLeftRadius: 25, borderTopRightRadius: 25, padding: 18, paddingBottom: 28 }, sheetHandle: { alignSelf: 'center', width: 38, height: 4, backgroundColor: '#D5E0EE', borderRadius: 3, marginBottom: 14 }, sheetHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 }, sheetEyebrow: { fontSize: 9, fontWeight: '900', color: '#1976D2', letterSpacing: .7 }, sheetTitle: { color: '#102A56', fontSize: 19, fontWeight: '900', marginTop: 3 }, sheetClose: { width: 36, height: 36, borderRadius: 12, backgroundColor: '#F2F6FC', alignItems: 'center', justifyContent: 'center' }, sheetList: { maxHeight: 390 }, sheetRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 11, borderBottomWidth: 1, borderBottomColor: '#EDF2F8' }, sheetRowIcon: { width: 39, height: 39, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, sheetRowTitle: { color: '#102A56', fontSize: 12, fontWeight: '800' }, sheetRowSub: { color: '#64748B', fontSize: 10, marginTop: 3 }, detailBlock: { alignItems: 'center', paddingVertical: 10 }, sheetIcon: { width: 58, height: 58, borderRadius: 18, backgroundColor: '#EEF7FF', alignItems: 'center', justifyContent: 'center', marginBottom: 12 }, detailTitle: { color: '#102A56', fontSize: 16, fontWeight: '900', textAlign: 'center' }, detailCopy: { color: '#60728C', fontSize: 11, lineHeight: 17, textAlign: 'center', marginTop: 8 }, sheetPrimary: { height: 45, borderRadius: 13, backgroundColor: '#1976D2', alignSelf: 'stretch', alignItems: 'center', justifyContent: 'center', marginTop: 18 }, sheetPrimaryText: { color: '#FFFFFF', fontSize: 11, fontWeight: '900' }, sheetEmpty: { alignItems: 'center', paddingVertical: 34 }, sheetEmptyTitle: { color: '#102A56', fontWeight: '900', marginTop: 10 }, sheetEmptyCopy: { color: '#64748B', fontSize: 11, marginTop: 4 }
});
