import React, { useMemo, useState } from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import DirectMessage from './DirectMessage';

const statusLabel = (status) => { const value = String(status || '').toLowerCase(); if (value.includes('xác nhận')) return 'ĐÃ XÁC NHẬN'; if (value.includes('hoàn thành')) return 'ĐÃ HOÀN THÀNH'; if (value.includes('hủy')) return 'ĐÃ HỦY'; return 'CHỜ XÁC NHẬN'; };

export default function MentorInbox({ mentors = [], bookings = [], menteeName }) {
  const [chat, setChat] = useState(null);
  const conversations = useMemo(() => {
    const rows = new Map();
    bookings.forEach((booking) => {
      const id = booking.mentorEmail || booking.mentorId || booking.mentorName;
      if (!id) return;
      const mentor = mentors.find(item => item.id === id || item.email === id) || { id, name: booking.mentorName || 'Mentor PSIFU', role: 'Mentor PSIFU' };
      const previous = rows.get(id);
      if (!previous || String(booking.dateTime || '') > String(previous.booking.dateTime || '')) rows.set(id, { mentor, booking });
    });
    return [...rows.values()];
  }, [bookings, mentors]);
  if (chat) return <DirectMessage mentorName={chat.mentor.name} mentorEmail={chat.mentor.id} menteeName={menteeName} booking={chat.booking} onBack={() => setChat(null)} />;
  return <ScrollView style={s.screen} contentContainerStyle={s.content}><View style={s.hero}><View style={s.heroIcon}><Ionicons name="chatbubbles" size={22} color="#fff" /></View><View style={{flex:1}}><Text style={s.title}>Mentor Chat</Text><Text style={s.sub}>Mentor tự động xuất hiện ở đây ngay khi bạn đặt lịch.</Text></View><View style={s.count}><Text style={s.countText}>{conversations.length}</Text></View></View><Text style={s.heading}>Cuộc trò chuyện của bạn</Text>{conversations.length ? conversations.map(({ mentor, booking }, index) => <TouchableOpacity key={mentor.id} style={s.row} onPress={() => setChat({ mentor, booking })}><View style={[s.avatar, {backgroundColor:['#155EEF','#7C3AED','#0F766E'][index % 3]}]}><Text style={s.avatarText}>{mentor.name?.slice(0,1)}</Text><View style={s.online}/></View><View style={{flex:1}}><View style={s.nameRow}><Text style={s.name}>{mentor.name}</Text><View style={[s.status, statusLabel(booking.status) === 'ĐÃ XÁC NHẬN' && s.statusConfirmed]}><Text style={[s.statusText, statusLabel(booking.status) === 'ĐÃ XÁC NHẬN' && s.statusTextConfirmed]}>{statusLabel(booking.status)}</Text></View></View><Text numberOfLines={1} style={s.preview}>{booking.course || 'Phiên mentoring'} · {booking.dateTime || 'Đang chờ lịch'}</Text><Text style={s.openText}>Nhấn để trò chuyện riêng  →</Text></View><Ionicons name="chevron-forward" size={18} color="#71829D" /></TouchableOpacity>) : <View style={s.empty}><Ionicons name="calendar-outline" size={35} color="#1976D2" /><Text style={s.emptyTitle}>Chưa có lịch mentoring</Text><Text style={s.emptyCopy}>Sau khi bạn đặt lịch, mentor tương ứng sẽ tự động xuất hiện trong danh sách chat này.</Text></View>}</ScrollView>;
}
const s = StyleSheet.create({screen:{flex:1,backgroundColor:'#fff'},content:{padding:16,paddingBottom:30},hero:{backgroundColor:'#EEF4FF',borderRadius:17,padding:15,flexDirection:'row',alignItems:'center',gap:11},heroIcon:{width:43,height:43,borderRadius:14,backgroundColor:'#155EEF',alignItems:'center',justifyContent:'center'},title:{color:'#102A56',fontSize:17,fontWeight:'900'},sub:{color:'#526F98',fontSize:10,marginTop:4,lineHeight:14},count:{width:24,height:24,borderRadius:12,backgroundColor:'#155EEF',alignItems:'center',justifyContent:'center'},countText:{color:'#fff',fontSize:11,fontWeight:'900'},heading:{color:'#102A56',fontWeight:'900',fontSize:13,marginTop:21,marginBottom:9},row:{minHeight:82,borderWidth:1,borderColor:'#DCE6F4',borderRadius:14,padding:11,flexDirection:'row',alignItems:'center',gap:10,marginBottom:8,backgroundColor:'#fff'},avatar:{width:43,height:43,borderRadius:15,alignItems:'center',justifyContent:'center',position:'relative'},avatarText:{color:'#fff',fontWeight:'900'},online:{position:'absolute',right:-1,bottom:-1,width:11,height:11,borderRadius:6,backgroundColor:'#22C55E',borderWidth:2,borderColor:'#fff'},nameRow:{flexDirection:'row',alignItems:'center',gap:5},name:{color:'#102A56',fontSize:12,fontWeight:'900'},status:{backgroundColor:'#FFF3DD',paddingHorizontal:5,paddingVertical:2,borderRadius:4},statusConfirmed:{backgroundColor:'#DCFCE7'},statusText:{color:'#B45309',fontSize:6,fontWeight:'900'},statusTextConfirmed:{color:'#16803C'},preview:{color:'#71829D',fontSize:9,marginTop:4},openText:{color:'#155EEF',fontWeight:'800',fontSize:8,marginTop:4},empty:{alignItems:'center',paddingTop:60,paddingHorizontal:28},emptyTitle:{color:'#102A56',fontWeight:'900',marginTop:10},emptyCopy:{color:'#64748B',fontSize:10,marginTop:5,lineHeight:15,textAlign:'center'}});
