import React, { useMemo, useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';

export default function MyDocuments({ documents = [], unlockedDocs = {}, onOpen }) {
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('catalog');
  const items = useMemo(() => documents.filter(doc => {
    const matches = `${doc.name || doc.title || ''} ${doc.code || doc.course || ''}`.toLowerCase().includes(query.trim().toLowerCase());
    return matches && (filter !== 'unlocked' || unlockedDocs[doc.id || doc.code]);
  }), [documents, filter, query, unlockedDocs]);
  const unlocked = documents.filter(doc => unlockedDocs[doc.id || doc.code]);
  const source = items;
  return <ScrollView style={s.screen} contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
    <View style={s.top}><View><Text style={s.title}>My Documents</Text><Text style={s.sub}>Tài liệu và tiến độ học của bạn</Text></View><View style={s.avatar}><Ionicons name="person" size={16} color="#fff" /></View></View>
    <View style={s.search}><Ionicons name="search-outline" size={18} color="#71829D" /><TextInput value={query} onChangeText={setQuery} placeholder="Tìm trong tài liệu của tôi..." placeholderTextColor="#8A9BB5" style={s.input} /></View>
    <View style={s.tabs}>{[['catalog','Khám phá'],['unlocked','Đã mở khóa']].map(([key,label]) => <TouchableOpacity key={key} onPress={() => setFilter(key)} style={[s.tab, filter === key && s.tabOn]}><Text style={[s.tabText, filter === key && s.tabTextOn]}>{label}</Text></TouchableOpacity>)}</View>
    <View style={s.sectionHead}><Text style={s.section}>Tài liệu của bạn</Text><Text style={s.count}>{unlocked.length} đã mở khóa</Text></View>
    {source.map((doc, index) => { const id = doc.id || doc.code; const open = !!unlockedDocs[id] || Number(doc.fee || 0) === 0; return <TouchableOpacity key={id || index} activeOpacity={.85} style={s.card} onPress={() => onOpen({ ...doc, id, name: doc.name || doc.title })}><View style={s.icon}><Ionicons name="document-text" size={21} color="#155EEF" /></View><View style={s.cardMain}><View style={s.cardTitleRow}><Text style={s.code}>{doc.code || doc.course || 'STUDY GUIDE'}</Text><Ionicons name={open ? 'bookmark' : 'lock-closed'} size={14} color="#155EEF" /></View><Text style={s.name} numberOfLines={1}>{doc.name || doc.title}</Text><Text style={s.meta}>{doc.mentorName ? `Mentor ${doc.mentorName}` : 'PSIFU Learning Library'} · {doc.term || 'Học kỳ hiện tại'}</Text>{open ? <><View style={s.progressTrack}><View style={[s.progressFill,{width:index === 0 ? '50%' : '18%'}]} /></View><View style={s.cardBottom}><Text style={s.progressText}>{index === 0 ? 'Tiến độ đọc: 12 / 24 trang' : 'Chưa bắt đầu'}</Text><View style={s.action}><Ionicons name={index === 0 ? 'reader-outline' : 'play'} size={13} color="#fff" /><Text style={s.actionText}>{index === 0 ? 'Tiếp tục đọc' : 'Đọc tài liệu'}</Text></View></View></> : <Text style={s.locked}>Mở khóa để đọc · {doc.fee || 0} Xu</Text>}</View></TouchableOpacity>; })}
    {!source.length && <View style={s.empty}><Ionicons name="folder-open-outline" size={26} color="#71829D" /><Text style={s.emptyTitle}>Chưa có tài liệu phù hợp</Text><Text style={s.emptyCopy}>Tài liệu được mở khóa sẽ xuất hiện ở đây để bạn học tiếp.</Text></View>}
    <View style={s.privacy}><Ionicons name="shield-checkmark-outline" size={16} color="#155EEF" /><View style={{flex:1}}><Text style={s.privacyTitle}>Quy tắc tổ chức học liệu</Text><Text style={s.privacyCopy}>Tiến độ đọc được lưu theo tài khoản. Nội dung đầy đủ chỉ mở sau khi hệ thống xác nhận quyền truy cập.</Text></View></View>
  </ScrollView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#F8F7FF'},content:{padding:16,paddingBottom:30},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:14},title:{fontSize:21,fontWeight:'900',color:'#102A56'},sub:{fontSize:10,color:'#71829D',marginTop:3},avatar:{width:32,height:32,borderRadius:16,backgroundColor:'#155EEF',alignItems:'center',justifyContent:'center'},search:{height:42,backgroundColor:'#fff',borderWidth:1,borderColor:'#DCE6F4',borderRadius:11,alignItems:'center',flexDirection:'row',paddingHorizontal:11,gap:7},input:{flex:1,color:'#102A56',fontSize:12},tabs:{flexDirection:'row',gap:7,marginVertical:13},tab:{paddingHorizontal:10,paddingVertical:7,borderRadius:12,backgroundColor:'#EEF2F8'},tabOn:{backgroundColor:'#155EEF'},tabText:{fontSize:9,color:'#64748B',fontWeight:'800'},tabTextOn:{color:'#fff'},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:9},section:{fontWeight:'900',fontSize:13,color:'#102A56'},count:{fontSize:9,color:'#155EEF',fontWeight:'800'},card:{backgroundColor:'#fff',borderRadius:14,borderWidth:1,borderColor:'#E1E8F4',padding:11,flexDirection:'row',gap:10,marginBottom:10},icon:{width:39,height:43,borderRadius:10,backgroundColor:'#E8F0FF',alignItems:'center',justifyContent:'center'},cardMain:{flex:1},cardTitleRow:{flexDirection:'row',justifyContent:'space-between'},code:{fontSize:8,fontWeight:'900',color:'#155EEF'},name:{fontSize:13,color:'#102A56',fontWeight:'900',marginTop:3},meta:{fontSize:9,color:'#71829D',marginTop:3},progressTrack:{height:4,backgroundColor:'#E6ECF6',borderRadius:4,overflow:'hidden',marginTop:9},progressFill:{height:'100%',backgroundColor:'#155EEF'},cardBottom:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:8},progressText:{fontSize:8,color:'#64748B'},action:{backgroundColor:'#155EEF',borderRadius:7,paddingHorizontal:8,paddingVertical:5,flexDirection:'row',gap:4,alignItems:'center'},actionText:{fontSize:8,color:'#fff',fontWeight:'900'},locked:{fontSize:9,color:'#C76B00',fontWeight:'800',marginTop:9},empty:{alignItems:'center',padding:27,backgroundColor:'#fff',borderRadius:14,borderWidth:1,borderStyle:'dashed',borderColor:'#C9D6E8'},emptyTitle:{color:'#102A56',fontWeight:'900',marginTop:8},emptyCopy:{color:'#71829D',fontSize:10,textAlign:'center',marginTop:4},privacy:{marginTop:5,backgroundColor:'#F1F5FF',borderRadius:12,padding:11,flexDirection:'row',gap:8},privacyTitle:{fontSize:10,color:'#155EEF',fontWeight:'900'},privacyCopy:{fontSize:9,color:'#64748B',lineHeight:13,marginTop:3}});
