import React, { useCallback, useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Database } from '../data/database';

const fallback = [
  { id:'appointment', type:'APPOINTMENT', title:'Booking Confirmed', body:'Phiên mentoring PRF192 của bạn đã được xác nhận.', createdAt:new Date().toISOString(), read:false },
  { id:'mentor-chat', type:'CHAT', title:'Mentor Chat', body:'Mentor đã gửi cho bạn một tin nhắn mới.', createdAt:new Date(Date.now()-5*60000).toISOString(), read:false },
  { id:'document', type:'DOCUMENT', title:'New Document', body:'Có tài liệu ôn tập mới được chia sẻ cho môn học của bạn.', createdAt:new Date(Date.now()-86400000).toISOString(), read:true },
];
const icon = { APPOINTMENT:'calendar-outline', CHAT:'chatbubble-ellipses-outline', DOCUMENT:'document-text-outline', PREMIUM:'wallet-outline' };
export default function Notifications({ email, onBack }) { const [items,setItems]=useState(fallback); const [filter,setFilter]=useState('all'); const load=useCallback(async()=>{try{const data=await Database.getNotifications(email); setItems(data.length?data:fallback)}catch{setItems(fallback)}},[email]); useEffect(()=>{load()},[load]); const unread=items.filter(x=>!x.read).length; const shown=items.filter(x=>filter==='all'||x.type===filter); const markAll=async()=>{await Promise.all(items.filter(x=>!x.read&&/^[a-f0-9]{24}$/i.test(String(x.id))).map(x=>Database.markNotificationRead(x.id).catch(()=>null)));setItems(prev=>prev.map(x=>({...x,read:true})));}; return <ScrollView style={s.screen} contentContainerStyle={s.content}><View style={s.top}><TouchableOpacity onPress={onBack}><Ionicons name="chevron-back" size={24} color="#102A56" /></TouchableOpacity><Text style={s.title}>Notifications</Text><TouchableOpacity onPress={markAll}><Text style={s.mark}>Đánh dấu đã đọc</Text></TouchableOpacity></View><View style={s.summary}><View style={s.summaryIcon}><Ionicons name="notifications" size={18} color="#155EEF" /></View><View><Text style={s.summaryTitle}>{unread} thông báo mới</Text><Text style={s.summaryCopy}>Nhắc lịch học, mentor chat và tài liệu</Text></View></View><View style={s.filters}>{[['all','Tất cả'],['APPOINTMENT','Lịch hẹn'],['CHAT','Tin nhắn'],['DOCUMENT','Tài liệu']].map(([key,label])=><TouchableOpacity key={key} style={[s.filter,filter===key&&s.filterOn]} onPress={()=>setFilter(key)}><Text style={[s.filterText,filter===key&&s.filterTextOn]}>{label}</Text></TouchableOpacity>)}</View><Text style={s.group}>HÔM NAY</Text>{shown.map(item=><TouchableOpacity key={item.id} style={[s.card,!item.read&&s.unread]} onPress={async()=>{if(!item.read){try{if(/^[a-f0-9]{24}$/i.test(String(item.id)))await Database.markNotificationRead(item.id)}catch{}setItems(prev=>prev.map(x=>x.id===item.id?{...x,read:true}:x))}}}><View style={s.icon}><Ionicons name={icon[item.type]||'notifications-outline'} size={20} color="#155EEF" /></View><View style={{flex:1}}><Text style={s.tag}>{item.type==='APPOINTMENT'?'Appointments':item.type==='CHAT'?'Private 1-on-1':'Documents'}</Text><Text style={s.cardTitle}>{item.title}</Text><Text style={s.body}>{item.body}</Text><Text style={s.time}>{new Date(item.createdAt).toLocaleString('vi-VN')}</Text></View>{!item.read&&<View style={s.dot}/>}</TouchableOpacity>)}<View style={s.info}><Ionicons name="bulb-outline" size={18} color="#155EEF" /><Text style={s.infoText}>Bạn có thể thay đổi loại thông báo trong Profile → Thông báo ứng dụng.</Text></View></ScrollView>; }
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#FAFAFF'},content:{padding:16,paddingBottom:32},top:{height:42,flexDirection:'row',alignItems:'center',gap:12},title:{flex:1,color:'#102A56',fontWeight:'900',fontSize:18},mark:{color:'#155EEF',fontSize:10,fontWeight:'900'},summary:{backgroundColor:'#EEF4FF',borderRadius:14,padding:12,marginTop:11,flexDirection:'row',gap:10,alignItems:'center'},summaryIcon:{width:38,height:38,borderRadius:13,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},summaryTitle:{fontWeight:'900',color:'#102A56',fontSize:13},summaryCopy:{color:'#64748B',fontSize:9,marginTop:3},filters:{flexDirection:'row',gap:7,marginTop:14,marginBottom:17},filter:{paddingHorizontal:10,paddingVertical:7,borderRadius:14,backgroundColor:'#EEF1F8'},filterOn:{backgroundColor:'#155EEF'},filterText:{color:'#64748B',fontSize:9,fontWeight:'800'},filterTextOn:{color:'#fff'},group:{fontSize:11,color:'#536E99',fontWeight:'900',letterSpacing:.5,marginBottom:8},card:{backgroundColor:'#fff',borderRadius:14,borderWidth:1,borderColor:'#E0E8F5',padding:12,flexDirection:'row',gap:10,marginBottom:9},unread:{borderColor:'#C6D9FF',backgroundColor:'#F7FAFF'},icon:{width:42,height:42,borderRadius:14,backgroundColor:'#E6EEFF',alignItems:'center',justifyContent:'center'},tag:{alignSelf:'flex-start',backgroundColor:'#DDE8FF',borderRadius:7,paddingHorizontal:6,paddingVertical:3,color:'#315A9D',fontSize:8,fontWeight:'800'},cardTitle:{color:'#102A56',fontSize:15,fontWeight:'900',marginTop:6},body:{color:'#40536F',fontSize:11,lineHeight:16,marginTop:4},time:{color:'#8A9BB5',fontSize:8,marginTop:8},dot:{width:7,height:7,borderRadius:4,backgroundColor:'#155EEF',marginTop:5},info:{flexDirection:'row',gap:8,padding:12,backgroundColor:'#EEF2FF',borderRadius:12,marginTop:8},infoText:{flex:1,color:'#536E99',fontSize:10,lineHeight:15}});
