import React,{useEffect,useRef,useState}from'react';
import {ActivityIndicator,Alert,Linking,ScrollView,StyleSheet,Text,TouchableOpacity,View}from'react-native';
import {Ionicons}from'@expo/vector-icons';
import {Database}from'../data/database';

export default function PayOSPayment({coins,email,onPaid,onCancel}){
  const [order,setOrder]=useState(null); const [loading,setLoading]=useState(true); const [checking,setChecking]=useState(false); const [error,setError]=useState(''); const [checkout,setCheckout]=useState(false); const finished=useRef(false);
  useEffect(()=>{let mounted=true;Database.createPayosTopup(email,coins).then(value=>mounted&&setOrder(value)).catch(e=>mounted&&setError(e?.data?.msg||e.message||'Không thể tạo đơn PayOS.')).finally(()=>mounted&&setLoading(false));return()=>{mounted=false}},[email,coins]);
  const checkStatus=async(silent=false)=>{if(!order?.orderCode||finished.current)return;setChecking(true);try{const value=await Database.getPayosOrder(order.orderCode);if(value.status==='PAID'){finished.current=true;onPaid(value);return;}if(!silent)Alert.alert('Chưa có xác nhận','PayOS chưa xác nhận giao dịch. Ứng dụng sẽ tự kiểm tra lại.');}catch(e){if(!silent)Alert.alert('Không thể kiểm tra',e?.data?.msg||'Vui lòng thử lại.')}finally{setChecking(false)}};
  useEffect(()=>{if(!order?.orderCode)return;const id=setInterval(()=>checkStatus(true),5000);return()=>clearInterval(id)},[order?.orderCode]);
  return <View style={s.screen}><View style={s.header}><TouchableOpacity onPress={onCancel}><Ionicons name="chevron-back" size={25} color="#102A56"/></TouchableOpacity><Text style={s.title}>Thanh toán PayOS</Text><Ionicons name="shield-checkmark" size={20} color="#155EEF"/></View><ScrollView contentContainerStyle={s.content}>{loading?<View style={s.center}><ActivityIndicator color="#155EEF" size="large"/><Text style={s.muted}>Đang tạo đơn thanh toán PayOS...</Text></View>:error?<View style={s.error}><Ionicons name="alert-circle-outline" size={28} color="#D92D20"/><Text style={s.errorTitle}>Chưa thể tạo giao dịch</Text><Text style={s.errorText}>{error}</Text><TouchableOpacity style={s.primary} onPress={onCancel}><Text style={s.primaryText}>QUAY LẠI</Text></TouchableOpacity></View>:<><View style={s.hero}><Text style={s.tag}>PAYOS · VIETQR BẢO MẬT</Text><Text style={s.amount}>{Number(order.amount).toLocaleString('vi-VN')} đ</Text><Text style={s.coin}>Nạp {coins} Xu vào Ví PSIFU</Text><View style={s.order}><Text style={s.orderLabel}>MÃ ĐƠN HÀNG</Text><Text style={s.orderCode}>#{order.orderCode}</Text></View></View><View style={s.info}><Ionicons name="qr-code-outline" size={21} color="#155EEF"/><View style={{flex:1}}><Text style={s.infoTitle}>QR PayOS đã sẵn sàng</Text><Text style={s.infoText}>Mở checkout PayOS trong trình duyệt để quét QR an toàn.</Text></View></View><View style={s.steps}><Step n="1" text="Mở QR thanh toán PayOS"/><Step n="2" text="Quét QR hoặc chọn ngân hàng"/><Step n="3" text="App tự nhận webhook xác nhận"/></View><TouchableOpacity style={s.primary} onPress={()=>Linking.openURL(order.checkoutUrl)}><Ionicons name="qr-code" size={18} color="#fff"/><Text style={s.primaryText}>MỞ QR PAYOS</Text></TouchableOpacity><TouchableOpacity style={s.secondary} disabled={checking} onPress={()=>checkStatus(false)}><Ionicons name="sync-outline" size={18} color="#155EEF"/><Text style={s.secondaryText}>{checking?'ĐANG KIỂM TRA...':'KIỂM TRA TRẠNG THÁI'}</Text></TouchableOpacity><Text style={s.note}>Đơn PayOS #{order.orderCode} · Xu chỉ cộng sau khi webhook hợp lệ được máy chủ xác minh.</Text></>}</ScrollView></View>;
}
function Step({n,text}){return <View style={s.step}><Text style={s.number}>{n}</Text><Text style={s.stepText}>{text}</Text><Ionicons name="checkmark-circle-outline" size={17} color="#155EEF"/></View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#FAFAFF'},header:{height:55,backgroundColor:'#fff',paddingHorizontal:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderColor:'#E6ECF6'},title:{fontSize:16,fontWeight:'900',color:'#102A56'},content:{padding:16,paddingBottom:34},center:{alignItems:'center',paddingTop:100,gap:14},muted:{fontSize:12,color:'#64748B'},hero:{borderRadius:18,backgroundColor:'#155EEF',padding:19},tag:{fontSize:9,fontWeight:'900',color:'#DCE9FF',letterSpacing:.6},amount:{fontSize:31,fontWeight:'900',color:'#fff',marginTop:9},coin:{fontSize:12,color:'#E6EEFF',marginTop:2},order:{marginTop:17,backgroundColor:'rgba(255,255,255,.16)',borderRadius:10,padding:10,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},orderLabel:{fontSize:8,fontWeight:'900',color:'#DCE9FF'},orderCode:{fontSize:12,fontWeight:'900',color:'#fff'},info:{marginTop:14,backgroundColor:'#EEF3FF',borderRadius:12,padding:13,flexDirection:'row',gap:9},infoTitle:{fontSize:11,fontWeight:'900',color:'#102A56'},infoText:{color:'#526F98',fontSize:10,lineHeight:15,marginTop:3},steps:{marginTop:14,backgroundColor:'#fff',borderWidth:1,borderColor:'#E0E8F5',borderRadius:13,padding:12,gap:10},step:{flexDirection:'row',alignItems:'center',gap:9},number:{width:22,height:22,borderRadius:11,overflow:'hidden',textAlign:'center',paddingTop:4,backgroundColor:'#DDE8FF',color:'#155EEF',fontSize:10,fontWeight:'900'},stepText:{flex:1,color:'#102A56',fontSize:11,fontWeight:'700'},primary:{height:48,borderRadius:12,backgroundColor:'#155EEF',marginTop:17,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:7},primaryText:{color:'#fff',fontWeight:'900',fontSize:11},secondary:{height:45,borderRadius:12,backgroundColor:'#E7EEFF',marginTop:9,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:7},secondaryText:{color:'#155EEF',fontWeight:'900',fontSize:10},note:{fontSize:9,color:'#71829D',lineHeight:14,textAlign:'center',marginTop:12},webNote:{minHeight:45,backgroundColor:'#EEF3FF',paddingHorizontal:14,flexDirection:'row',alignItems:'center',gap:8},webNoteText:{flex:1,color:'#526F98',fontSize:9,lineHeight:13},error:{alignItems:'center',backgroundColor:'#fff',borderRadius:15,borderWidth:1,borderColor:'#FFD8D4',padding:22,marginTop:50},errorTitle:{fontSize:16,fontWeight:'900',color:'#102A56',marginTop:9},errorText:{fontSize:11,color:'#64748B',lineHeight:16,textAlign:'center',marginTop:6}});
