import React, { useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Database } from '../data/database';

export default function ForgotPassword({ onBack, onCodeSent }) {
  const [email, setEmail] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async () => {
    const normalizedEmail = email.trim().toLowerCase();
    if (!normalizedEmail.includes('@')) return setError('Vui lòng nhập một email hợp lệ.');
    setLoading(true); setError('');
    const result = await Database.sendPasswordResetCode(normalizedEmail);
    setLoading(false);
    if (!result.success) return setError(result.msg || 'Không thể gửi mã lúc này.');
    Alert.alert('Đã gửi mã OTP', `Mã xác minh đặt lại mật khẩu đã được gửi đến ${normalizedEmail}.`, [{ text: 'Nhập mã', onPress: () => onCodeSent(normalizedEmail) }]);
  };
  return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.content}><View style={styles.top}><TouchableOpacity style={styles.back} onPress={onBack}><Ionicons name="arrow-back" size={22} color="#355476" /></TouchableOpacity><Text style={styles.brand}>PSIFU</Text></View><View style={styles.lock}><Ionicons name="lock-closed-outline" size={62} color="#2563EB" /><View style={styles.question}><Text style={styles.questionText}>?</Text></View></View><Text style={styles.title}>Quên mật khẩu?</Text><Text style={styles.subtitle}>Nhập email học tập, PSIFU sẽ gửi mã xác minh để bạn đặt lại mật khẩu.</Text><Text style={styles.label}>Email học tập</Text><View style={[styles.inputWrap, error && styles.inputError]}><Ionicons name="mail-outline" size={20} color="#7185A2" /><TextInput style={styles.input} value={email} onChangeText={(value) => { setEmail(value); setError(''); }} placeholder="name@fpt.edu.vn" placeholderTextColor="#8194AE" autoCapitalize="none" keyboardType="email-address" editable={!loading} /></View>{error ? <Text style={styles.error}>{error}</Text> : null}<View style={styles.note}><Ionicons name="information-circle-outline" size={17} color="#2563EB" /><Text style={styles.noteText}>Dùng email đã liên kết với tài khoản PSIFU của bạn.</Text></View><TouchableOpacity style={[styles.button, loading && { opacity: 0.65 }]} onPress={submit} disabled={loading}><Text style={styles.buttonText}>{loading ? 'ĐANG GỬI...' : 'GỬI MÃ ĐẶT LẠI'}</Text></TouchableOpacity></View></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#F7F9FF' }, content: { flex: 1, padding: 29, paddingTop: 28 }, top: { flexDirection: 'row', alignItems: 'center' }, back: { width: 42, height: 42, borderRadius: 12, borderWidth: 1, borderColor: '#C9D6E8', backgroundColor: '#FFFFFF', justifyContent: 'center', alignItems: 'center' }, brand: { color: '#102A56', fontWeight: '900', fontSize: 20, marginLeft: 96 }, lock: { height: 169, justifyContent: 'center', alignItems: 'center' }, question: { position: 'absolute', marginLeft: 66, marginTop: 15, width: 25, height: 25, borderRadius: 14, backgroundColor: '#2563EB', alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#F7F9FF' }, questionText: { color: '#fff', fontWeight: '900' }, title: { color: '#102A56', fontSize: 29, fontWeight: '800' }, subtitle: { color: '#667992', fontSize: 15, lineHeight: 22, marginTop: 9, marginBottom: 37 }, label: { color: '#233B62', fontSize: 13, fontWeight: '700', marginBottom: 8 }, inputWrap: { height: 58, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#C9D6E8', borderRadius: 13, paddingHorizontal: 14, alignItems: 'center', flexDirection: 'row', gap: 11 }, inputError: { borderColor: '#E07171' }, input: { flex: 1, color: '#102A56', fontSize: 15 }, error: { color: '#B42318', fontSize: 12, marginTop: 9 }, note: { flexDirection: 'row', gap: 9, borderWidth: 1, borderColor: '#B8CDF0', backgroundColor: '#EEF5FF', padding: 14, borderRadius: 11, marginTop: 39 }, noteText: { color: '#355476', flex: 1, fontSize: 12, lineHeight: 18 }, button: { height: 58, backgroundColor: '#2563EB', borderRadius: 13, justifyContent: 'center', alignItems: 'center', marginTop: 17 }, buttonText: { color: '#fff', fontWeight: '900', fontSize: 14 } });
