import React, { useEffect, useState } from 'react';
import { Image, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Database } from '../data/database';

export default function Login({ onLoginSuccess, onSwitchToRegister, onForgotPassword, prefilledEmail = '' }) {
  const [email, setEmail] = useState(prefilledEmail); const [password, setPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  useEffect(() => setEmail(prefilledEmail), [prefilledEmail]);
  const login = async () => {
    if (!email.trim() || !password) return setError('Vui lòng nhập đầy đủ email và mật khẩu.');
    setLoading(true); setError('');
    const result = await Database.checkLogin(email.trim(), password);
    setLoading(false);
    if (result.success) onLoginSuccess(result.user); else setError(result.msg || 'Không thể đăng nhập lúc này. Vui lòng thử lại.');
  };
  return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <View style={styles.brand}><Image source={require('../assets/logo.png')} style={styles.logo} resizeMode="contain" /><Text style={styles.brandName}>PSIFU</Text></View>
    <Text style={styles.title}>Sẵn sàng bứt phá?</Text><Text style={styles.subtitle}>Đăng nhập để tiếp tục hành trình học tập.</Text>
    <View style={styles.form}><Text style={styles.label}>Email học tập</Text><View style={[styles.inputWrap, error && styles.inputError]}><Ionicons name="mail-outline" size={20} color="#8092B1" /><TextInput style={styles.input} placeholder="name@fpt.edu.vn" placeholderTextColor="#71829D" value={email} onChangeText={(value) => { setEmail(value); setError(''); }} autoCapitalize="none" keyboardType="email-address" /></View>
      <Text style={styles.label}>Mật khẩu</Text><View style={[styles.inputWrap, error && styles.inputError]}><Ionicons name="lock-closed-outline" size={20} color="#8092B1" /><TextInput style={styles.input} placeholder="Nhập mật khẩu" placeholderTextColor="#71829D" value={password} onChangeText={(value) => { setPassword(value); setError(''); }} secureTextEntry={!showPassword} /><TouchableOpacity onPress={() => setShowPassword(!showPassword)}><Ionicons name={showPassword ? 'eye-off-outline' : 'eye-outline'} size={22} color="#8092B1" /></TouchableOpacity></View>
      {error ? <View style={styles.errorBox}><Ionicons name="alert-circle" size={17} color="#FCA5A5" /><Text style={styles.errorText}>{error}</Text></View> : null}
      <TouchableOpacity style={styles.forgot} onPress={onForgotPassword}><Text style={styles.forgotText}>Quên mật khẩu?</Text></TouchableOpacity>
      <TouchableOpacity style={[styles.loginButton, loading && styles.disabled]} onPress={login} disabled={loading}><Text style={styles.loginText}>{loading ? 'ĐANG ĐĂNG NHẬP...' : 'ĐĂNG NHẬP'}</Text></TouchableOpacity>
      <View style={styles.divider}><View style={styles.line} /><Text style={styles.or}>hoặc</Text><View style={styles.line} /></View><TouchableOpacity style={styles.googleButton}><Text style={styles.googleG}>G</Text><Text style={styles.googleText}>Tiếp tục với Google</Text></TouchableOpacity>
    </View><View style={styles.bottom}><Text style={styles.bottomText}>Chưa có tài khoản? </Text><TouchableOpacity onPress={onSwitchToRegister}><Text style={styles.register}>Đăng ký</Text></TouchableOpacity></View>
  </ScrollView></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#F7F9FF' }, content: { flexGrow: 1, paddingHorizontal: 29, paddingTop: 52, paddingBottom: 34 }, brand: { alignItems: 'center', marginBottom: 25 }, logo: { width: 76, height: 76 }, brandName: { color: '#102A56', fontSize: 21, fontWeight: '900', letterSpacing: 2.4, marginTop: 11 }, title: { color: '#102A56', fontSize: 28, fontWeight: '800' }, subtitle: { color: '#667992', fontSize: 14, marginTop: 7 }, form: { marginTop: 31 }, label: { color: '#233B62', fontWeight: '700', fontSize: 13, marginBottom: 8 }, inputWrap: { flexDirection: 'row', alignItems: 'center', gap: 11, backgroundColor: '#FFFFFF', borderColor: '#C9D6E8', borderWidth: 1, borderRadius: 13, paddingHorizontal: 14, height: 56, marginBottom: 17 }, inputError: { borderColor: '#E07171' }, input: { flex: 1, color: '#102A56', fontSize: 15 }, errorBox: { flexDirection: 'row', gap: 8, alignItems: 'center', borderWidth: 1, borderColor: '#E9B9B9', backgroundColor: '#FFF2F2', borderRadius: 10, padding: 10, marginTop: -7, marginBottom: 12 }, errorText: { color: '#B42318', flex: 1, fontSize: 12, lineHeight: 17 }, forgot: { alignSelf: 'flex-end', marginTop: -7, marginBottom: 23 }, forgotText: { color: '#2563EB', fontWeight: '700' }, loginButton: { height: 54, alignItems: 'center', justifyContent: 'center', borderRadius: 13, backgroundColor: '#2563EB' }, disabled: { opacity: .6 }, loginText: { color: '#fff', fontSize: 14, fontWeight: '800' }, divider: { flexDirection: 'row', gap: 12, alignItems: 'center', marginVertical: 23 }, line: { flex: 1, height: 1, backgroundColor: '#D7E0EE' }, or: { color: '#7B8EA9', fontSize: 13 }, googleButton: { borderColor: '#C9D6E8', backgroundColor: '#FFFFFF', borderWidth: 1, height: 54, borderRadius: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 12 }, googleG: { color: '#2563EB', fontSize: 22, fontWeight: '900' }, googleText: { color: '#233B62', fontWeight: '700', fontSize: 14 }, bottom: { flexDirection: 'row', justifyContent: 'center', marginTop: 27 }, bottomText: { color: '#64748B' }, register: { color: '#2563EB', fontWeight: '800' } });
