import React, { useEffect, useState } from 'react';
import { Image, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Database } from '../data/database';
import AuthSnowflakes from '../components/AuthSnowflakes';

export default function Login({ onLoginSuccess, onSwitchToRegister, onForgotPassword, prefilledEmail = '' }) {
  const [email, setEmail] = useState(prefilledEmail); const [password, setPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  useEffect(() => setEmail(prefilledEmail), [prefilledEmail]);
  const login = async () => { if (!email.trim() || !password) return setError('Vui lòng nhập đầy đủ email và mật khẩu.'); setLoading(true); setError(''); const result = await Database.checkLogin(email.trim(), password); setLoading(false); if (result.success) onLoginSuccess(result.user); else setError(result.msg || 'Không thể đăng nhập lúc này. Vui lòng thử lại.'); };
  return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled"><View style={styles.card}><AuthSnowflakes />
    <View style={styles.brand}><Image source={require('../assets/logo.png')} style={styles.logo} resizeMode="contain" /><View><Text style={styles.brandName}>PSIFU</Text><Text style={styles.brandSub}>FPT UNIVERSITY MENTORING</Text></View></View>
    <View style={styles.hero}><Text style={styles.title}>Learn smarter. <Text style={styles.titleAccent}>Grow together.</Text></Text><Text style={styles.subtitle}>Kết nối với Mentor, học cùng Community và tiến bộ hơn qua từng học kỳ.</Text></View>
    <View style={styles.form}><Text style={styles.label}>Email</Text><View style={[styles.inputWrap, error && styles.inputError]}><Ionicons name="mail-outline" size={16} color="#183B73" /><TextInput style={styles.input} placeholder="Nhập email của bạn" placeholderTextColor="#8A9AB5" value={email} onChangeText={(value) => { setEmail(value); setError(''); }} autoCapitalize="none" keyboardType="email-address" /></View>
      <View style={styles.passwordLabel}><Text style={styles.label}>Password</Text><TouchableOpacity onPress={onForgotPassword}><Text style={styles.forgotText}>Quên mật khẩu?</Text></TouchableOpacity></View><View style={[styles.inputWrap, error && styles.inputError]}><Ionicons name="lock-closed-outline" size={16} color="#183B73" /><TextInput style={styles.input} placeholder="Nhập mật khẩu" placeholderTextColor="#8A9AB5" value={password} onChangeText={(value) => { setPassword(value); setError(''); }} secureTextEntry={!showPassword} /><TouchableOpacity onPress={() => setShowPassword(!showPassword)}><Ionicons name={showPassword ? 'eye-off-outline' : 'eye-outline'} size={17} color="#183B73" /></TouchableOpacity></View>
      {error ? <Text style={styles.error}>{error}</Text> : null}<TouchableOpacity style={[styles.primaryButton, loading && styles.disabled]} onPress={login} disabled={loading}><Text style={styles.primaryText}>{loading ? 'ĐANG ĐĂNG NHẬP...' : 'Login  →'}</Text></TouchableOpacity>
    </View><View style={styles.bottom}><Text style={styles.bottomText}>Chưa có tài khoản? </Text><TouchableOpacity onPress={onSwitchToRegister}><Text style={styles.link}>Register ngay</Text></TouchableOpacity></View><View style={styles.notice}><Ionicons name="shield-checkmark-outline" size={13} color="#2664E8" /><Text style={styles.noticeText}>Hàng dành cho sinh viên Đại học FPT.</Text></View>
  </View></ScrollView></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({screen:{flex:1,backgroundColor:'#F1F3F9'},scroll:{flexGrow:1,justifyContent:'center',padding:18},card:{width:'100%',maxWidth:390,alignSelf:'center',overflow:'hidden',backgroundColor:'#FFF',borderRadius:8,paddingHorizontal:24,paddingTop:20,paddingBottom:18,shadowColor:'#1E40AF',shadowOpacity:.2,shadowRadius:14,elevation:5},pattern:{position:'absolute',right:-20,top:-20,width:122,height:122,opacity:.55},patternLineOne:{position:'absolute',width:145,height:2,backgroundColor:'#B8CEF9',transform:[{rotate:'45deg'}],top:39,left:-13},patternLineTwo:{position:'absolute',width:145,height:2,backgroundColor:'#B8CEF9',transform:[{rotate:'-45deg'}],top:39,left:-13},patternDiamond:{position:'absolute',width:48,height:48,borderWidth:2,borderColor:'#B8CEF9',transform:[{rotate:'45deg'}],top:24,left:35},brand:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},logo:{width:37,height:37,borderRadius:8},brandName:{fontSize:16,fontWeight:'900',color:'#0F3675',letterSpacing:.4},brandSub:{fontSize:6.5,fontWeight:'700',color:'#2360B9',letterSpacing:.45,marginTop:1},hero:{marginTop:29},title:{color:'#112F65',fontSize:17,fontWeight:'800',textAlign:'center'},titleAccent:{color:'#2463EE'},subtitle:{color:'#526987',fontSize:10,lineHeight:15,textAlign:'center',marginTop:5,paddingHorizontal:7},form:{marginTop:22},label:{fontSize:10,fontWeight:'800',color:'#152D5C'},passwordLabel:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:13,marginBottom:6},inputWrap:{height:37,flexDirection:'row',alignItems:'center',gap:9,backgroundColor:'#F0F2FD',borderRadius:8,paddingHorizontal:10,borderWidth:1,borderColor:'#EEF0FA'},inputError:{borderColor:'#E07171'},input:{flex:1,fontSize:10,color:'#142E5E'},forgotText:{fontSize:9,color:'#2463EE',fontWeight:'700'},error:{fontSize:9,color:'#C23434',marginTop:7},primaryButton:{height:39,borderRadius:7,backgroundColor:'#2864E8',alignItems:'center',justifyContent:'center',marginTop:14,shadowColor:'#2864E8',shadowOpacity:.27,shadowRadius:7,elevation:3},disabled:{opacity:.6},primaryText:{color:'#FFF',fontSize:11,fontWeight:'800'},bottom:{marginTop:14,flexDirection:'row',justifyContent:'center'},bottomText:{fontSize:9,color:'#536987'},link:{fontSize:9,color:'#2463EE',fontWeight:'800'},notice:{marginTop:20,minHeight:24,borderRadius:12,backgroundColor:'#F3F5FD',flexDirection:'row',gap:5,alignItems:'center',justifyContent:'center'},noticeText:{fontSize:8,color:'#5C7192'}});
