import React, { useState } from 'react';
import { Alert, Image, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { academicPrograms, defaultProgram } from '../data/academicPrograms';

const terms = ['Kỳ 1', 'Kỳ 2', 'Kỳ 3', 'Kỳ 4', 'Kỳ 5', 'Kỳ 6', 'Kỳ 7', 'Kỳ 8', 'Kỳ 9'];
export default function ProfileSetup({ onComplete }) {
  const [university, setUniversity] = useState('FPT University'); const [cohort, setCohort] = useState('K20'); const [studentId, setStudentId] = useState(''); const [term, setTerm] = useState('Kỳ 1'); const [groupId, setGroupId] = useState(defaultProgram.id); const [majorId, setMajorId] = useState(defaultProgram.majors[0].id); const [trackId, setTrackId] = useState(defaultProgram.majors[0].tracks[0]?.id || '');
  const selectedGroup = academicPrograms.find(item => item.id === groupId) || defaultProgram;
  const selectedMajor = selectedGroup.majors.find(item => item.id === majorId) || selectedGroup.majors[0];
  const selectedTrack = selectedMajor.tracks.find(item => item.id === trackId);
  const programInfo = { major: selectedGroup.name, specialization: selectedMajor.code, track: selectedTrack?.name || '' };
  const submit = () => { if (!studentId.trim()) return Alert.alert('Thiếu thông tin', 'Vui lòng nhập mã số sinh viên.'); onComplete({ university, fptK: cohort, studentId: studentId.trim(), ...programInfo, currentTerm: term, academicYear: 'Năm 1' }); };
  return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <View style={styles.brand}><Image source={require('../assets/logo.png')} style={styles.logo} resizeMode="contain" /><Text style={styles.brandName}>PSIFU</Text></View>
    <Text style={styles.title}>Thông tin của bạn</Text><Text style={styles.subtitle}>PSIFU sẽ cá nhân hóa Community và môn học theo lộ trình của bạn.</Text>
    <View style={styles.avatar}><Ionicons name="person-outline" color="#bfdbfe" size={30} /><View style={styles.plus}><Ionicons name="add" color="#fff" size={15} /></View></View>
    <Text style={styles.label}>TRƯỜNG ĐẠI HỌC</Text><View style={styles.readonly}><Ionicons name="school-outline" color="#60a5fa" size={18} /><Text style={styles.readonlyText}>{university}</Text></View>
    <Text style={styles.label}>NHÓM NGÀNH</Text><View style={{ gap: 8 }}>{academicPrograms.map(item => <TouchableOpacity key={item.id} style={{ minHeight: 52, borderWidth: 1, borderColor: groupId === item.id ? '#60a5fa' : '#34455f', borderRadius: 11, backgroundColor: groupId === item.id ? '#2563eb' : '#18263d', flexDirection: 'row', alignItems: 'center', gap: 11, paddingHorizontal: 13 }} onPress={() => { const nextMajor = item.majors[0]; setGroupId(item.id); setMajorId(nextMajor.id); setTrackId(nextMajor.tracks[0]?.id || ''); }}><Ionicons name={item.icon} color={groupId === item.id ? '#fff' : '#60a5fa'} size={18} /><Text style={{ flex: 1, color: '#fff', fontSize: 13, fontWeight: '700' }}>{item.code} · {item.name}</Text>{groupId === item.id && <Ionicons name="checkmark-circle" color="#fff" size={18} />}</TouchableOpacity>)}</View>
    <Text style={styles.label}>CHUYÊN NGÀNH</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.termRow}>{selectedGroup.majors.map(item => <TouchableOpacity key={item.id} style={[styles.term, majorId === item.id && styles.termActive]} onPress={() => { setMajorId(item.id); setTrackId(item.tracks[0]?.id || ''); }}><Text style={[styles.termText, majorId === item.id && styles.termTextActive]}>{item.code} · {item.name}</Text></TouchableOpacity>)}</ScrollView>
    {!!selectedMajor.tracks.length && <><Text style={styles.label}>HƯỚNG CHUYÊN SÂU</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.termRow}>{selectedMajor.tracks.map(item => <TouchableOpacity key={item.id} style={[styles.term, trackId === item.id && styles.termActive]} onPress={() => setTrackId(item.id)}><Text style={[styles.termText, trackId === item.id && styles.termTextActive]}>{item.name}</Text></TouchableOpacity>)}</ScrollView></>}
    <View style={styles.twoCols}><View style={{ flex: .42 }}><Text style={styles.label}>KHÓA</Text><TextInput style={styles.input} value={cohort} onChangeText={setCohort} placeholder="K20" /></View><View style={{ flex: .58 }}><Text style={styles.label}>MÃ SỐ SINH VIÊN</Text><TextInput style={styles.input} value={studentId} onChangeText={setStudentId} placeholder="VD: SE170001" autoCapitalize="characters" /></View></View>
    <Text style={styles.label}>KỲ HỌC HIỆN TẠI</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.termRow}>{terms.map(item => <TouchableOpacity key={item} style={[styles.term, term === item && styles.termActive]} onPress={() => setTerm(item)}><Text style={[styles.termText, term === item && styles.termTextActive]}>{item}</Text></TouchableOpacity>)}</ScrollView>
    <View style={styles.info}><Ionicons name="information-circle" color="#60a5fa" size={20} /><Text style={styles.infoText}>Community và danh sách môn học sẽ được tự động điều chỉnh theo kỳ học của bạn.</Text></View>
    <TouchableOpacity style={styles.submit} onPress={submit}><Text style={styles.submitText}>HOÀN TẤT THIẾT LẬP</Text><Ionicons name="arrow-forward" color="#fff" size={19} /></TouchableOpacity>
  </ScrollView></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#0b1730' }, content: { padding: 24, paddingTop: 54, paddingBottom: 30 }, brand: { flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 28 }, logo: { width: 32, height: 32 }, brandName: { color: '#fff', fontSize: 17, fontWeight: '900', letterSpacing: 1 }, title: { color: '#fff', fontSize: 28, fontWeight: '800' }, subtitle: { color: '#bfdbfe', lineHeight: 20, fontSize: 13, marginTop: 7 }, avatar: { height: 55, width: 55, borderRadius: 28, backgroundColor: '#1e2d47', justifyContent: 'center', alignItems: 'center', marginTop: 26, marginBottom: 22 }, plus: { position: 'absolute', right: -4, bottom: -3, width: 22, height: 22, borderRadius: 11, justifyContent: 'center', alignItems: 'center', backgroundColor: '#2563eb', borderWidth: 2, borderColor: '#0b1730' }, label: { color: '#93c5fd', fontSize: 10, fontWeight: '800', letterSpacing: .6, marginBottom: 7, marginTop: 13 }, readonly: { height: 46, borderWidth: 1, borderColor: '#34455f', borderRadius: 11, backgroundColor: '#18263d', flexDirection: 'row', alignItems: 'center', gap: 11, paddingHorizontal: 13 }, readonlyText: { color: '#fff', fontSize: 13, fontWeight: '600' }, twoCols: { flexDirection: 'row', gap: 11 }, input: { height: 46, borderWidth: 1, borderColor: '#34455f', borderRadius: 11, backgroundColor: '#18263d', paddingHorizontal: 13, color: '#fff', fontSize: 13, fontWeight: '600' }, termRow: { gap: 8, paddingBottom: 3 }, term: { borderColor: '#34455f', borderWidth: 1, borderRadius: 10, paddingHorizontal: 11, paddingVertical: 9, backgroundColor: '#18263d' }, termActive: { backgroundColor: '#2563eb', borderColor: '#60a5fa' }, termText: { color: '#bfdbfe', fontSize: 12, fontWeight: '700' }, termTextActive: { color: '#fff' }, info: { flexDirection: 'row', gap: 10, padding: 13, backgroundColor: '#162b4d', borderRadius: 13, marginTop: 19 }, infoText: { flex: 1, color: '#bfdbfe', fontSize: 12, lineHeight: 18 }, submit: { height: 54, marginTop: 25, borderRadius: 13, backgroundColor: '#2563eb', alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 9 }, submitText: { color: '#fff', fontWeight: '800', fontSize: 13 } });
