import React, { useState } from 'react';
import { Alert, Image, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Database } from '../data/database';
import AuthSnowflakes from '../components/AuthSnowflakes';

export default function Register({ onSwitchToLogin, onRegisterSuccess }) {
  const [fullName, setFullName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [showConfirm, setShowConfirm] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async () => { if (!fullName.trim() || !email.trim() || !password || !confirmPassword) return setError('Vui lòng điền đầy đủ các trường thông tin.'); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())) return setError('Email chưa đúng định dạng.'); if (password.length < 8) return setError('Mật khẩu cần có ít nhất 8 ký tự.'); if (password !== confirmPassword) return setError('Hai mật khẩu chưa trùng khớp.'); setLoading(true); setError(''); const user={fullName:fullName.trim(),email:email.trim().toLowerCase(),password,university:'',academicYear:'',fptK:'',currentTerm:'',userXu:20,hasCheckedInToday:false,isFirstLogin:true}; const result=await Database.saveUser(user); setLoading(false); if(!result.success)return setError(result.msg||'Không thể tạo tài khoản. Vui lòng thử lại.'); Alert.alert('Đăng ký thành công','Tài khoản đã được tạo. Bạn có thể đăng nhập ngay.',[{text:'Đến trang đăng nhập',onPress:()=>onRegisterSuccess(user.email)}]); };
  const field=(label,icon,value,change,placeholder,secure=false,shown=false,toggle=null,type='default')=><View><Text style={s.label}>{label}</Text><View style={s.inputWrap}><Ionicons name={icon} size={21} color="#183B73"/><TextInput style={s.input} value={value} onChangeText={v=>{change(v);setError('');}} placeholder={placeholder} placeholderTextColor="#8A9AB5" secureTextEntry={secure&&!shown} autoCapitalize="none" keyboardType={type}/>{secure&&<TouchableOpacity hitSlop={10} onPress={toggle}><Ionicons name={shown?'eye-off-outline':'eye-outline'} size={22} color="#183B73"/></TouchableOpacity>}</View></View>;
  return <KeyboardAvoidingView style={s.screen} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={s.scroll} keyboardShouldPersistTaps="handled"><View style={s.card}><AuthSnowflakes/><View style={s.top}><TouchableOpacity style={s.back} onPress={onSwitchToLogin}><Ionicons name="arrow-back" size={22} color="#102E63"/></TouchableOpacity><View style={s.brand}><Image source={require('../assets/logo.png')} style={s.logo}/><View><Text style={s.brandName}>PSIFU</Text><Text style={s.brandSub}>FPT MENTORING</Text></View></View></View><Text style={s.title}>Tạo tài khoản</Text><Text style={s.subtitle}>Tham gia PSIFU để bắt đầu hành trình học tập cùng cộng đồng.</Text><View style={s.form}>{field('Họ và tên','person-outline',fullName,setFullName,'Nhập họ và tên')}{field('Email','mail-outline',email,setEmail,'Nhập email của bạn',false,false,null,'email-address')}{field('Mật khẩu','lock-closed-outline',password,setPassword,'Tạo mật khẩu tối thiểu 8 ký tự',true,showPassword,()=>setShowPassword(!showPassword))}{field('Xác nhận mật khẩu','lock-closed-outline',confirmPassword,setConfirmPassword,'Nhập lại mật khẩu',true,showConfirm,()=>setShowConfirm(!showConfirm))}<Text style={s.hint}>Mật khẩu phải có ít nhất 8 ký tự.</Text>{error?<Text style={s.error}>{error}</Text>:null}<TouchableOpacity disabled={loading} style={[s.button,loading&&s.disabled]} onPress={submit}><Text style={s.buttonText}>{loading?'ĐANG TẠO TÀI KHOẢN...':'Tạo tài khoản  →'}</Text></TouchableOpacity></View><View style={s.bottom}><Text style={s.bottomText}>Đã có tài khoản? </Text><TouchableOpacity onPress={onSwitchToLogin}><Text style={s.link}>Đăng nhập</Text></TouchableOpacity></View></View></ScrollView></KeyboardAvoidingView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#F1F3F9'},scroll:{flexGrow:1,justifyContent:'center',padding:18},card:{width:'100%',maxWidth:460,alignSelf:'center',overflow:'hidden',backgroundColor:'#FFF',borderRadius:16,paddingHorizontal:28,paddingVertical:25,shadowColor:'#203F78',shadowOpacity:.17,shadowRadius:13,elevation:4},top:{height:48,flexDirection:'row',alignItems:'center'},back:{width:39,height:39,borderRadius:20,backgroundColor:'#F1F4FD',alignItems:'center',justifyContent:'center'},brand:{position:'absolute',left:0,right:0,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},logo:{width:37,height:37,borderRadius:8},brandName:{fontSize:18,fontWeight:'900',color:'#10326C'},brandSub:{fontSize:8,fontWeight:'700',color:'#2763B7'},title:{fontSize:27,fontWeight:'800',color:'#102E63',marginTop:20},subtitle:{fontSize:15,lineHeight:22,color:'#526987',marginTop:7},form:{marginTop:20},label:{fontSize:14,color:'#102E63',fontWeight:'800',marginBottom:7,marginTop:13},inputWrap:{height:52,borderRadius:10,backgroundColor:'#EFF1FC',paddingHorizontal:13,flexDirection:'row',alignItems:'center',gap:10,borderWidth:1,borderColor:'#E2E7F4'},input:{flex:1,color:'#142E5E',fontSize:16},hint:{fontSize:12,color:'#2463EE',marginTop:7},error:{fontSize:13,color:'#C23434',marginTop:9,lineHeight:18},button:{height:53,borderRadius:10,backgroundColor:'#2864E8',alignItems:'center',justifyContent:'center',marginTop:20},disabled:{opacity:.6},buttonText:{color:'#FFF',fontSize:16,fontWeight:'800'},bottom:{flexDirection:'row',justifyContent:'center',marginTop:20},bottomText:{fontSize:14,color:'#536987'},link:{fontSize:14,color:'#2463EE',fontWeight:'800'}});
