import React, { useState } from 'react';
import { Alert, Image, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Database } from '../data/database';
import AuthSnowflakes from '../components/AuthSnowflakes';

export default function Register({ onSwitchToLogin, onRegisterSuccess }) {
  const [fullName, setFullName] = useState(''), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [confirmPassword, setConfirmPassword] = useState(''), [showPassword, setShowPassword] = useState(false), [showConfirm, setShowConfirm] = useState(false), [error, setError] = useState('');
  const submit = async () => { if (!fullName.trim() || !email.trim() || !password || !confirmPassword) return setError('Vui lòng điền đầy đủ các trường thông tin.'); if (!email.includes('@')) return setError('Email chưa đúng định dạng.'); if (password.length < 6) return setError('Mật khẩu cần có ít nhất 6 ký tự.'); if (password !== confirmPassword) return setError('Hai mật khẩu chưa trùng khớp.'); const user={fullName:fullName.trim(),email:email.trim().toLowerCase(),password,university:'',academicYear:'',fptK:'',currentTerm:'',userXu:20,hasCheckedInToday:false,isFirstLogin:true}; const result=await Database.saveUser(user); if(!result.success)return setError(result.msg||'Không thể tạo tài khoản. Vui lòng thử lại.'); Alert.alert('Đăng ký thành công','Tài khoản đã được tạo. Bạn có thể đăng nhập ngay.',[{text:'Đến trang đăng nhập',onPress:()=>onRegisterSuccess(user.email)}]); };
  const field=(label,icon,value,change,placeholder,secure=false,shown=false,toggle=null,type='default')=><View><Text style={styles.label}>{label}</Text><View style={styles.inputWrap}><Ionicons name={icon} size={16} color="#183B73"/><TextInput style={styles.input} value={value} onChangeText={v=>{change(v);setError('');}} placeholder={placeholder} placeholderTextColor="#8A9AB5" secureTextEntry={secure&&!shown} autoCapitalize="none" keyboardType={type}/>{secure&&<TouchableOpacity onPress={toggle}><Ionicons name={shown?'eye-off-outline':'eye-outline'} size={17} color="#183B73"/></TouchableOpacity>}</View></View>;
  return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled"><View style={styles.card}><AuthSnowflakes/><View style={styles.top}><TouchableOpacity style={styles.back} onPress={onSwitchToLogin}><Ionicons name="arrow-back" size={17} color="#102E63"/></TouchableOpacity><View style={styles.brand}><Image source={require('../assets/logo.png')} style={styles.logo}/><View><Text style={styles.brandName}>PSIFU</Text><Text style={styles.brandSub}>FPT MENTORING</Text></View></View></View><Text style={styles.title}>Create your account</Text><Text style={styles.subtitle}>Tham gia PSIFU và bắt đầu hành trình học tập cùng Community.</Text><View style={styles.form}>{field('Họ và tên','person-outline',fullName,setFullName,'Nhập họ và tên')}{field('Email','mail-outline',email,setEmail,'Nhập email của bạn',false,false,null,'email-address')}{field('Password','lock-closed-outline',password,setPassword,'Tạo mật khẩu',true,showPassword,()=>setShowPassword(!showPassword))}<Text style={styles.hint}>• Mật khẩu phải có ít nhất 8 ký tự.</Text>{field('Xác nhận Password','lock-closed-outline',confirmPassword,setConfirmPassword,'Nhập lại mật khẩu',true,showConfirm,()=>setShowConfirm(!showConfirm))}<View style={styles.terms}><View style={styles.checkbox}/><Text style={styles.termsText}>Tôi đồng ý với <Text style={styles.termsLink}>Điều khoản sử dụng</Text> và <Text style={styles.termsLink}>Chính sách quyền riêng tư</Text>.</Text></View>{error?<Text style={styles.error}>{error}</Text>:null}<TouchableOpacity style={styles.button} onPress={submit}><Text style={styles.buttonText}>Create Account  →</Text></TouchableOpacity></View><View style={styles.bottom}><Text style={styles.bottomText}>Đã có tài khoản? </Text><TouchableOpacity onPress={onSwitchToLogin}><Text style={styles.link}>Login</Text></TouchableOpacity></View></View></ScrollView></KeyboardAvoidingView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#F1F3F9'},scroll:{flexGrow:1,justifyContent:'center',padding:18},card:{width:'100%',maxWidth:390,alignSelf:'center',overflow:'hidden',backgroundColor:'#FFF',borderRadius:7,paddingHorizontal:24,paddingVertical:17,shadowColor:'#203F78',shadowOpacity:.17,shadowRadius:13,elevation:4},top:{height:38,flexDirection:'row',alignItems:'center'},back:{width:27,height:27,borderRadius:14,backgroundColor:'#F1F4FD',alignItems:'center',justifyContent:'center'},brand:{position:'absolute',left:0,right:0,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6},logo:{width:25,height:25,borderRadius:6},brandName:{fontSize:12,fontWeight:'900',color:'#10326C'},brandSub:{fontSize:5.5,fontWeight:'700',color:'#2763B7'},title:{fontSize:18,fontWeight:'800',color:'#102E63',marginTop:12},subtitle:{fontSize:9.5,lineHeight:14,color:'#526987',marginTop:5},form:{marginTop:15},label:{fontSize:9.5,color:'#102E63',fontWeight:'800',marginBottom:5,marginTop:9},inputWrap:{height:34,borderRadius:7,backgroundColor:'#EFF1FC',paddingHorizontal:10,flexDirection:'row',alignItems:'center',gap:8},input:{flex:1,color:'#142E5E',fontSize:10},hint:{fontSize:7.5,color:'#2463EE',marginTop:4},terms:{flexDirection:'row',gap:6,alignItems:'flex-start',marginTop:13},checkbox:{width:12,height:12,borderRadius:3,backgroundColor:'#E8ECF8',marginTop:1},termsText:{flex:1,fontSize:7.5,lineHeight:11,color:'#536987'},termsLink:{color:'#2463EE'},error:{fontSize:8.5,color:'#C23434',marginTop:6},button:{height:37,borderRadius:7,backgroundColor:'#2864E8',alignItems:'center',justifyContent:'center',marginTop:14},buttonText:{color:'#FFF',fontSize:10,fontWeight:'800'},bottom:{flexDirection:'row',justifyContent:'center',marginTop:15},bottomText:{fontSize:8.5,color:'#536987'},link:{fontSize:8.5,color:'#2463EE',fontWeight:'800'}});
