import React, { useState } from 'react';
import { Alert, Image, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Database } from '../data/database';

export default function Register({ onSwitchToLogin, onRegisterSuccess }) {
  const [fullName, setFullName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [showConfirm, setShowConfirm] = useState(false); const [error, setError] = useState('');
  const submit = async () => {
    if (!fullName.trim() || !email.trim() || !password || !confirmPassword) return setError('Vui lòng điền đầy đủ các trường thông tin.');
    if (!email.trim().includes('@')) return setError('Email chưa đúng định dạng.');
    if (password.length < 6) return setError('Mật khẩu cần có ít nhất 6 ký tự.');
    if (password !== confirmPassword) return setError('Hai mật khẩu chưa trùng khớp.');
    const user = { fullName: fullName.trim(), email: email.trim().toLowerCase(), password, university: '', academicYear: '', fptK: '', currentTerm: '', userXu: 20, hasCheckedInToday: false, isFirstLogin: true };
    const result = await Database.saveUser(user);
    if (!result.success) return setError(result.msg || 'Không thể tạo tài khoản. Vui lòng thử lại.');
    Alert.alert('Đăng ký thành công', 'Cảm ơn bạn đã đăng ký. Hãy xác minh email để tiếp tục.', [{ text: 'Xác minh email', onPress: () => onRegisterSuccess(user.email) }]);
  };
  const field = (label, icon, value, change, placeholder, secure, shown, toggle, type) => <><Text style={styles.label}>{label}</Text><View style={styles.inputWrap}><Ionicons name={icon} size={20} color="#8194B1" /><TextInput style={styles.input} value={value} onChangeText={(v) => { change(v); setError(''); }} placeholder={placeholder} placeholderTextColor="#71829D" secureTextEntry={secure && !shown} autoCapitalize="none" keyboardType={type} />{secure ? <TouchableOpacity onPress={toggle}><Ionicons name={shown ? 'eye-off-outline' : 'eye-outline'} size={21} color="#8194B1" /></TouchableOpacity> : null}</View></>;
  return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.top}><TouchableOpacity style={styles.back} onPress={onSwitchToLogin}><Ionicons name="arrow-back" size={22} color="#102A56" /></TouchableOpacity><View style={styles.brand}><View style={styles.logoStage}><Image source={require('../assets/logo.png')} style={styles.logo} resizeMode="contain" /></View><Text style={styles.brandText}>PSIFU</Text></View></View><Text style={styles.title}>Tạo tài khoản</Text><Text style={styles.subtitle}>Gia nhập cộng đồng học tập PSIFU.</Text><View style={styles.form}>{field('Họ và tên', 'person-outline', fullName, setFullName, 'Nhập họ và tên')}{field('Email học tập', 'mail-outline', email, setEmail, 'name@fpt.edu.vn', false, false, null, 'email-address')}{field('Mật khẩu', 'lock-closed-outline', password, setPassword, 'Tạo mật khẩu', true, showPassword, () => setShowPassword(!showPassword))}{field('Xác nhận mật khẩu', 'lock-closed-outline', confirmPassword, setConfirmPassword, 'Nhập lại mật khẩu', true, showConfirm, () => setShowConfirm(!showConfirm))}<View style={styles.note}><Ionicons name="information-circle-outline" size={17} color="#173F83" /><Text style={styles.noteText}>Dùng email học tập để xác minh tài khoản sinh viên.</Text></View>{error ? <Text style={styles.error}>{error}</Text> : null}<TouchableOpacity style={styles.button} onPress={submit}><Text style={styles.buttonText}>TẠO TÀI KHOẢN</Text></TouchableOpacity></View><View style={styles.bottom}><Text style={styles.bottomText}>Đã có tài khoản? </Text><TouchableOpacity onPress={onSwitchToLogin}><Text style={styles.login}>Đăng nhập</Text></TouchableOpacity></View></ScrollView></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#FFFFFF' }, content: { padding: 29, paddingTop: 28, paddingBottom: 34 }, top: { flexDirection: 'row', alignItems: 'center', marginBottom: 35 }, back: { width: 42, height: 42, borderRadius: 12, borderWidth: 1, borderColor: '#C9D6E8', backgroundColor: '#FFFFFF', justifyContent: 'center', alignItems: 'center' }, brand: { flexDirection: 'row', alignItems: 'center', marginLeft: 56 }, logoStage:{width:44,height:44,alignItems:'center',justifyContent:'center'}, logo: { width: 40, height: 40, borderRadius: 9 }, brandText: { color: '#102A56', fontWeight: '900', fontSize: 20, marginLeft: 8 }, title: { color: '#102A56', fontSize: 28, fontWeight: '800' }, subtitle: { color: '#667992', marginTop: 6, fontSize: 14 }, form: { marginTop: 29 }, label: { color: '#233B62', fontSize: 13, fontWeight: '700', marginBottom: 8 }, inputWrap: { height: 56, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#C9D6E8', borderRadius: 13, paddingHorizontal: 14, alignItems: 'center', flexDirection: 'row', gap: 11, marginBottom: 16 }, input: { flex: 1, color: '#102A56', fontSize: 15 }, note: { flexDirection: 'row', gap: 9, borderWidth: 1, borderColor: '#B8CDF0', backgroundColor: '#EEF5FF', padding: 13, borderRadius: 11, marginTop: 0 }, noteText: { color: '#355476', flex: 1, fontSize: 12, lineHeight: 18 }, error: { color: '#102A56', fontSize: 12, marginTop: 12 }, button: { height: 58, backgroundColor: '#102A56', borderRadius: 13, justifyContent: 'center', alignItems: 'center', marginTop: 21 }, buttonText: { color: '#fff', fontWeight: '900', fontSize: 14 }, bottom: { flexDirection: 'row', justifyContent: 'center', marginTop: 29 }, bottomText: { color: '#64748B' }, login: { color: '#173F83', fontWeight: '800' } });
