require('dotenv').config();
const crypto = require('crypto'); const nodemailer = require('nodemailer'); const bcrypt = require('bcryptjs'); const jwt = require('jsonwebtoken'); const rateLimit = require('express-rate-limit');
const express = require('express'); const cors = require('cors'); const mongoose = require('mongoose'); const http = require('http'); const { Server } = require('socket.io');
const app = express(); app.use(cors()); app.use(express.json());
const server = http.createServer(app); const io = new Server(server,{cors:{origin:'*',methods:['GET','POST']}});
const User = mongoose.model('User', new mongoose.Schema({ fullName: { type: String, required: true }, email: { type: String, required: true, unique: true, lowercase: true }, password: { type: String, required: true }, googleSubject: { type: String, unique: true, sparse: true }, role: { type: String, enum: ['mentee', 'mentor', 'admin'], default: 'mentee' }, avatarUrl: String, university: String, academicYear: String, fptK: String, studentId: String, major: String, specialization: String, track: String, currentTerm: String, specialty: String, mentorBio: String, mentorFee: Number, mentorCourses: [String], mentorAvailability: { accepting: { type: Boolean, default: true }, slots: [{ day: String, ranges: [String] }] }, notificationPreferences: { appointment: { type: Boolean, default: true }, community: { type: Boolean, default: true }, chat: { type: Boolean, default: true }, public: { type: Boolean, default: true }, document: { type: Boolean, default: true }, wallet: { type: Boolean, default: true } }, userXu: { type: Number, default: 20 }, availableXu: { type: Number, default: 0 }, escrowXu: { type: Number, default: 0 }, bankAccount: { bankName: String, accountNumber: String, accountHolder: String, bin: String }, bankAccounts: [{ id: String, bankName: String, accountNumber: String, accountHolder: String, bin: String }], subscription: { plan: { type: String, enum: ['FREE','PREMIUM'], default: 'FREE' }, status: { type: String, enum: ['ACTIVE','EXPIRED','CANCELLED'], default: 'ACTIVE' }, startedAt: Date, expiresAt: Date }, aiQuizUsage: { type: Number, default: 0 }, aiQuizUsagePeriod: String, hasCheckedInToday: { type: Boolean, default: false }, lastCheckInDate: String, sessionVersion: { type: Number, default: 0 }, isFirstLogin: { type: Boolean, default: true }, emailVerified: { type: Boolean, default: false }, emailVerificationRequired: { type: Boolean, default: false }, otpHash: String, otpPurpose: String, otpExpiresAt: Date, protected: { type: Boolean, default: false } }, { timestamps: true, versionKey: false }));
const Course = mongoose.model('Course', new mongoose.Schema({ code: String, name: String, term: String, fee: Number, link: String, major: String, specialization: String, track: { type: String, default: '' } }, { timestamps: true, versionKey: false }));
Course.schema.index({ code: 1, major: 1, specialization: 1, track: 1 }, { unique: true });
const Question = mongoose.model('Question', new mongoose.Schema({ menteeName: String, major: String, currentTerm: String, question: String, status: { type: String, default: 'new' } }, { timestamps: true, versionKey: false }));
const Booking = mongoose.model('Booking', new mongoose.Schema({ mentorEmail: String, mentorName: String, menteeName: String, menteeEmail: String, course: String, dateTime: String, note: String, fee: { type:Number, default:0 }, meetingLink: String, status: { type: String, default: 'Chờ mentor xác nhận' }, rating:{score:Number,comment:String,createdAt:Date} }, { timestamps: true, versionKey: false }));
const ChatMessage = mongoose.model('ChatMessage', new mongoose.Schema({ roomId: String, user: String, authorEmail: String, role: { type: String, enum: ['MENTEE','MENTOR','ADMIN'] }, text: String }, { timestamps: true, versionKey: false }));
const MentorDocument = mongoose.model('MentorDocument', new mongoose.Schema({ mentorEmail: String, mentorName: String, title: String, fileName: String, fileUri: String, cloudinaryPublicId:String, fileSize:Number, mimeType: String, term: String, course: String, specialty: String, category: String, description: String, fee: { type: Number, default: 15 }, previewPages: { type: Number, default: 2 }, status: { type: String, default: 'DRAFT' }, pages: { type: Number, default: 0 }, unlocks: { type: Number, default: 0 }, revenue: { type: Number, default: 0 } }, { timestamps: true, versionKey: false }));
const PremiumDocument = mongoose.model('PremiumDocument', new mongoose.Schema({ title:String, university:String, major:String, term:String, course:String, description:String, sourceType:{type:String,default:'PREMIUM_LIBRARY'} }, { timestamps:true, versionKey:false }));
const AppRelease = mongoose.model('AppRelease', new mongoose.Schema({ version:{type:String,required:true,trim:true}, platform:{type:String,enum:['android'],default:'android'}, apkUrl:{type:String,default:''}, fileSizeBytes:{type:Number,min:0,default:0}, sha256:{type:String,default:''}, releaseNotes:[String], minSupportedVersion:{type:String,default:''}, isForcedUpdate:{type:Boolean,default:false}, status:{type:String,enum:['DRAFT','PUBLISHED','ARCHIVED'],default:'DRAFT'}, publishedAt:Date }, { timestamps:true, versionKey:false }));
AppRelease.schema.index({version:1,platform:1},{unique:true});
const Notification = mongoose.model('Notification', new mongoose.Schema({ userEmail:String, title:String, body:String, type:String, read:{type:Boolean,default:false} }, { timestamps:true, versionKey:false }));
const Transaction = mongoose.model('Transaction', new mongoose.Schema({ userEmail:String, type:String, amount:Number, status:String, metadata:Object }, { timestamps:true, versionKey:false }));
const Payout = mongoose.model('Payout', new mongoose.Schema({ payoutCode:{type:String,unique:true,index:true}, mentorEmail:{type:String,index:true}, amountXu:Number, amountVnd:Number, bankAccount:{bankName:String,accountNumber:String,accountHolder:String,bin:String}, status:{type:String,enum:['PROCESSING','SUCCESS','FAILED','CANCELLED'],default:'PROCESSING'}, provider:{type:String,default:'MANUAL_REVIEW'}, providerReference:String, failureReason:String, completedAt:Date }, { timestamps:true, versionKey:false }));
const DocumentUnlock = mongoose.model('DocumentUnlock', new mongoose.Schema({ userEmail:{type:String,index:true}, documentId:{type:mongoose.Schema.Types.ObjectId,ref:'MentorDocument',index:true} }, { timestamps:true, versionKey:false }));
DocumentUnlock.schema.index({userEmail:1,documentId:1},{unique:true});
const PaymentOrder = mongoose.model('PaymentOrder', new mongoose.Schema({ orderCode:{type:Number,unique:true,index:true}, userEmail:{type:String,index:true}, coins:Number, amount:Number, status:{type:String,enum:['PENDING','PAID','CANCELLED','EXPIRED','FAILED'],default:'PENDING'}, paymentLinkId:String, checkoutUrl:String, reference:String, paidAt:Date }, { timestamps:true, versionKey:false }));
const SupportTicket = mongoose.model('SupportTicket', new mongoose.Schema({ reporterEmail:String, reporterRole:String, bookingId:String, reason:String, detail:String, evidenceNames:[String], status:{type:String,default:'OPEN'} }, { timestamps:true, versionKey:false }));
const AuditLog = mongoose.model('AuditLog', new mongoose.Schema({ actorEmail:String, action:String, targetType:String, targetId:String, metadata:Object }, { timestamps:true, versionKey:false }));
const PREMIUM_PLAN={code:'PREMIUM_MONTHLY',name:'PSIFU Premium',price:49000,durationDays:30,freeAiQuizLimit:Number(process.env.FREE_AI_QUIZ_LIMIT||3),premiumAiQuizLimit:Number(process.env.PREMIUM_AI_QUIZ_LIMIT||30)};
const systemUsers = [{ fullName: 'PSIFU Admin', email: 'admin@psifu.vn', password: 'admin123', role: 'admin', university: 'PSIFU', userXu: 0, hasCheckedInToday: false, isFirstLogin: false, protected: true, emailVerified:true }, { fullName: 'Mentor Minh Anh', email: 'mentor.se@psifu.vn', password: 'mentor123', role: 'mentor', specialty: 'Kỹ thuật phần mềm (SE)', university: 'FPT University', userXu: 0, hasCheckedInToday: false, isFirstLogin: false, protected: true, emailVerified:true }, { fullName: 'Mentor Gia Hân', email: 'mentor.data@psifu.vn', password: 'mentor123', role: 'mentor', specialty: 'Data Science & AI', university: 'FPT University', userXu: 0, hasCheckedInToday: false, isFirstLogin: false, protected: true, emailVerified:true }, { fullName: 'Mentor Quốc Bảo', email: 'mentor.business@psifu.vn', password: 'mentor123', role: 'mentor', specialty: 'Digital Marketing & Business', university: 'FPT University', userXu: 0, hasCheckedInToday: false, isFirstLogin: false, protected: true, emailVerified:true }];
const courseSeed = [
['SSL101c','Academic Skills for University Success','Kỳ 1',5],['CSI104','Introduction to Computer Science','Kỳ 1',6],['PRF192','Programming Fundamentals','Kỳ 1',8],['MAE101','Mathematics for Engineering','Kỳ 1',10],['CEA201','Computer Organization and Architecture','Kỳ 1',9],
['PRO192','Object-Oriented Programming','Kỳ 2',10],['MAD101','Discrete Mathematics','Kỳ 2',12],['OSG202','Operating Systems','Kỳ 2',9],['SSG104','Communication and In-Group Working Skills','Kỳ 2',5],['NWC204','Computer Networking','Kỳ 2',8],
['JPD113','Elementary Japanese 1-A1.1','Kỳ 3',7],['CSD201','Data Structures and Algorithms','Kỳ 3',15],['DBI202','Introduction to Databases','Kỳ 3',10],['LAB211','OOP with Java Lab','Kỳ 3',12],['WED201c','Web Design','Kỳ 3',7],
['MAS291','Statistics and Probability','Kỳ 4',11],['JPD123','Elementary Japanese 1-A1.2','Kỳ 4',7],['IOT102','Internet of Things','Kỳ 4',9],['PRJ301','Java Web Application Development','Kỳ 4',14],['SWE201c','Introduction to Software Engineering','Kỳ 4',8],
['SWP391','Application Development Project','Kỳ 5',15],['ITE302c','Ethics in IT','Kỳ 5',5],['SWR302','Software Requirement','Kỳ 5',10],['SWT301','Software Testing','Kỳ 5',11],['FER202','Front-End Web Development with React','Kỳ 5',13],
['ENW493c','Research Methods & Academic Writing Skills','Kỳ 6',8],['OJT202','On the Job Training','Kỳ 6',15],['SWD392','Software Architecture and Design','Kỳ 7',12],['PMG201c','Project Management','Kỳ 7',9],['EXE101','Experiential Entrepreneurship 1','Kỳ 7',10],['SDN302','Server-Side Development with NodeJS, Express, and MongoDB','Kỳ 7',14],['MMA301','Multiplatform Mobile App Development','Kỳ 7',14],
['WDP301','Web Development Project','Kỳ 8',15],['PRM393','Mobile Programming','Kỳ 8',13],['MLN111','Philosophy of Marxism – Leninism','Kỳ 8',6],['EXE201','Experiential Entrepreneurship 2','Kỳ 8',12],['WDU203c','UI/UX Design','Kỳ 8',8],['MLN122','Political Economics of Marxism – Leninism','Kỳ 8',6],
['HCM202','Ho Chi Minh Ideology','Kỳ 9',6],['MLN131','Scientific Socialism','Kỳ 9',6],['VNR202','History of Việt Nam Communist Party','Kỳ 9',6],['SE_GRA_ELE','Graduation Elective - Software Engineering','Kỳ 9',15]
].map(([code,name,term,fee]) => ({ code, name, term, fee, major: 'Computing', specialization: 'SE', track: 'NodeJS', link: `https://drive.google.com/${code.toLowerCase()}_secret` }));

const bbaMcCourseSeed = [
['GDQP','Military Education',0],['TMI101','Traditional Musical Instrument',0],['TRS601','English 6 (University Success)',0],['VOV114','Vovinam 1/3',0],['VOV124','Vovinam 2/3',0],['VOV134','Vovinam 3/3',0],
['DTG111','Visual Design Tools 1',1],['MED201','New Media Technology',1],['MGT103','Introduction to Management',1],['MKT101','Marketing Principles',1],['SSL101c','Academic Skills for University Success',1],
['ACC101','Principles of Accounting',2],['CMC201c','Creative Writing',2],['DTG121','Visual Design Tools 2',2],['MMP201','Media Psychology',2],['SSG104','Communication and In-Group Working Skills',2],
['CCO201','Corporate Communication',3],['MKT208c','Social Media Marketing',3],['PFD201','Photography for Designer',3],['RMC201','Research Methods in Communication',3],['SDP201','Sound Production',3],
['CHN111','Elementary Chinese 1',4],['IFT201c','Innovation and Future Thinking',4],['IPR102','Intellectual Property Rights',4],['VDP201','Video Production',4],['WMC201','Media Writing',4],
['CHN122','Elementary Chinese 2',5],['EVN201','Event Planning',5],['MCO201m','Transmedia Storytelling',5],['MKT304','Integrated Marketing Communications',5],['WDU202c','UI/UX Design',5],
['ENW492c','Academic Writing Skills',6],['OJB202','On-the-job Training',6],
['BRA301','Brand Management',7],['CCM301','Crisis Communications Management',7],['CSP201m','Content Strategy for Professionals',7],['EXE101','Experiential Entrepreneurship 1',7],['MEP301','Multimedia Production Project',7],
['EXE201','Experiential Entrepreneurship 2',8],['MLN111','Philosophy of Marxism - Leninism',8],['MLN122','Political Economics of Marxism - Leninism',8],['MSM201c','Meta Social Media Marketing Management',8],['PMG201c','Project Management',8],['PRE301','Public Relations Principles and Strategies',8],
['GRA497','Capstone Project Multimedia Communications',9],['HCM202','Ho Chi Minh Ideology',9],['MLN131','Scientific Socialism',9],['VNR202','History of Viet Nam Communist Party',9]
].map(([code, name, semester]) => ({ code, name, term: `Kỳ ${semester}`, fee: 0, major: 'Business Administration', specialization: 'MC', track: '', link: `https://drive.google.com/${String(code).toLowerCase()}_secret` }));
// Nguồn: chương trình BA(IB) do người dùng cung cấp.
const baIbCourseSeed = [
['ECO111','Microeconomics',1],['ENM302','Business English - Level: Intermediate',1],['MGT103','Introduction to Management',1],['MKT101','Marketing Principles',1],['SSL101c','Academic Skills for University Success',1],
['ACC101','Principles of Accounting',2],['ECO121','Macroeconomics',2],['ENM402','Business English Level 2',2],['OBE102c','Organizational Behavior',2],['SSG104','Communication and In-Group Working Skills',2],
['ECO201','International Economics',3],['FIN202','Principles of Corporate Finance',3],['HRM202c','Human Resource Management',3],['IBC201','Cross Cultural Management and Negotiation',3],['IBI101','Introduction to International Business',3],
['CHN113','Elementary Chinese 1',4],['IBF301','International Finance',4],['ITA203c','Information System Overview',4],['MAS202','Applied Statistics for Business',4],['SCM201','Supply Chain Management',4],
['CHN123','Elementary Chinese 2',5],['IBS301m','International Business Strategy',5],['IEI301','Import Export',5],['MKT205c','International Marketing',5],['SSB201','Advanced Business Communication',5],
['ENW492c','Academic Writing Skills',6],['OJB202','On-the-job Training',6],
['EXE101','Experiential Entrepreneurship 1',7],['IIP301','International Payment',7],['LAW102','Business Law and Ethics Fundamentals',7],['LAW201c','International Business Law',7],['SCM301m','Procurement and Global Sourcing',7],['EXE201','Experiential Entrepreneurship 2',7],
['LOG311','Customs Operations',8],['MLN111','Philosophy of Marxism - Leninism',8],['MLN122','Political Economics of Marxism and Leninism',8],['PMG201c','Project Management',8],['RMB301','Business Research Methods',8],
['BBA_GRA_ELE','BBA Graduation Thesis Elective',9],['HCM202','HCM Ideology',9],['MLN131','Scientific Socialism',9],['VNR202','History of CPV',9]
].map(([code, name, semester]) => ({ code, name, term: `Kỳ ${semester}`, fee: 0, major: 'Business Administration', specialization: 'BA(IB)', track: '', link: `https://drive.google.com/${String(code).toLowerCase()}_secret` }));
// Nguồn: chương trình IT → SE → .NET do người dùng cung cấp.
const seDotnetCourseSeed = [
['GDQP','Military Education',0],['OTP101','Orientation and General Training Program',0],['TMI101','Traditional Musical Instrument',0],['TRS601','English 6 (University Success)',0],['VOV114','Vovinam 1/3',0],['VOV124','Vovinam 2/3',0],['VOV134','Vovinam 3/3',0],
['CEA201','Computer Organization and Architecture',1],['CSI104','Introduction to Computer Science',1],['MAE101','Mathematics for Engineering',1],['PRF192','Programming Fundamentals',1],['SSL101c','Academic Skills for University Success',1],
['MAD101','Discrete Mathematics',2],['NWC204','Computer Networking',2],['OSG202','Operating Systems',2],['PRO192','Object-Oriented Programming',2],['SSG104','Communication and In-Group Working Skills',2],
['CSD201','Data Structures and Algorithms',3],['JPD113','Elementary Japanese 1-A1.1',3],['LAB211','OOP with Java Lab',3],['WED201c','Web Design',3],
['IOT102','Internet of Things',4],['JPD123','Elementary Japanese 1-A1.2',4],['MAS291','Statistics & Probability',4],['PRJ301','Java Web Application Development',4],['SWE201c','Introduction to Software Engineering',4],
['PRN212','Basic Cross-Platform Application Programming With .NET',5],['SWP391','Software Development Project',5],['SWR302','Software Requirement',5],['SWT301','Software Testing',5],['WDU203c','UI/UX Design',5],
['ENW493c','Research Methods & Academic Writing Skills',6],['OJT202','On-The-Job Training',6],
['EXE101','Experiential Entrepreneurship 1',7],['PMG201c','Project Management',7],['PRN222','Advanced Cross-Platform Application Programming With .NET',7],['PRU213','Game Programming with C#',7],['SWD392','Software Architecture and Design',7],
['EXE201','Experiential Entrepreneurship 2',8],['ITE302c','Ethics in IT',8],['MLN111','Philosophy of Marxism - Leninism',8],['MLN122','Political Economics of Marxism - Leninism',8],['PRM393','Mobile Programming',8],['PRN232','Xây dựng ứng dụng back-end với .NET',8],
['HCM202','HCM Ideology',9],['MLN131','Scientific Socialism',9],['SE_GRA_ELE','Graduation Elective - Software Engineering',9],['VNR202','History of CPV',9]
].map(([code, name, semester]) => ({ code, name, term: `Kỳ ${semester}`, fee: 0, major: 'Computing', specialization: 'SE', track: '.NET', link: `https://drive.google.com/${String(code).toLowerCase()}_secret` }));
// Nguồn: chương trình IT → SE → JS do người dùng cung cấp.
const seJsCourseSeed = [
['GDQP','Military Education',0],['OTP101','Orientation and General Training Program',0],['TMI101','Traditional Musical Instrument',0],['TRS601','English 6 (University Success)',0],['VOV114','Vovinam 1/3',0],['VOV124','Vovinam 2/3',0],['VOV134','Vovinam 3/3',0],
['CEA201','Computer Organization and Architecture',1],['CSI104','Introduction to Computer Science',1],['MAE101','Mathematics for Engineering',1],['PRF192','Programming Fundamentals',1],['SSL101c','Academic Skills for University Success',1],
['MAD101','Discrete Mathematics',2],['NWC204','Computer Networking',2],['OSG202','Operating Systems',2],['PRO192','Object-Oriented Programming',2],['SSG104','Communication and In-Group Working Skills',2],
['CSD201','Data Structures and Algorithms',3],['DBI202','Introduction to Databases',3],['JPD113','Elementary Japanese 1 - A1.1',3],['LAB211','OOP with Java Lab',3],['WED201c','Web Design',3],
['IOT102','Internet of Things',4],['JPD123','Elementary Japanese 1-A1.2',4],['MAS291','Statistics & Probability',4],['PRJ301','Java Web Application Development',4],['SWE201c','Introduction to Software Engineering',4],
['JPD133','Elementary Japanese 1-A1/A2',5],['SWP391','Software Development Project',5],['SWR302','Software Requirement',5],['SWT301','Software Testing',5],['WDU203c','UI/UX Design',5],
['ENW493c','Research Methods & Academic Writing Skills',6],['OJT202','On-The-Job Training',6],
['JPD316','Intermediate Japanese 1-B1/B2',7],['PMG201c','Project Management',7],['SWD392','Software Architecture and Design',7],['SYB302c','Entrepreneurship',7],
['ITE302c','Ethics in IT',8],['JFE301','Japanese IT Fundamentals',8],['JIT401','Information Technology Japanese',8],['MLN111','Philosophy of Marxism - Leninism',8],['MLN122','Political Economics of Marxism - Leninism',8],['PRM393','Mobile Programming',8],
['HCM202','HCM Ideology',9],['MLN131','Scientific Socialism',9],['SE_GRA_ELE','Graduation Elective - Software Engineering',9],['VNR202','History of CPV',9]
].map(([code, name, semester]) => ({ code, name, term: `Kỳ ${semester}`, fee: 0, major: 'Computing', specialization: 'SE', track: 'JS', link: `https://drive.google.com/${String(code).toLowerCase()}_secret` }));

const aiCourseSeed = [
['GDQP','Military Education (Giáo dục quốc phòng)',0],['OTP101','Orientation & General Training Program',0],['TMI101','Traditional Musical Instrument (Nhạc cụ)',0],['TRS601','English 6 (University Success)',0],['VOV114','Vovinam 1/3',0],['VOV124','Vovinam 2/3',0],['VOV134','Vovinam 3/3',0],
['CSI106','Introduction to Computer Science',1],['MAD101','Discrete Mathematics (Toán rời rạc)',1],['MAE101','Mathematics for Engineering',1],['PFP191','Programming Fundamentals with Python',1],['SSL101c','Academic Skills for University Success',1],
['AIG202c','Artificial Intelligence (Nhập môn AI)',2],['CEA201','Computer Organization & Architecture',2],['CSD203','Data Structures and Algorithm with Python',2],['DBI202','Introduction to Databases',2],['SSG104','Communication & In-Group Working Skills',2],
['ADY201m','AI, DS with Python & SQL',3],['ITE303c','Ethics in IT (Đạo đức CNTT)',3],['JPD113','Elementary Japanese 1 - A1.1',3],['MAI391','Mathematics for Machine Learning',3],['MAS291','Statistics & Probability',3],
['AIL303m','Machine Learning (Học máy)',4],['CPV301','Computer Vision (Thị giác máy tính)',4],['DAP391m','AI-DS Project (Đồ án AI & Khoa học DL)',4],['JPD123','Elementary Japanese 1 - A1.2',4],['SWE201c','Introduction to Software Engineering',4],
['AIH301m','AI in Healthcare',5],['ASR301c','AI for Scientific Research',5],['DPL302m','Deep Learning (Học sâu)',5],['DWP301c','Web Development with Python',5],
['NLP301c','Natural Language Processing (Xử lý NN tự nhiên)',6],['OJT202','On-The-Job Training (Kỳ thực tập doanh nghiệp)',6],
['AIM301m','AI for Medicine',7],['DAT301m','AI Development with TensorFlow',7],['ENW493c','Research Methods & Academic Writing',7],['EXE101','Experiential Entrepreneurship 1',7],['PMG201c','Project Management (Quản trị dự án)',7],
['AID301c','AI in Production (Triển khai hệ thống AI)',8],['AIE301m','AI for Trading',8],['EXE201','Experiential Entrepreneurship 2',8],['MLN111','Philosophy of Marxism - Leninism',8],['MLN122','Political Economics of Marxism - Leninism',8],['REL301m','Reinforcement Learning (Học tăng cường)',8],
['AI17_GRA','AI17_GRA_ELE: Graduation Elective / Thesis',9],['HCM202','HCM Ideology (Tư tưởng Hồ Chí Minh)',9],['MLN131','Scientific Socialism (Chủ nghĩa XHKH)',9],['VNR202','History of CPV (Lịch sử Đảng CSVN)',9]
].map(([code, name, semester]) => ({ code, name, term: `Kỳ ${semester}`, fee: 0, major: 'Computing', specialization: 'AI', track: '', link: `https://drive.google.com/${String(code).toLowerCase()}_secret` }));
const allCourseSeeds = [...courseSeed, ...bbaMcCourseSeed, ...baIbCourseSeed, ...seDotnetCourseSeed, ...seJsCourseSeed, ...aiCourseSeed];
const toClient = doc => { const value = doc.toObject ? doc.toObject() : doc; const { password, googleSubject, otpHash, otpPurpose, otpExpiresAt, ...safe } = value; return { ...safe, id: String(value._id), createdAt: value.createdAt || new Date().toISOString() }; };
const JWT_SECRET = process.env.JWT_SECRET;
const PASSWORD_HASH_ROUNDS = 10;
const authLimiter = rateLimit({windowMs:15*60*1000,limit:8,standardHeaders:'draft-8',legacyHeaders:false,message:{success:false,msg:'Bạn đã thử quá nhiều lần. Vui lòng thử lại sau 15 phút.'}});
const otpLimiter = rateLimit({windowMs:15*60*1000,limit:5,standardHeaders:'draft-8',legacyHeaders:false,keyGenerator:req=>`${rateLimit.ipKeyGenerator(req.ip)}:${cleanEmail(req.body?.email)}`,message:{success:false,msg:'Bạn đã yêu cầu OTP quá nhiều lần. Vui lòng thử lại sau 15 phút.'}});
const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const cleanEmail=value=>String(value||'').trim().toLowerCase();
const validPassword=value=>typeof value==='string'&&value.length>=8&&value.length<=72;
const makeToken=user=>{if(!JWT_SECRET)throw new Error('JWT_SECRET chưa được cấu hình trên máy chủ.');return jwt.sign({sub:String(user._id),email:user.email,role:user.role,sv:user.sessionVersion||0},JWT_SECRET,{expiresIn:'7d',issuer:'psifu-api'});};
const requireAuth=async(req,res,next)=>{try{if(!JWT_SECRET)return res.status(503).json({success:false,msg:'Máy chủ chưa cấu hình JWT_SECRET.'});const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)return res.status(401).json({success:false,msg:'Bạn cần đăng nhập để tiếp tục.'});const payload=jwt.verify(token,JWT_SECRET,{issuer:'psifu-api'});const user=await User.findById(payload.sub).select('email role sessionVersion');if(!user||user.email!==payload.email||(user.sessionVersion||0)!==(payload.sv||0))return res.status(401).json({success:false,msg:'Phiên đăng nhập không còn hiệu lực. Vui lòng đăng nhập lại.'});req.auth={...payload,role:user.role,email:user.email};next();}catch{return res.status(401).json({success:false,msg:'Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.'});}};
const requireRole=(...roles)=>(req,res,next)=>roles.includes(req.auth?.role)?next():res.status(403).json({success:false,msg:'Bạn không có quyền thực hiện thao tác này.'});
const pageResult = async (Model, filter, req, res) => { const page=Math.max(1,Number(req.query.page)||1),limit=Math.min(100,Math.max(1,Number(req.query.limit)||20)); const [items,total]=await Promise.all([Model.find(filter).sort({createdAt:-1}).skip((page-1)*limit).limit(limit),Model.countDocuments(filter)]); res.json({items:items.map(toClient),pagination:{page,limit,total,totalPages:Math.ceil(total/limit)}}); };
const requireSelfOrAdmin=(field='email')=>(req,res,next)=>cleanEmail(req.params[field]||req.body[field])===req.auth?.email||req.auth?.role==='admin'?next():res.status(403).json({success:false,msg:'Bạn chỉ được thao tác trên tài khoản của chính mình.'});
const requireChatParticipant=async(req,res,next)=>{const roomId=String(req.params.roomId||'');if(!roomId.startsWith('mentor-chat-'))return next();const matched=roomId.match(/^mentor-chat-([^-]+)-/);if(!matched)return res.status(403).json({success:false,msg:'Phòng trò chuyện không hợp lệ.'});let mentorEmail;try{mentorEmail=cleanEmail(decodeURIComponent(matched[1]));}catch{return res.status(403).json({success:false,msg:'Phòng trò chuyện không hợp lệ.'});}if(req.auth.role==='admin'||req.auth.email===mentorEmail)return next();if(await Booking.exists({mentorEmail,menteeEmail:req.auth.email,status:{$ne:'Đã hủy'}}))return next();return res.status(403).json({success:false,msg:'Bạn không có quyền truy cập cuộc trò chuyện này.'});};
io.use(async(socket,next)=>{try{const token=String(socket.handshake.auth?.token||'');const payload=jwt.verify(token,JWT_SECRET,{issuer:'psifu-api'});const user=await User.findById(payload.sub).select('email role sessionVersion');if(!user||user.email!==payload.email||(user.sessionVersion||0)!==(payload.sv||0))return next(new Error('unauthorized'));socket.user={email:user.email,role:user.role};next();}catch{next(new Error('unauthorized'));}});
io.on('connection',socket=>{socket.on('chat:join',roomId=>{const room=String(roomId||'');if(room==='homepage-live'||room.includes('::'))socket.join(room);});});
const mailer = process.env.SMTP_HOST ? nodemailer.createTransport({ host: process.env.SMTP_HOST, port: Number(process.env.SMTP_PORT || 587), secure: process.env.SMTP_SECURE === 'true', auth: process.env.SMTP_USER ? { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS } : undefined, connectionTimeout: 15000, greetingTimeout: 15000, socketTimeout: 20000 }) : null;
const hashOtp = code => crypto.createHash('sha256').update(code).digest('hex');
const sendEmail = async ({to,subject,text,html}) => { if(process.env.RESEND_API_KEY){ const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.RESEND_FROM||'PSIFU <onboarding@resend.dev>',to:[to],subject,text,html})}); const result=await response.json().catch(()=>({})); if(!response.ok)throw new Error(result.message||result.name||'Resend không thể gửi email.'); return result; } if(!mailer)throw new Error('Chưa cấu hình RESEND_API_KEY hoặc SMTP.'); return mailer.sendMail({from:process.env.SMTP_FROM||process.env.SMTP_USER,to,subject,text,html}); };
const payosConfigured = () => Boolean(process.env.PAYOS_CLIENT_ID && process.env.PAYOS_API_KEY && process.env.PAYOS_CHECKSUM_KEY && process.env.PAYOS_RETURN_URL && process.env.PAYOS_CANCEL_URL);
const cloudinaryConfigured = () => Boolean(process.env.CLOUDINARY_CLOUD_NAME && process.env.CLOUDINARY_API_KEY && process.env.CLOUDINARY_API_SECRET);
const cloudinarySignature = params => crypto.createHash('sha1').update(`${Object.keys(params).sort().map(key=>`${key}=${params[key]}`).join('&')}${process.env.CLOUDINARY_API_SECRET}`).digest('hex');
const payosSignature = data => crypto.createHmac('sha256', process.env.PAYOS_CHECKSUM_KEY || '').update(Object.keys(data || {}).sort().filter(key => data[key] !== undefined && data[key] !== null).map(key => `${key}=${data[key]}`).join('&')).digest('hex');
const payosRequest = async (path, options = {}) => { const response = await fetch(`https://api-merchant.payos.vn${path}`, { ...options, headers:{ 'Content-Type':'application/json', 'x-client-id':process.env.PAYOS_CLIENT_ID, 'x-api-key':process.env.PAYOS_API_KEY, ...(options.headers||{}) } }); const payload = await response.json().catch(() => ({})); if (!response.ok || payload.code && payload.code !== '00') throw new Error(payload.desc || 'PayOS không thể xử lý yêu cầu thanh toán.'); return payload.data; };
const nextPayosOrderCode = async () => { for(let attempts=0;attempts<8;attempts+=1){ const code=Number(`${Date.now().toString().slice(-8)}${crypto.randomInt(10,100)}`); if(!await PaymentOrder.exists({orderCode:code})) return code; } throw new Error('Không thể tạo mã đơn thanh toán.'); };
const issueOtp = async (user, purpose) => { const code = crypto.randomInt(100000, 1000000).toString(); const title=purpose === 'verify-email' ? 'Xác minh email' : 'Đặt lại mật khẩu'; user.otpHash = hashOtp(code); user.otpPurpose = purpose; user.otpExpiresAt = new Date(Date.now() + 10 * 60 * 1000); await user.save(); await sendEmail({to:user.email,subject:`PSIFU – ${title}`,text:`Mã OTP PSIFU của bạn là: ${code}. Mã có hiệu lực trong 10 phút. Không chia sẻ mã này cho bất kỳ ai.`,html:`<div style="font-family:Arial,sans-serif;background:#f4f7ff;padding:32px;color:#152a4d"><div style="max-width:520px;margin:auto;background:#fff;border-radius:16px;padding:30px"><div style="font-size:22px;font-weight:800;color:#155eef">PSIFU</div><h2>${title}</h2><p>Xin chào ${user.fullName || 'bạn'},</p><p>Dùng mã OTP dưới đây để tiếp tục. Mã có hiệu lực trong <b>10 phút</b>.</p><div style="font-size:32px;letter-spacing:8px;font-weight:800;color:#155eef;background:#eef3ff;padding:18px;border-radius:12px;text-align:center">${code}</div><p style="font-size:13px;color:#64748b;margin-top:24px">Không chia sẻ mã này cho bất kỳ ai, kể cả người tự xưng là PSIFU.</p></div></div>`}); };
const validateOtp = (user, purpose, code) => user && user.otpPurpose === purpose && user.otpExpiresAt > new Date() && user.otpHash === hashOtp(String(code || ''));
// Sensitive financial/profile routes require a valid identity before their handlers run.
app.use('/api/mentors/:email/bank-account',requireAuth,requireSelfOrAdmin());
app.use('/api/payouts/:email',requireAuth,requireSelfOrAdmin());
app.use('/api/payouts',requireAuth,(req,res,next)=>req.method==='POST'?requireSelfOrAdmin()(req,res,next):next());
app.use('/api/users/:email/settings',requireAuth,requireSelfOrAdmin());
app.use('/api/document-unlocks/:email',requireAuth,requireSelfOrAdmin());
app.use('/api/support-tickets/:email',requireAuth,requireSelfOrAdmin());
app.get('/api/health', (_req, res) => res.json({ status: 'ok' }));
app.get('/payment/return', (_req, res) => res.type('html').send('<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>PSIFU Payment</title></head><body style="font-family:system-ui;text-align:center;padding:56px 20px;background:#f8faff;color:#102a56"><h1>Đang xác nhận thanh toán</h1><p>PayOS đã chuyển bạn về PSIFU. Hãy quay lại ứng dụng; Xu chỉ được cộng sau khi webhook được xác minh.</p></body></html>'));
app.get('/payment/cancel', (_req, res) => res.type('html').send('<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>PSIFU Payment</title></head><body style="font-family:system-ui;text-align:center;padding:56px 20px;background:#f8faff;color:#102a56"><h1>Thanh toán chưa hoàn tất</h1><p>Bạn có thể quay lại ứng dụng PSIFU để thử lại khi sẵn sàng.</p></body></html>'));
app.get('/api/courses', async (req, res) => { const filter = { major: req.query.major || 'Computing', specialization: req.query.specialization || 'SE' }; if (req.query.track !== undefined) filter.track = req.query.track; if (req.query.term) filter.term = req.query.term; res.json((await Course.find(filter).sort({ term: 1, code: 1 })).map(toClient)); });
const releaseClient=release=>{const item=toClient(release);return {id:item.id,version:item.version,platform:item.platform,apkUrl:item.apkUrl,fileSizeBytes:item.fileSizeBytes,sha256:item.sha256,releaseNotes:item.releaseNotes||[],minSupportedVersion:item.minSupportedVersion,isForcedUpdate:item.isForcedUpdate,status:item.status,publishedAt:item.publishedAt,createdAt:item.createdAt,updatedAt:item.updatedAt};};
const releaseInput=body=>{const version=String(body.version||'').trim();const apkUrl=String(body.apkUrl||'').trim();const status=String(body.status||'DRAFT');if(!/^v?\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/.test(version))throw new Error('Version phải theo SemVer, ví dụ 1.0.0 hoặc v1.1.0.');if(apkUrl&&!/^https?:\/\//i.test(apkUrl))throw new Error('URL APK phải bắt đầu bằng http:// hoặc https://.');if(!['DRAFT','PUBLISHED','ARCHIVED'].includes(status))throw new Error('Trạng thái release không hợp lệ.');const notes=Array.isArray(body.releaseNotes)?body.releaseNotes:String(body.releaseNotes||'').split('\n');return {version,platform:'android',apkUrl,fileSizeBytes:Math.max(0,Number(body.fileSizeBytes)||0),sha256:String(body.sha256||'').trim().toLowerCase(),releaseNotes:notes.map(note=>String(note).trim()).filter(Boolean).slice(0,30),minSupportedVersion:String(body.minSupportedVersion||'').trim(),isForcedUpdate:Boolean(body.isForcedUpdate),status};};
app.get('/api/releases/latest',async(req,res)=>{const platform=String(req.query.platform||'android');const release=await AppRelease.findOne({platform,status:'PUBLISHED'}).sort({publishedAt:-1,createdAt:-1});res.json({success:true,release:release?releaseClient(release):null});});
app.get('/api/releases',async(req,res)=>{const platform=String(req.query.platform||'android');const releases=await AppRelease.find({platform,status:'PUBLISHED'}).sort({publishedAt:-1,createdAt:-1});res.json({success:true,items:releases.map(releaseClient)});});
app.get('/api/releases/:version',async(req,res)=>{const release=await AppRelease.findOne({version:String(req.params.version),platform:'android',status:'PUBLISHED'});if(!release)return res.status(404).json({success:false,msg:'Không tìm thấy phiên bản đã xuất bản.'});res.json({success:true,release:releaseClient(release)});});
app.get('/api/users',requireAuth,requireRole('admin'), async (_req, res) => res.json((await User.find().sort({ createdAt: -1 })).map(toClient)));
// Aggregated server-side data for the admin portal. Keep reporting queries here so
// browsers never need to download raw collections merely to calculate charts.
app.get('/api/admin/dashboard',requireAuth,requireRole('admin'),async(req,res)=>{
  const now=new Date();
  const defaultFrom=new Date(now); defaultFrom.setDate(defaultFrom.getDate()-29); defaultFrom.setHours(0,0,0,0);
  const parseDate=(value,fallback)=>{const date=value?new Date(String(value)):fallback;return Number.isNaN(date.getTime())?null:date;};
  const from=parseDate(req.query.from,defaultFrom),to=parseDate(req.query.to,now);
  if(!from||!to||from>to)return res.status(400).json({success:false,msg:'Khoảng thời gian không hợp lệ.'});
  from.setHours(0,0,0,0); to.setHours(23,59,59,999);
  const range={createdAt:{$gte:from,$lte:to}};
  const byDay=(Model,match={},valueField)=>Model.aggregate([
    {$match:{...match,...range}},
    {$group:{_id:{$dateToString:{format:'%Y-%m-%d',date:'$createdAt',timezone:'Asia/Ho_Chi_Minh'}},value:valueField?{$sum:`$${valueField}`} : {$sum:1}}},
    {$project:{_id:0,date:'$_id',value:1}},{$sort:{date:1}}
  ]);
  const [users,mentors,mentees,bookings,documents,ticketsOpen,payoutsPending,paymentStats,newUsers,bookingsByDay,topupsByDay,ticketsByDay]=await Promise.all([
    User.countDocuments(),User.countDocuments({role:'mentor'}),User.countDocuments({role:'mentee'}),Booking.countDocuments(range),MentorDocument.countDocuments({status:'PUBLISHED'}),SupportTicket.countDocuments({status:{$in:['OPEN','IN_PROGRESS']}}),Payout.countDocuments({status:'PROCESSING'}),
    PaymentOrder.aggregate([{$match:{status:'PAID',...range}},{$group:{_id:null,count:{$sum:1},amount:{$sum:'$amount'}}}]),
    byDay(User),byDay(Booking),byDay(PaymentOrder,{status:'PAID'},'amount'),byDay(SupportTicket)
  ]);
  res.json({success:true,range:{from:from.toISOString(),to:to.toISOString()},totals:{users,mentors,mentees,bookings,documents,ticketsOpen,payoutsPending,paidOrders:paymentStats[0]?.count||0,revenueVnd:paymentStats[0]?.amount||0},charts:{newUsers,newBookings:bookingsByDay,topupsVnd:topupsByDay,newTickets:ticketsByDay}});
});
// Admin-only operational APIs. These return a single paginated response shape for the web portal.
app.get('/api/admin/payment-orders',requireAuth,requireRole('admin'),async(req,res)=>{const filter={};if(req.query.status)filter.status=String(req.query.status);if(req.query.from||req.query.to)filter.createdAt={...(req.query.from?{$gte:new Date(String(req.query.from))}:{}),...(req.query.to?{$lte:new Date(String(req.query.to))}:{})};await pageResult(PaymentOrder,filter,req,res);});
app.get('/api/admin/transactions',requireAuth,requireRole('admin'),async(req,res)=>{const filter={};if(req.query.type)filter.type=String(req.query.type);if(req.query.status)filter.status=String(req.query.status);if(req.query.from||req.query.to)filter.createdAt={...(req.query.from?{$gte:new Date(String(req.query.from))}:{}),...(req.query.to?{$lte:new Date(String(req.query.to))}:{})};await pageResult(Transaction,filter,req,res);});
app.get('/api/admin/payouts',requireAuth,requireRole('admin'),async(req,res)=>{const filter={};if(req.query.status)filter.status=String(req.query.status);await pageResult(Payout,filter,req,res);});
app.patch('/api/admin/payouts/:payoutCode',requireAuth,requireRole('admin'),async(req,res)=>{const status=String(req.body.status||'');const failureReason=String(req.body.failureReason||'').trim();const providerReference=String(req.body.providerReference||'').trim();if(!['SUCCESS','FAILED','CANCELLED'].includes(status))return res.status(400).json({success:false,msg:'Trạng thái payout không hợp lệ.'});if(status==='FAILED'&&!failureReason)return res.status(400).json({success:false,msg:'Cần nêu lý do payout thất bại.'});const payout=await Payout.findOneAndUpdate({payoutCode:req.params.payoutCode,status:'PROCESSING'},{$set:{status,failureReason:status==='FAILED'?failureReason:undefined,providerReference:status==='SUCCESS'?providerReference:undefined,completedAt:new Date()}},{new:true});if(!payout){const exists=await Payout.exists({payoutCode:req.params.payoutCode});return res.status(exists?409:404).json({success:false,msg:exists?'Payout đã được xử lý, không thể cập nhật lại.':'Không tìm thấy payout.'});}if(status==='FAILED'||status==='CANCELLED'){await User.findOneAndUpdate({email:payout.mentorEmail,role:'mentor'},{$inc:{availableXu:payout.amountXu}});await Transaction.updateOne({userEmail:payout.mentorEmail,type:'MENTOR_PAYOUT','metadata.payoutCode':payout.payoutCode},{$set:{status:'REFUNDED',metadata:{payoutCode:payout.payoutCode,reason:failureReason||'Yêu cầu rút đã bị hủy'}}});await Notification.create({userEmail:payout.mentorEmail,title:'Yêu cầu rút Xu không được duyệt',body:`Lệnh ${payout.payoutCode} đã ${status==='CANCELLED'?'bị hủy':'không thành công'}. ${payout.amountXu} Xu đã được hoàn về ví khả dụng.`,type:'WALLET'});}else{await Transaction.updateOne({userEmail:payout.mentorEmail,type:'MENTOR_PAYOUT','metadata.payoutCode':payout.payoutCode},{$set:{status:'SUCCESS'}});await Notification.create({userEmail:payout.mentorEmail,title:'Yêu cầu rút Xu đã được duyệt',body:`Lệnh ${payout.payoutCode} đã được PSIFU xác nhận chuyển khoản.`,type:'WALLET'});}await AuditLog.create({actorEmail:req.auth.email,action:'PAYOUT_STATUS_UPDATED',targetType:'Payout',targetId:payout.payoutCode,metadata:{status,failureReason,providerReference}});res.json({success:true,payout:toClient(payout)});});
app.get('/api/admin/support-tickets',requireAuth,requireRole('admin'),async(req,res)=>{const filter={};if(req.query.status)filter.status=String(req.query.status);await pageResult(SupportTicket,filter,req,res);});
app.patch('/api/admin/support-tickets/:id',requireAuth,requireRole('admin'),async(req,res)=>{const status=String(req.body.status||'');if(!['OPEN','IN_PROGRESS','RESOLVED','CLOSED'].includes(status))return res.status(400).json({success:false,msg:'Trạng thái ticket không hợp lệ.'});const ticket=await SupportTicket.findByIdAndUpdate(req.params.id,{$set:{status}},{new:true});if(!ticket)return res.status(404).json({success:false,msg:'Không tìm thấy ticket.'});await AuditLog.create({actorEmail:req.auth.email,action:'SUPPORT_TICKET_STATUS_UPDATED',targetType:'SupportTicket',targetId:String(ticket._id),metadata:{status}});res.json({success:true,ticket:toClient(ticket)});});
app.get('/api/admin/releases',requireAuth,requireRole('admin'),async(req,res)=>{const releases=await AppRelease.find({}).sort({createdAt:-1});res.json({success:true,items:releases.map(releaseClient)});});
app.post('/api/admin/releases',requireAuth,requireRole('admin'),async(req,res)=>{try{const input=releaseInput(req.body);if(input.status==='PUBLISHED'&&!input.apkUrl)return res.status(400).json({success:false,msg:'Cần URL APK trước khi xuất bản release.'});const release=await AppRelease.create({...input,publishedAt:input.status==='PUBLISHED'?new Date():undefined});await AuditLog.create({actorEmail:req.auth.email,action:'APP_RELEASE_CREATED',targetType:'AppRelease',targetId:String(release._id),metadata:{version:release.version,status:release.status}});res.status(201).json({success:true,release:releaseClient(release)});}catch(error){res.status(error?.code===11000?409:400).json({success:false,msg:error?.code===11000?'Version này đã tồn tại.':error.message||'Không thể tạo release.'});}});
app.patch('/api/admin/releases/:id',requireAuth,requireRole('admin'),async(req,res)=>{try{const input=releaseInput(req.body);if(input.status==='PUBLISHED'&&!input.apkUrl)return res.status(400).json({success:false,msg:'Cần URL APK trước khi xuất bản release.'});const existing=await AppRelease.findById(req.params.id);if(!existing)return res.status(404).json({success:false,msg:'Không tìm thấy release.'});const publishedAt=input.status==='PUBLISHED'&&existing.status!=='PUBLISHED'?new Date():existing.publishedAt;const release=await AppRelease.findByIdAndUpdate(existing._id,{$set:{...input,publishedAt}},{new:true,runValidators:true});await AuditLog.create({actorEmail:req.auth.email,action:'APP_RELEASE_UPDATED',targetType:'AppRelease',targetId:String(release._id),metadata:{version:release.version,status:release.status}});res.json({success:true,release:releaseClient(release)});}catch(error){res.status(error?.code===11000?409:400).json({success:false,msg:error?.code===11000?'Version này đã tồn tại.':error.message||'Không thể cập nhật release.'});}});
app.get('/api/mentors', async (_req,res) => { const mentors=await User.find({role:'mentor'}).select('fullName email avatarUrl specialty mentorBio mentorFee mentorCourses mentorAvailability');res.json(mentors.map(toClient)); });
app.post('/api/users',authLimiter, async (req,res)=>{const email=cleanEmail(req.body.email),fullName=String(req.body.fullName||'').trim(),password=req.body.password,role=req.body.role||'mentee';if(!emailPattern.test(email))return res.status(400).json({success:false,msg:'Email không hợp lệ.'});if(fullName.length<2||fullName.length>80)return res.status(400).json({success:false,msg:'Họ tên phải từ 2 đến 80 ký tự.'});if(!validPassword(password))return res.status(400).json({success:false,msg:'Mật khẩu phải dài từ 8 đến 72 ký tự.'});if(!['mentee','mentor'].includes(role))return res.status(400).json({success:false,msg:'Vai trò đăng ký không hợp lệ.'});if(await User.exists({email}))return res.status(409).json({success:false,msg:'Email/Tài khoản này đã tồn tại!'});const user=await User.create({email,fullName,password:await bcrypt.hash(password,PASSWORD_HASH_ROUNDS),role,emailVerified:false,emailVerificationRequired:true,userXu:20,hasCheckedInToday:false,isFirstLogin:true});res.status(201).json({success:true,msg:'Đăng ký thành công! Hãy xác minh email.',user:toClient(user)});});
app.post('/api/auth/email-verification/send', otpLimiter, async (req, res) => { const user = await User.findOne({ email: req.body.email?.trim().toLowerCase() }); if (!user) return res.status(404).json({ success: false, msg: 'Không tìm thấy tài khoản với email này.' }); try { await issueOtp(user, 'verify-email'); res.json({ success: true, msg: 'Mã OTP đã được gửi tới email của bạn.' }); } catch (error) { res.status(503).json({ success: false, msg: error.message }); } });
app.post('/api/auth/email-verification/verify', async (req, res) => { const user = await User.findOne({ email: req.body.email?.trim().toLowerCase() }); if (!validateOtp(user, 'verify-email', req.body.code)) return res.status(400).json({ success: false, msg: 'Mã OTP không đúng hoặc đã hết hạn.' }); user.emailVerified = true; user.emailVerificationRequired = false; user.otpHash = undefined; user.otpPurpose = undefined; user.otpExpiresAt = undefined; await user.save(); res.json({ success: true, msg: 'Email đã được xác minh.' }); });
app.post('/api/auth/password-reset/send', otpLimiter, async (req, res) => { const user = await User.findOne({ email: req.body.email?.trim().toLowerCase() }); if (!user) return res.json({ success: true, msg: 'Nếu email thuộc tài khoản PSIFU, mã đặt lại mật khẩu sẽ được gửi.' }); try { await issueOtp(user, 'password-reset'); res.json({ success: true, msg: 'Nếu email thuộc tài khoản PSIFU, mã đặt lại mật khẩu sẽ được gửi.' }); } catch (error) { console.error('Password-reset OTP delivery failed:', error.message); res.status(503).json({ success: false, msg: 'Chưa thể gửi email lúc này. Vui lòng thử lại sau.' }); } });
app.post('/api/auth/password-reset/verify', async (req, res) => { const user = await User.findOne({ email: req.body.email?.trim().toLowerCase() }); if (!validateOtp(user, 'password-reset', req.body.code)) return res.status(400).json({ success: false, msg: 'Mã OTP không đúng hoặc đã hết hạn.' }); res.json({ success: true }); });
app.post('/api/auth/password-reset/complete', authLimiter, async (req,res)=>{const user=await User.findOne({email:cleanEmail(req.body.email)});if(!validPassword(req.body.password))return res.status(400).json({success:false,msg:'Mật khẩu phải dài từ 8 đến 72 ký tự.'});if(!validateOtp(user,'password-reset',req.body.code))return res.status(400).json({success:false,msg:'Mã OTP không đúng hoặc đã hết hạn.'});user.password=await bcrypt.hash(req.body.password,PASSWORD_HASH_ROUNDS);user.sessionVersion=(user.sessionVersion||0)+1;user.otpHash=undefined;user.otpPurpose=undefined;user.otpExpiresAt=undefined;await user.save();res.json({success:true,msg:'Đặt lại mật khẩu thành công. Các phiên đăng nhập cũ đã bị đăng xuất.'});});
app.post('/api/auth/logout-all',requireAuth,async(req,res)=>{await User.findByIdAndUpdate(req.auth.sub,{$inc:{sessionVersion:1}});res.json({success:true,msg:'Đã đăng xuất toàn bộ thiết bị.'});});
app.get('/api/auth/me',requireAuth,async(req,res)=>{const user=await User.findById(req.auth.sub);if(!user)return res.status(401).json({success:false});res.json({success:true,user:toClient(user)});});
app.post('/api/wallet/daily-check-in',requireAuth,async(req,res)=>{const user=await User.findById(req.auth.sub);const today=new Date().toISOString().slice(0,10);if(user.lastCheckInDate===today)return res.status(409).json({success:false,msg:'Bạn đã điểm danh hôm nay.'});user.lastCheckInDate=today;user.hasCheckedInToday=true;user.userXu=(user.userXu||0)+1;await user.save();await Transaction.create({userEmail:user.email,type:'DAILY_CHECK_IN',amount:1,status:'SUCCESS'});res.json({success:true,userXu:user.userXu});});
app.post('/api/auth/login', authLimiter, async (req, res) => {
  const email = req.body.email?.trim().toLowerCase();
  const user = await User.findOne({ email });
  if (!user) return res.status(404).json({ success: false, code: 'EMAIL_NOT_FOUND', msg: 'Email này chưa có tài khoản PSIFU.' });
  const passwordOk=await bcrypt.compare(String(req.body.password||''),user.password).catch(()=>false); const legacyPasswordOk=!passwordOk&&user.password===req.body.password;
  if (!passwordOk&&!legacyPasswordOk) return res.status(401).json({ success: false, code: 'WRONG_PASSWORD', msg: 'Mật khẩu chưa chính xác. Vui lòng thử lại.' });
  if (user.emailVerificationRequired && !user.emailVerified) return res.status(403).json({ success:false, code:'EMAIL_NOT_VERIFIED', msg:'Hãy xác minh email trước khi đăng nhập.' });
  res.json({ success: true, user: toClient(user), accessToken:makeToken(user) });
  if(legacyPasswordOk||bcrypt.getRounds(user.password)>PASSWORD_HASH_ROUNDS){bcrypt.hash(req.body.password,PASSWORD_HASH_ROUNDS).then(password=>User.updateOne({_id:user._id},{$set:{password}})).catch(()=>{});}
});
app.post('/api/auth/google', authLimiter, async (req, res) => {
  const idToken = String(req.body.idToken || '');
  const clientId = process.env.GOOGLE_WEB_CLIENT_ID;
  if (!clientId) return res.status(503).json({ success: false, msg: 'Đăng nhập Google chưa được cấu hình trên máy chủ.' });
  if (!idToken || idToken.length > 4096) return res.status(400).json({ success: false, msg: 'Google ID token không hợp lệ.' });
  try {
    const response = await fetch(`https://oauth2.googleapis.com/tokeninfo?id_token=${encodeURIComponent(idToken)}`);
    const payload = await response.json().catch(() => ({}));
    if (!response.ok || payload.aud !== clientId || !['accounts.google.com', 'https://accounts.google.com'].includes(payload.iss) || !['true', true].includes(payload.email_verified) || !emailPattern.test(payload.email || '') || !payload.sub) {
      return res.status(401).json({ success: false, msg: 'Không thể xác minh tài khoản Google này.' });
    }
    const email = cleanEmail(payload.email);
    let user = await User.findOne({ $or: [{ googleSubject: payload.sub }, { email }] });
    if (user && user.googleSubject && user.googleSubject !== payload.sub) return res.status(409).json({ success: false, msg: 'Email này đã được liên kết với một tài khoản Google khác.' });
    if (!user) {
      const fullName = String(payload.name || email.split('@')[0]).trim().slice(0, 80) || 'PSIFU Member';
      user = await User.create({ fullName, email, password: await bcrypt.hash(crypto.randomBytes(32).toString('hex'), PASSWORD_HASH_ROUNDS), googleSubject: payload.sub, avatarUrl: payload.picture || '', emailVerified: true, role: 'mentee', isFirstLogin: true });
    } else {
      user.googleSubject = payload.sub;
      user.emailVerified = true;
      if (!user.avatarUrl && payload.picture) user.avatarUrl = payload.picture;
      await user.save();
    }
    res.json({ success: true, user: toClient(user), accessToken: makeToken(user) });
  } catch (error) {
    console.error('Google sign-in verification:', error.message);
    res.status(502).json({ success: false, msg: 'Không thể xác minh Google lúc này. Vui lòng thử lại.' });
  }
});
app.patch('/api/users/:email',requireAuth,requireSelfOrAdmin(), async (req,res)=>{const allowed=['fullName','avatarUrl','university','academicYear','fptK','studentId','major','specialization','track','currentTerm','mentorBio','mentorCourses','mentorAvailability','notificationPreferences','isFirstLogin'];const updates={};for(const key of allowed)if(req.body[key]!==undefined)updates[key]=req.body[key];if(updates.fullName!==undefined&&(String(updates.fullName).trim().length<2||String(updates.fullName).trim().length>80))return res.status(400).json({success:false,msg:'Họ tên phải từ 2 đến 80 ký tự.'});const user=await User.findOneAndUpdate({email:req.params.email.toLowerCase()},{$set:updates},{new:true});if(!user)return res.status(404).json({success:false});res.json({success:true,user:toClient(user)});});
app.get('/api/users/:email/settings', async (req,res) => { const user=await User.findOne({email:req.params.email.toLowerCase()}); if(!user)return res.status(404).json({success:false}); res.json({notificationPreferences:user.notificationPreferences||{},mentorAvailability:user.mentorAvailability||{accepting:true,slots:[]}}); });
app.patch('/api/users/:email/settings',requireAuth,requireSelfOrAdmin(),async(req,res)=>{const allowed={};if(req.body.notificationPreferences&&typeof req.body.notificationPreferences==='object')allowed.notificationPreferences=req.body.notificationPreferences;if(req.body.mentorAvailability&&typeof req.body.mentorAvailability==='object')allowed.mentorAvailability=req.body.mentorAvailability;const user=await User.findOneAndUpdate({email:req.params.email.toLowerCase()},{$set:allowed},{new:true});if(!user)return res.status(404).json({success:false});res.json({success:true,notificationPreferences:user.notificationPreferences,mentorAvailability:user.mentorAvailability});});
app.post('/api/uploads/cloudinary-signature',requireAuth,async(req,res)=>{const email=req.auth.email;if(cleanEmail(req.body.email)!==email)return res.status(403).json({success:false,msg:'Bạn chỉ được tải tài liệu cho chính mình.'});const user=await User.findOne({email});if(!user||user.role!=='mentor')return res.status(403).json({success:false,msg:'Chỉ Mentor được tải tài liệu lên.'});if(!cloudinaryConfigured())return res.status(503).json({success:false,msg:'Cloudinary chưa được cấu hình trên máy chủ.'});const fileName=String(req.body.fileName||'document.pdf');if(!fileName.toLowerCase().endsWith('.pdf'))return res.status(400).json({success:false,msg:'PSIFU chỉ hỗ trợ tệp PDF.'});const timestamp=Math.floor(Date.now()/1000);const safeEmail=email.replace(/[^a-z0-9]/gi,'_');const params={folder:`psifu/mentor-documents/${safeEmail}`,public_id:`doc_${timestamp}_${crypto.randomUUID().slice(0,8)}`,timestamp};res.json({success:true,cloudName:process.env.CLOUDINARY_CLOUD_NAME,apiKey:process.env.CLOUDINARY_API_KEY,timestamp,folder:params.folder,publicId:params.public_id,signature:cloudinarySignature(params)});});
app.post('/api/uploads/avatar-signature',requireAuth,async(req,res)=>{if(!cloudinaryConfigured())return res.status(503).json({success:false,msg:'Cloudinary chưa được cấu hình trên máy chủ.'});const timestamp=Math.floor(Date.now()/1000);const safeEmail=req.auth.email.replace(/[^a-z0-9]/gi,'_');const params={folder:'psifu/avatars',public_id:`avatar_${safeEmail}`,overwrite:true,timestamp};res.json({success:true,cloudName:process.env.CLOUDINARY_CLOUD_NAME,apiKey:process.env.CLOUDINARY_API_KEY,timestamp,folder:params.folder,publicId:params.public_id,signature:cloudinarySignature(params)});});
app.post('/api/payments/payos/topups',requireAuth, async (req,res) => { const email=req.auth.email; const coins=Number(req.body.coins); const packages=[50,100,200,500]; if(cleanEmail(req.body.email)!==email||!packages.includes(coins)) return res.status(400).json({success:false,msg:'Gói nạp không hợp lệ.'}); if(!payosConfigured()) return res.status(503).json({success:false,msg:'PayOS chưa được cấu hình trên máy chủ. Hãy thêm PAYOS_CLIENT_ID, PAYOS_API_KEY, PAYOS_CHECKSUM_KEY, PAYOS_RETURN_URL và PAYOS_CANCEL_URL.'}); const user=await User.findOne({email}); if(!user) return res.status(404).json({success:false,msg:'Không tìm thấy tài khoản.'}); try { const orderCode=await nextPayosOrderCode(); const amount=coins*1000; const requestData={orderCode,amount,description:`PSIFU ${coins} Xu`,returnUrl:process.env.PAYOS_RETURN_URL,cancelUrl:process.env.PAYOS_CANCEL_URL,items:[{name:`PSIFU ${coins} Xu`,quantity:1,price:amount}]}; requestData.signature=payosSignature({orderCode,amount,description:requestData.description,returnUrl:requestData.returnUrl,cancelUrl:requestData.cancelUrl}); const payment=await payosRequest('/v2/payment-requests',{method:'POST',body:JSON.stringify(requestData)}); const order=await PaymentOrder.create({orderCode,userEmail:email,coins,amount,paymentLinkId:payment.paymentLinkId,checkoutUrl:payment.checkoutUrl}); await AuditLog.create({actorEmail:email,action:'PAYOS_TOPUP_CREATED',targetType:'PaymentOrder',targetId:String(order.orderCode),metadata:{coins,amount}}); res.status(201).json({success:true,orderCode:order.orderCode,checkoutUrl:order.checkoutUrl,qrCode:payment.qrCode,amount:order.amount,status:order.status}); } catch(error){ console.error('PayOS create payment link:',error.message); res.status(502).json({success:false,msg:error.message||'Không thể tạo liên kết PayOS.'}); } });
app.get('/api/payments/payos/orders/:orderCode',requireAuth, async (req,res) => { const order=await PaymentOrder.findOne({orderCode:Number(req.params.orderCode)}); if(!order|| (order.userEmail!==req.auth.email&&req.auth.role!=='admin')) return res.status(404).json({success:false,msg:'Không tìm thấy đơn thanh toán.'}); res.json({success:true,orderCode:order.orderCode,status:order.status,coins:order.coins,amount:order.amount,userXu:order.status==='PAID'?(await User.findOne({email:order.userEmail}).select('userXu'))?.userXu:undefined}); });
app.post('/api/payments/payos/webhook', async (req,res) => { try { const payload=req.body||{}; const expected=payosSignature(payload.data||{}); const received=String(payload.signature||''); if(!received || expected.length!==received.length || !crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(received))) return res.status(400).json({success:false,msg:'Webhook signature không hợp lệ.'}); if(payload.code!=='00' || payload.success!==true || payload.data?.code!=='00') return res.status(200).json({success:true,ignored:true}); const existing=await PaymentOrder.findOne({orderCode:Number(payload.data.orderCode)}); if(!existing || existing.status==='PAID') return res.status(200).json({success:true,ignored:true}); if(existing.amount!==Number(payload.data.amount)) return res.status(400).json({success:false,msg:'Số tiền webhook không khớp đơn hàng.'}); const order=await PaymentOrder.findOneAndUpdate({orderCode:existing.orderCode,status:'PENDING'},{$set:{status:'PAID',reference:payload.data.reference,paidAt:new Date()}},{new:true}); if(!order) return res.status(200).json({success:true,ignored:true}); const user=await User.findOneAndUpdate({email:order.userEmail},{$inc:{userXu:order.coins}},{new:true}); if(!user) return res.status(404).json({success:false}); await Transaction.create({userEmail:user.email,type:'PAYOS_TOPUP',amount:order.coins,status:'SUCCESS',metadata:{orderCode:order.orderCode,amountVnd:order.amount,reference:order.reference}}); await Notification.create({userEmail:user.email,title:'Nạp Xu thành công',body:`PayOS đã xác nhận đơn #${order.orderCode}. ${order.coins} Xu đã được cộng vào ví.`,type:'WALLET'}); res.status(200).json({success:true}); } catch(error){ console.error('PayOS webhook:',error.message); res.status(500).json({success:false,msg:'Không thể xử lý webhook.'}); } });
app.put('/api/mentors/:email/bank-account',requireAuth,requireSelfOrAdmin(),async(req,res)=>{const email=req.params.email.trim().toLowerCase(),bank=req.body.bankAccount||{};const required=['bankName','accountNumber','accountHolder'];if(required.some(key=>!String(bank[key]||'').trim()))return res.status(400).json({success:false,msg:'Hãy nhập đủ ngân hàng, số tài khoản và tên chủ tài khoản.'});if(!/^\d{6,19}$/.test(String(bank.accountNumber)))return res.status(400).json({success:false,msg:'Số tài khoản phải gồm 6–19 chữ số.'});const user=await User.findOneAndUpdate({email,role:'mentor'},{$set:{bankAccount:{bankName:String(bank.bankName).trim(),accountNumber:String(bank.accountNumber).trim(),accountHolder:String(bank.accountHolder).trim().toUpperCase(),bin:String(bank.bin||'').trim()}}},{new:true});if(!user)return res.status(404).json({success:false,msg:'Không tìm thấy tài khoản Mentor.'});res.json({success:true,bankAccount:user.bankAccount});});
app.get('/api/mentors/:email/bank-accounts',requireAuth,requireSelfOrAdmin(),async(req,res)=>{const user=await User.findOne({email:req.params.email.toLowerCase(),role:'mentor'}).lean();if(!user)return res.status(404).json({success:false,msg:'Không tìm thấy tài khoản Mentor.'});const accounts=user.bankAccounts?.length?user.bankAccounts:(user.bankAccount?.accountNumber?[{...user.bankAccount,id:'legacy'}]:[]);res.json({success:true,accounts,selectedAccountNumber:user.bankAccount?.accountNumber||null});});
app.post('/api/mentors/:email/bank-accounts',requireAuth,requireSelfOrAdmin(),async(req,res)=>{const email=req.params.email.toLowerCase(),bank=req.body.bankAccount||{};if(!String(bank.bankName||'').trim()||!/^\d{6,19}$/.test(String(bank.accountNumber||''))||!String(bank.accountHolder||'').trim())return res.status(400).json({success:false,msg:'Ngân hàng, số tài khoản (6–19 chữ số) và chủ tài khoản là bắt buộc.'});const user=await User.findOne({email,role:'mentor'}).lean();if(!user)return res.status(404).json({success:false,msg:'Không tìm thấy tài khoản Mentor.'});const accounts=user.bankAccounts?.length?user.bankAccounts:(user.bankAccount?.accountNumber?[{...user.bankAccount,id:'legacy'}]:[]);if(accounts.some(item=>item.accountNumber===String(bank.accountNumber)))return res.status(409).json({success:false,msg:'Tài khoản này đã tồn tại.'});const account={id:crypto.randomUUID(),bankName:String(bank.bankName).trim(),accountNumber:String(bank.accountNumber),accountHolder:String(bank.accountHolder).trim().toUpperCase(),bin:String(bank.bin||'').trim()};accounts.push(account);await User.collection.updateOne({_id:user._id},{$set:{bankAccounts:accounts,bankAccount:user.bankAccount?.accountNumber?user.bankAccount:account}});res.status(201).json({success:true,accounts,selectedAccountNumber:(user.bankAccount||account).accountNumber});});
app.patch('/api/mentors/:email/bank-accounts/:accountId/select',requireAuth,requireSelfOrAdmin(),async(req,res)=>{const user=await User.findOne({email:req.params.email.toLowerCase(),role:'mentor'}).lean();if(!user)return res.status(404).json({success:false});const accounts=user.bankAccounts?.length?user.bankAccounts:(user.bankAccount?.accountNumber?[{...user.bankAccount,id:'legacy'}]:[]);const account=accounts.find(item=>item.id===req.params.accountId);if(!account)return res.status(404).json({success:false,msg:'Không tìm thấy tài khoản.'});await User.collection.updateOne({_id:user._id},{$set:{bankAccounts:accounts,bankAccount:account}});res.json({success:true,bankAccount:account});});
app.post('/api/payouts',async(req,res)=>{const email=req.auth.email,amountXu=Number(req.body.amountXu);if(cleanEmail(req.body.email)!==email||!Number.isInteger(amountXu)||amountXu<50)return res.status(400).json({success:false,msg:'Số Xu rút tối thiểu là 50 Xu.'});const user=await User.findOneAndUpdate({email,role:'mentor',availableXu:{$gte:amountXu},'bankAccount.accountNumber':{$exists:true,$ne:''}},{$inc:{availableXu:-amountXu}},{new:true});if(!user)return res.status(400).json({success:false,msg:'Số dư khả dụng không đủ hoặc bạn chưa thêm tài khoản ngân hàng.'});try{const payoutCode=`PO-${Date.now()}-${crypto.randomUUID().slice(0,6).toUpperCase()}`;const payout=await Payout.create({payoutCode,mentorEmail:email,amountXu,amountVnd:amountXu*1000,bankAccount:user.bankAccount,status:'PROCESSING'});await Transaction.create({userEmail:email,type:'MENTOR_PAYOUT',amount:-amountXu,status:'PROCESSING',metadata:{payoutCode,bankName:user.bankAccount.bankName,accountNumber:user.bankAccount.accountNumber}});await AuditLog.create({actorEmail:email,action:'PAYOUT_CREATED',targetType:'Payout',targetId:payoutCode,metadata:{amountXu,amountVnd:payout.amountVnd}});await Notification.create({userEmail:email,title:'Yêu cầu rút Xu đang xử lý',body:`Lệnh ${payoutCode} rút ${amountXu} Xu đang chờ đối soát.`,type:'WALLET'});res.status(201).json({success:true,payout:toClient(payout),availableXu:user.availableXu});}catch(error){await User.findOneAndUpdate({email},{$inc:{availableXu:amountXu}});throw error;}});
app.get('/api/payouts/:email',async(req,res)=>{const email=req.params.email.trim().toLowerCase();res.json((await Payout.find({mentorEmail:email}).sort({createdAt:-1}).limit(50)).map(toClient));});
app.get('/api/payouts/:email/:payoutCode',async(req,res)=>{const payout=await Payout.findOne({mentorEmail:req.params.email.trim().toLowerCase(),payoutCode:req.params.payoutCode});if(!payout)return res.status(404).json({success:false,msg:'Không tìm thấy lệnh Payout.'});res.json({success:true,payout:toClient(payout)});});
app.get('/api/support-tickets/:email',async(req,res)=>res.json((await SupportTicket.find({reporterEmail:req.params.email.toLowerCase()}).sort({createdAt:-1})).map(toClient)));
app.post('/api/support-tickets',requireAuth,async(req,res)=>{if(cleanEmail(req.body.reporterEmail)!==req.auth.email||!req.body.reason||!req.body.detail?.trim())return res.status(400).json({success:false,msg:'Hãy chọn lý do và mô tả chi tiết sự cố.'});res.status(201).json({success:true,ticket:toClient(await SupportTicket.create({...req.body,reporterEmail:req.auth.email,reporterRole:req.auth.role}))});});
app.patch('/api/users/:email/role',requireAuth,requireRole('admin'), async (req, res) => { if (!['mentee', 'mentor', 'admin'].includes(req.body.role)) return res.status(400).json({ success: false }); const user = await User.findOne({ email: req.params.email.toLowerCase() }); if (!user || user.protected) return res.status(403).json({ success: false }); const oldRole=user.role; user.role = req.body.role; await user.save(); await AuditLog.create({actorEmail:req.auth.email,action:'ROLE_CHANGED',targetType:'User',targetId:user.email,metadata:{from:oldRole,to:user.role}}); res.json({ success: true }); });
const isPremiumUser=user=>user?.subscription?.plan==='PREMIUM'&&user.subscription.status==='ACTIVE'&&new Date(user.subscription.expiresAt)>new Date();
const subscriptionState=user=>({plan:isPremiumUser(user)?'PREMIUM':'FREE',status:isPremiumUser(user)?'ACTIVE':(user?.subscription?.status||'ACTIVE'),startedAt:user?.subscription?.startedAt||null,expiresAt:user?.subscription?.expiresAt||null,isPremium:isPremiumUser(user)});
app.get('/api/premium/plan',(_req,res)=>res.json(PREMIUM_PLAN));
app.get('/api/premium/subscription/:email',requireAuth,requireSelfOrAdmin(),async(req,res)=>{const user=await User.findOne({email:req.params.email.toLowerCase()});if(!user)return res.status(404).json({success:false});res.json(subscriptionState(user));});
app.post('/api/premium/mock-payment/complete',requireAuth,async(req,res)=>{if(process.env.NODE_ENV==='production')return res.status(404).json({success:false,msg:'Phương thức thanh toán không khả dụng.'});if(cleanEmail(req.body.email)!==req.auth.email)return res.status(403).json({success:false,msg:'Bạn chỉ được thao tác trên tài khoản của chính mình.'});const user=await User.findOne({email:req.auth.email});if(!user)return res.status(404).json({success:false});const startedAt=new Date();const expiresAt=new Date(startedAt.getTime()+PREMIUM_PLAN.durationDays*86400000);user.subscription={plan:'PREMIUM',status:'ACTIVE',startedAt,expiresAt};await user.save();await Transaction.create({userEmail:user.email,type:'PREMIUM_SUBSCRIPTION',amount:PREMIUM_PLAN.price,status:'SUCCESS',metadata:{mode:'VNPAY_MOCK'}});await Notification.create({userEmail:user.email,title:'Chào mừng đến PSIFU Premium!',body:'Premium của bạn đã được kích hoạt.',type:'PREMIUM'});res.json({success:true,subscription:subscriptionState(user)});});
app.get('/api/premium/documents/:email',requireAuth,requireSelfOrAdmin(),async(req,res)=>{const user=await User.findOne({email:req.params.email.toLowerCase()});if(!isPremiumUser(user))return res.status(403).json({success:false,code:'PREMIUM_REQUIRED',message:'Tài nguyên này cần PSIFU Premium.'});res.json((await PremiumDocument.find()).map(toClient));});
app.post('/api/quiz/access',requireAuth,async(req,res)=>{if(cleanEmail(req.body.email)!==req.auth.email)return res.status(403).json({success:false,msg:'Bạn chỉ được sử dụng lượt quiz của chính mình.'});const user=await User.findById(req.auth.sub);if(!user)return res.status(404).json({success:false});const period=new Date().toISOString().slice(0,7);if(user.aiQuizUsagePeriod!==period){user.aiQuizUsagePeriod=period;user.aiQuizUsage=0;}const limit=isPremiumUser(user)?PREMIUM_PLAN.premiumAiQuizLimit:PREMIUM_PLAN.freeAiQuizLimit;if(user.aiQuizUsage>=limit){await user.save();return res.status(429).json({success:false,code:isPremiumUser(user)?'LIMIT_REACHED':'PREMIUM_REQUIRED',limit});}user.aiQuizUsage+=1;await user.save();res.json({success:true,remaining:limit-user.aiQuizUsage,plan:subscriptionState(user).plan});});
app.get('/api/notifications/:email',requireAuth,requireSelfOrAdmin(),async(req,res)=>res.json((await Notification.find({userEmail:req.params.email.toLowerCase()}).sort({createdAt:-1}).limit(30)).map(toClient)));
app.patch('/api/notifications/:id/read',requireAuth,async(req,res)=>res.json({success:!!await Notification.findOneAndUpdate({_id:req.params.id,userEmail:req.auth.email},{read:true})}));
app.get('/api/questions', async (_req, res) => res.json((await Question.find().sort({ createdAt: -1 })).map(toClient)));
app.post('/api/questions',requireAuth, async (req, res) => {const question=String(req.body.question||'').trim();if(!question||question.length>2000)return res.status(400).json({success:false,msg:'Nội dung câu hỏi không hợp lệ.'});res.status(201).json(toClient(await Question.create({question,menteeName:String(req.body.menteeName||'').slice(0,80),major:String(req.body.major||'').slice(0,80),currentTerm:String(req.body.currentTerm||'').slice(0,40)})));});
app.get('/api/bookings',requireAuth, async (req, res) => { const filter=req.auth.role==='admin'?{}:req.auth.role==='mentor'?{mentorEmail:req.auth.email}:{$or:[{menteeEmail:req.auth.email},{menteeName:(await User.findById(req.auth.sub).select('fullName'))?.fullName}]}; res.json((await Booking.find(filter).sort({ createdAt: -1 })).map(toClient)); });
app.get('/api/mentors/:email/availability',requireAuth,async(req,res)=>{const mentorEmail=cleanEmail(req.params.email);const date=String(req.query.date||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return res.status(400).json({success:false,msg:'Ngày phải theo định dạng YYYY-MM-DD.'});const mentor=await User.findOne({email:mentorEmail,role:'mentor'}).select('mentorAvailability');if(!mentor)return res.status(404).json({success:false,msg:'Không tìm thấy Mentor.'});const occupied=await Booking.find({mentorEmail,dateTime:{$regex:`^${date.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')} `},status:{$ne:'Đã hủy'}}).select('dateTime');const day=['Chủ Nhật','Thứ Hai','Thứ Ba','Thứ Tư','Thứ Năm','Thứ Sáu','Thứ Bảy'][new Date(`${date}T00:00:00`).getDay()];const ranges=mentor.mentorAvailability?.accepting===false?[]:(mentor.mentorAvailability?.slots?.find(slot=>slot.day===day)?.ranges||[]);res.json({success:true,date,accepting:mentor.mentorAvailability?.accepting!==false,ranges,occupiedTimes:occupied.map(item=>String(item.dateTime).split(' ')[1]).filter(Boolean)});});
app.post('/api/bookings',requireAuth, async (req, res) => { if(req.auth.role!=='mentee')return res.status(403).json({success:false,msg:'Chỉ Mentee có thể đặt lịch.'});const mentorEmail=cleanEmail(req.body.mentorEmail);const mentor=await User.findOne({email:mentorEmail,role:'mentor'}).select('fullName mentorFee mentorAvailability');const mentee=await User.findById(req.auth.sub).select('fullName userXu escrowXu');const dateTime=String(req.body.dateTime||'');const matched=dateTime.match(/^(\d{4}-\d{2}-\d{2})\s+(\d{2}:\d{2})$/);if(!mentor||!mentee||!matched)return res.status(400).json({success:false,msg:'Thông tin lịch hẹn không hợp lệ.'});const day=['Chủ Nhật','Thứ Hai','Thứ Ba','Thứ Tư','Thứ Năm','Thứ Sáu','Thứ Bảy'][new Date(`${matched[1]}T00:00:00`).getDay()];const ranges=mentor.mentorAvailability?.slots?.find(slot=>slot.day===day)?.ranges||[];const allowed=mentor.mentorAvailability?.accepting!==false&&ranges.some(range=>{const [from,to]=String(range).split('-').map(value=>value.trim());return from&&to&&matched[2]>=from&&matched[2]<to;});if(!allowed)return res.status(409).json({success:false,msg:'Mentor không mở lịch ở khung giờ này. Vui lòng chọn lịch trống khác.'});if(await Booking.exists({mentorEmail,dateTime,status:{$ne:'Đã hủy'}}))return res.status(409).json({success:false,msg:'Khung giờ này đã có mentee đặt trước.'});const fee=Number(mentor.mentorFee||50);const charged=await User.findOneAndUpdate({_id:mentee._id,userXu:{$gte:fee}},{$inc:{userXu:-fee,escrowXu:fee}},{new:true});if(!charged)return res.status(400).json({success:false,msg:'Bạn không đủ Xu để đặt lịch.'});try{const booking=await Booking.create({mentorEmail,mentorName:mentor.fullName,menteeName:mentee.fullName,menteeEmail:req.auth.email,course:String(req.body.course||'').slice(0,80),dateTime,note:String(req.body.note||'').trim().slice(0,2000),fee,meetingLink:'https://meet.google.com/psifu-session'});await Transaction.create({userEmail:req.auth.email,type:'BOOKING_ESCROW',amount:-fee,status:'HELD',metadata:{bookingId:String(booking._id),mentorEmail}});res.status(201).json({success:true,booking:toClient(booking),userXu:charged.userXu});}catch(error){await User.findByIdAndUpdate(mentee._id,{$inc:{userXu:fee,escrowXu:-fee}});throw error;}});
app.patch('/api/bookings/:id',requireAuth, async (req, res) => { const booking=await Booking.findById(req.params.id); if(!booking|| (req.auth.role!=='admin'&&booking.mentorEmail!==req.auth.email&&booking.menteeEmail!==req.auth.email))return res.status(404).json({success:false}); const allowed=req.auth.role==='mentor'||req.auth.role==='admin'?['Đã xác nhận','Đã hoàn thành','Đã hủy']:['Đã hủy']; if(!allowed.includes(req.body.status))return res.status(403).json({success:false,msg:'Bạn không có quyền cập nhật trạng thái này.'});if(booking.status===req.body.status)return res.json({success:true});if(req.body.status==='Đã hủy'&&booking.fee>0){await User.findOneAndUpdate({email:booking.menteeEmail},{$inc:{userXu:booking.fee,escrowXu:-booking.fee}});await Transaction.create({userEmail:booking.menteeEmail,type:'BOOKING_REFUND',amount:booking.fee,status:'SUCCESS',metadata:{bookingId:String(booking._id)}});}if(req.body.status==='Đã hoàn thành'&&booking.fee>0){await User.findOneAndUpdate({email:booking.menteeEmail},{$inc:{escrowXu:-booking.fee}});await User.findOneAndUpdate({email:booking.mentorEmail},{$inc:{availableXu:booking.fee}});await Transaction.create({userEmail:booking.mentorEmail,type:'BOOKING_RELEASE',amount:booking.fee,status:'SUCCESS',metadata:{bookingId:String(booking._id)}});}booking.status=req.body.status;await booking.save();res.json({success:true}); });
app.post('/api/bookings/:id/rating',requireAuth,async(req,res)=>{const booking=await Booking.findOne({_id:req.params.id,menteeEmail:req.auth.email});const score=Number(req.body.score);const comment=String(req.body.comment||'').trim();if(!booking)return res.status(404).json({success:false,msg:'Không tìm thấy lịch hẹn.'});if(booking.status!=='Đã hoàn thành')return res.status(409).json({success:false,msg:'Chỉ đánh giá sau khi buổi học hoàn thành.'});if(booking.rating?.score)return res.status(409).json({success:false,msg:'Buổi học này đã được đánh giá.'});if(!Number.isInteger(score)||score<1||score>5)return res.status(400).json({success:false,msg:'Vui lòng chọn từ 1 đến 5 sao.'});booking.rating={score,comment:comment.slice(0,1000),createdAt:new Date()};await booking.save();res.status(201).json({success:true,rating:booking.rating});});
app.get('/api/chats/:roomId',requireAuth,requireChatParticipant, async (req, res) => res.json((await ChatMessage.find({ roomId: req.params.roomId }).sort({ createdAt: 1 }).limit(25)).map(toClient)));
app.post('/api/chats/:roomId',requireAuth,requireChatParticipant, async (req, res) => { const text=String(req.body.text||'').trim();if(!text||text.length>2000)return res.status(400).json({success:false,msg:'Nội dung tin nhắn không hợp lệ.'});const role=req.auth.role==='mentor'?'MENTOR':req.auth.role==='admin'?'ADMIN':'MENTEE';const message=toClient(await ChatMessage.create({ roomId:req.params.roomId,user:String(req.body.user||'').slice(0,80),authorEmail:req.auth.email,role,text }));io.to(req.params.roomId).emit('chat:message',message);res.status(201).json(message); });
const catalogDocument = doc => { const item=toClient(doc); delete item.fileUri; delete item.cloudinaryPublicId; return item; };
app.get('/api/mentor-documents', async (req, res) => { const catalog=req.query.catalog==='true'; if(catalog){const documents=await MentorDocument.find({status:'PUBLISHED'}).sort({createdAt:-1});return res.json(documents.map(catalogDocument));} return requireAuth(req,res,async()=>{const filter=req.auth.role==='admin'?{}:{mentorEmail:req.auth.email}; if(req.query.status)filter.status=req.query.status; const documents=await MentorDocument.find(filter).sort({createdAt:-1});res.json(documents.map(toClient));}); });
app.post('/api/mentor-documents',requireAuth,requireRole('mentor','admin'), async (req, res) => { if(req.auth.role!=='admin'&&cleanEmail(req.body.mentorEmail)!==req.auth.email)return res.status(403).json({success:false,msg:'Bạn chỉ được tạo tài liệu của chính mình.'}); const document=await MentorDocument.create({...req.body,mentorEmail:req.auth.role==='admin'?cleanEmail(req.body.mentorEmail):req.auth.email});await AuditLog.create({actorEmail:req.auth.email,action:'MENTOR_DOCUMENT_CREATED',targetType:'MentorDocument',targetId:String(document._id),metadata:{status:document.status,title:document.title}});res.status(201).json(toClient(document));});
app.patch('/api/mentor-documents/:id',requireAuth,requireRole('mentor','admin'),async(req,res)=>{const document=await MentorDocument.findById(req.params.id);if(!document||(req.auth.role!=='admin'&&document.mentorEmail!==req.auth.email))return res.status(404).json({success:false,msg:'Không tìm thấy tài liệu.'});const allowed=['title','course','category','description','fee','previewPages','status'];for(const key of allowed)if(req.body[key]!==undefined)document[key]=req.body[key];await document.save();await AuditLog.create({actorEmail:req.auth.email,action:'MENTOR_DOCUMENT_UPDATED',targetType:'MentorDocument',targetId:String(document._id),metadata:{status:document.status,title:document.title}});res.json({success:true,document:toClient(document)});});
app.delete('/api/mentor-documents/:id',requireAuth,requireRole('mentor','admin'),async(req,res)=>{const document=await MentorDocument.findById(req.params.id);if(!document||(req.auth.role!=='admin'&&document.mentorEmail!==req.auth.email))return res.status(404).json({success:false,msg:'Không tìm thấy tài liệu.'});await DocumentUnlock.deleteMany({documentId:document._id});await MentorDocument.deleteOne({_id:document._id});await AuditLog.create({actorEmail:req.auth.email,action:'MENTOR_DOCUMENT_DELETED',targetType:'MentorDocument',targetId:String(document._id),metadata:{title:document.title}});res.json({success:true});});
app.get('/api/document-unlocks/:email',async(req,res)=>{const unlocks=await DocumentUnlock.find({userEmail:req.params.email.toLowerCase()}).select('documentId');res.json(unlocks.map(item=>String(item.documentId)));});
app.post('/api/mentor-documents/:id/unlock',requireAuth,async(req,res)=>{const email=req.auth.email;if(cleanEmail(req.body.email)!==email)return res.status(403).json({success:false,msg:'Bạn chỉ được mở khóa cho chính mình.'});const document=await MentorDocument.findOne({_id:req.params.id,status:'PUBLISHED'});if(!document)return res.status(404).json({success:false,msg:'Không tìm thấy tài liệu đã xuất bản.'});const exists=await DocumentUnlock.exists({userEmail:email,documentId:document._id});if(exists)return res.json({success:true,alreadyUnlocked:true,userXu:(await User.findOne({email}).select('userXu'))?.userXu});const fee=Number(document.fee||0);const user=await User.findOneAndUpdate({email,userXu:{$gte:fee}},{$inc:{userXu:-fee}},{new:true});if(!user)return res.status(400).json({success:false,msg:'Bạn không đủ Xu để mở khóa tài liệu.'});try{await DocumentUnlock.create({userEmail:email,documentId:document._id});await MentorDocument.findByIdAndUpdate(document._id,{$inc:{unlocks:1,revenue:fee}});await Transaction.create({userEmail:email,type:'DOCUMENT_UNLOCK',amount:-fee,status:'SUCCESS',metadata:{documentId:String(document._id),title:document.title}});await AuditLog.create({actorEmail:email,action:'DOCUMENT_UNLOCKED',targetType:'MentorDocument',targetId:String(document._id),metadata:{fee,title:document.title}});res.status(201).json({success:true,userXu:user.userXu});}catch(error){await User.findOneAndUpdate({email},{$inc:{userXu:fee}});if(error?.code===11000)return res.json({success:true,alreadyUnlocked:true,userXu:(await User.findOne({email}).select('userXu'))?.userXu});throw error;}});
app.get('/api/mentor-documents/:id/access',requireAuth,async(req,res)=>{const email=req.auth.email;if(cleanEmail(req.query.email)!==email)return res.status(403).json({success:false,msg:'Bạn chỉ được đọc tài liệu đã mở khóa của chính mình.'});const document=await MentorDocument.findOne({_id:req.params.id,status:'PUBLISHED'});if(!document)return res.status(404).json({success:false,msg:'Không tìm thấy tài liệu.'});const unlocked=Number(document.fee||0)===0||await DocumentUnlock.exists({userEmail:email,documentId:document._id});if(!unlocked)return res.status(403).json({success:false,msg:'Hãy mở khóa tài liệu trước.'});res.json({success:true,document:{...catalogDocument(document),fileUri:document.fileUri}});});
app.use((err, _req, res, _next) => { console.error(err); res.status(500).json({ success: false, msg: 'Lỗi máy chủ.' }); });
const port = process.env.PORT || 4000;
mongoose.connect(process.env.MONGODB_URI).then(async () => { await User.bulkWrite(systemUsers.map(user => ({ updateOne: { filter: { email: user.email }, update: { $setOnInsert: user }, upsert: true } }))); await User.updateMany({email:{$in:systemUsers.map(user=>user.email)}},{$set:{emailVerified:true}}); await Course.collection.dropIndex('code_1').catch(() => null); await Course.collection.dropIndex('code_1_major_1_specialization_1').catch(() => null); await Course.collection.createIndex({ code: 1, major: 1, specialization: 1, track: 1 }, { unique: true }); await Course.bulkWrite(allCourseSeeds.map(course => ({ updateOne: { filter: { code: course.code, major: course.major, specialization: course.specialization, track: course.track }, update: { $set: course }, upsert: true } }))); server.listen(port, '0.0.0.0', () => console.log(`PSIFU API is running on port ${port}`)); }).catch(error => { console.error('Không thể kết nối MongoDB:', error.message); process.exit(1); });
