require('dotenv').config();
const crypto = require('crypto'); const nodemailer = require('nodemailer');
const express = require('express'); const cors = require('cors'); const mongoose = require('mongoose');
const app = express(); app.use(cors()); app.use(express.json());
const User = mongoose.model('User', new mongoose.Schema({ fullName: { type: String, required: true }, email: { type: String, required: true, unique: true, lowercase: true }, password: { type: String, required: true }, role: { type: String, enum: ['mentee', 'mentor', 'admin'], default: 'mentee' }, avatarUrl: String, university: String, academicYear: String, fptK: String, studentId: String, major: String, specialization: String, currentTerm: String, specialty: String, mentorBio: String, mentorFee: Number, mentorCourses: [String], mentorAvailability: { accepting: { type: Boolean, default: true }, slots: [{ day: String, ranges: [String] }] }, notificationPreferences: { appointment: { type: Boolean, default: true }, community: { type: Boolean, default: true }, chat: { type: Boolean, default: true }, public: { type: Boolean, default: true }, document: { type: Boolean, default: true }, wallet: { type: Boolean, default: true } }, userXu: { type: Number, default: 20 }, availableXu: { type: Number, default: 0 }, escrowXu: { type: Number, default: 0 }, bankAccount: { bankName: String, accountNumber: String, accountHolder: String }, subscription: { plan: { type: String, enum: ['FREE','PREMIUM'], default: 'FREE' }, status: { type: String, enum: ['ACTIVE','EXPIRED','CANCELLED'], default: 'ACTIVE' }, startedAt: Date, expiresAt: Date }, aiQuizUsage: { type: Number, default: 0 }, aiQuizUsagePeriod: String, hasCheckedInToday: { type: Boolean, default: false }, isFirstLogin: { type: Boolean, default: true }, emailVerified: { type: Boolean, default: false }, otpHash: String, otpPurpose: String, otpExpiresAt: Date, protected: { type: Boolean, default: false } }, { timestamps: true, versionKey: false }));
const Course = mongoose.model('Course', new mongoose.Schema({ code: { type: String, unique: true }, name: String, term: String, fee: Number, link: String, major: { type: String, default: 'Kỹ thuật phần mềm' }, specialization: { type: String, default: 'NodeJS' } }, { timestamps: true, versionKey: false }));
const Question = mongoose.model('Question', new mongoose.Schema({ menteeName: String, major: String, currentTerm: String, question: String, status: { type: String, default: 'new' } }, { timestamps: true, versionKey: false }));
const Booking = mongoose.model('Booking', new mongoose.Schema({ mentorEmail: String, mentorName: String, menteeName: String, menteeEmail: String, course: String, dateTime: String, note: String, meetingLink: String, status: { type: String, default: 'Chờ mentor xác nhận' } }, { timestamps: true, versionKey: false }));
const ChatMessage = mongoose.model('ChatMessage', new mongoose.Schema({ roomId: String, user: String, authorEmail: String, text: String }, { timestamps: true, versionKey: false }));
const MentorDocument = mongoose.model('MentorDocument', new mongoose.Schema({ mentorEmail: String, mentorName: String, title: String, fileName: String, fileUri: String, mimeType: String, term: String, course: String, specialty: String, category: String, description: String, fee: { type: Number, default: 15 }, previewPages: { type: Number, default: 2 }, status: { type: String, default: 'DRAFT' }, pages: { type: Number, default: 0 }, unlocks: { type: Number, default: 0 }, revenue: { type: Number, default: 0 } }, { timestamps: true, versionKey: false }));
const PremiumDocument = mongoose.model('PremiumDocument', new mongoose.Schema({ title:String, university:String, major:String, term:String, course:String, description:String, sourceType:{type:String,default:'PREMIUM_LIBRARY'} }, { timestamps:true, versionKey:false }));
const Notification = mongoose.model('Notification', new mongoose.Schema({ userEmail:String, title:String, body:String, type:String, read:{type:Boolean,default:false} }, { timestamps:true, versionKey:false }));
const Transaction = mongoose.model('Transaction', new mongoose.Schema({ userEmail:String, type:String, amount:Number, status:String, metadata:Object }, { timestamps:true, versionKey:false }));
const PaymentOrder = mongoose.model('PaymentOrder', new mongoose.Schema({ orderCode:{type:Number,unique:true,index:true}, userEmail:{type:String,index:true}, coins:Number, amount:Number, status:{type:String,enum:['PENDING','PAID','CANCELLED','EXPIRED','FAILED'],default:'PENDING'}, paymentLinkId:String, checkoutUrl:String, reference:String, paidAt:Date }, { timestamps:true, versionKey:false }));
const SupportTicket = mongoose.model('SupportTicket', new mongoose.Schema({ reporterEmail:String, reporterRole:String, bookingId:String, reason:String, detail:String, evidenceNames:[String], status:{type:String,default:'OPEN'} }, { timestamps:true, versionKey:false }));
const PREMIUM_PLAN={code:'PREMIUM_MONTHLY',name:'PSIFU Premium',price:49000,durationDays:30,freeAiQuizLimit:Number(process.env.FREE_AI_QUIZ_LIMIT||3),premiumAiQuizLimit:Number(process.env.PREMIUM_AI_QUIZ_LIMIT||30)};
const systemUsers = [{ fullName: 'PSIFU Admin', email: 'admin@psifu.vn', password: 'admin123', role: 'admin', university: 'PSIFU', userXu: 0, hasCheckedInToday: false, isFirstLogin: false, protected: true }, { fullName: 'Mentor Minh Anh', email: 'mentor.se@psifu.vn', password: 'mentor123', role: 'mentor', specialty: 'Kỹ thuật phần mềm (SE)', university: 'FPT University', userXu: 0, hasCheckedInToday: false, isFirstLogin: false, protected: true }, { fullName: 'Mentor Gia Hân', email: 'mentor.data@psifu.vn', password: 'mentor123', role: 'mentor', specialty: 'Data Science & AI', university: 'FPT University', userXu: 0, hasCheckedInToday: false, isFirstLogin: false, protected: true }, { fullName: 'Mentor Quốc Bảo', email: 'mentor.business@psifu.vn', password: 'mentor123', role: 'mentor', specialty: 'Digital Marketing & Business', university: 'FPT University', userXu: 0, hasCheckedInToday: false, isFirstLogin: false, protected: true }];
const courseSeed = [
['SSL101c','Academic Skills for University Success','Kỳ 1',5],['CSI104','Introduction to Computer Science','Kỳ 1',6],['PRF192','Programming Fundamentals','Kỳ 1',8],['MAE101','Mathematics for Engineering','Kỳ 1',10],['CEA201','Computer Organization and Architecture','Kỳ 1',9],
['PRO192','Object-Oriented Programming','Kỳ 2',10],['MAD101','Discrete Mathematics','Kỳ 2',12],['OSG202','Operating Systems','Kỳ 2',9],['SSG104','Communication and In-Group Working Skills','Kỳ 2',5],['NWC204','Computer Networking','Kỳ 2',8],
['JPD113','Elementary Japanese 1-A1.1','Kỳ 3',7],['CSD201','Data Structures and Algorithms','Kỳ 3',15],['DBI202','Introduction to Databases','Kỳ 3',10],['LAB211','OOP with Java Lab','Kỳ 3',12],['WED201c','Web Design','Kỳ 3',7],
['MAS291','Statistics and Probability','Kỳ 4',11],['JPD123','Elementary Japanese 1-A1.2','Kỳ 4',7],['IOT102','Internet of Things','Kỳ 4',9],['PRJ301','Java Web Application Development','Kỳ 4',14],['SWE201c','Introduction to Software Engineering','Kỳ 4',8],
['SWP391','Application Development Project','Kỳ 5',15],['ITE302c','Ethics in IT','Kỳ 5',5],['SWR302','Software Requirement','Kỳ 5',10],['SWT301','Software Testing','Kỳ 5',11],['FER202','Front-End Web Development with React','Kỳ 5',13],
['ENW493c','Research Methods & Academic Writing Skills','Kỳ 6',8],['OJT202','On the Job Training','Kỳ 6',15],['SWD392','Software Architecture and Design','Kỳ 7',12],['PMG201c','Project Management','Kỳ 7',9],['EXE101','Experiential Entrepreneurship 1','Kỳ 7',10],['SDN302','Server-Side Development with NodeJS, Express, and MongoDB','Kỳ 7',14],['MMA301','Multiplatform Mobile App Development','Kỳ 7',14],
['WDP301','Web Development Project','Kỳ 8',15],['PRM393','Mobile Programming','Kỳ 8',13],['MLN111','Philosophy of Marxism – Leninism','Kỳ 8',6],['EXE201','Experiential Entrepreneurship 2','Kỳ 8',12],['WDU203c','UI/UX Design','Kỳ 8',8],['MLN122','Political Economics of Marxism – Leninism','Kỳ 8',6],
['HCM202','Ho Chi Minh Ideology','Kỳ 9',6],['MLN131','Scientific Socialism','Kỳ 9',6],['VNR202','History of Việt Nam Communist Party','Kỳ 9',6],['SE_GRA_ELE','Graduation Elective - Software Engineering','Kỳ 9',15]
].map(([code,name,term,fee]) => ({ code, name, term, fee, link: `https://drive.google.com/${code.toLowerCase()}_secret` }));
const toClient = doc => { const value = doc.toObject ? doc.toObject() : doc; return { ...value, id: String(value._id), createdAt: value.createdAt || new Date().toISOString() }; };
const mailer = process.env.SMTP_HOST ? nodemailer.createTransport({ host: process.env.SMTP_HOST, port: Number(process.env.SMTP_PORT || 587), secure: process.env.SMTP_SECURE === 'true', auth: process.env.SMTP_USER ? { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS } : undefined }) : null;
const hashOtp = code => crypto.createHash('sha256').update(code).digest('hex');
const payosConfigured = () => Boolean(process.env.PAYOS_CLIENT_ID && process.env.PAYOS_API_KEY && process.env.PAYOS_CHECKSUM_KEY && process.env.PAYOS_RETURN_URL && process.env.PAYOS_CANCEL_URL);
const payosSignature = data => crypto.createHmac('sha256', process.env.PAYOS_CHECKSUM_KEY || '').update(Object.keys(data || {}).sort().filter(key => data[key] !== undefined && data[key] !== null).map(key => `${key}=${data[key]}`).join('&')).digest('hex');
const payosRequest = async (path, options = {}) => { const response = await fetch(`https://api-merchant.payos.vn${path}`, { ...options, headers:{ 'Content-Type':'application/json', 'x-client-id':process.env.PAYOS_CLIENT_ID, 'x-api-key':process.env.PAYOS_API_KEY, ...(options.headers||{}) } }); const payload = await response.json().catch(() => ({})); if (!response.ok || payload.code && payload.code !== '00') throw new Error(payload.desc || 'PayOS không thể xử lý yêu cầu thanh toán.'); return payload.data; };
const nextPayosOrderCode = async () => { for(let attempts=0;attempts<8;attempts+=1){ const code=Number(`${Date.now().toString().slice(-8)}${crypto.randomInt(10,100)}`); if(!await PaymentOrder.exists({orderCode:code})) return code; } throw new Error('Không thể tạo mã đơn thanh toán.'); };
const issueOtp = async (user, purpose) => { const code = crypto.randomInt(100000, 1000000).toString(); user.otpHash = hashOtp(code); user.otpPurpose = purpose; user.otpExpiresAt = new Date(Date.now() + 10 * 60 * 1000); await user.save(); if (!mailer) throw new Error('SMTP chưa được cấu hình. Hãy thêm SMTP_HOST, SMTP_USER và SMTP_PASS vào backend/.env.'); await mailer.sendMail({ from: process.env.SMTP_FROM || process.env.SMTP_USER, to: user.email, subject: purpose === 'verify-email' ? 'PSIFU – Mã xác minh email' : 'PSIFU – Mã đặt lại mật khẩu', text: `Mã OTP PSIFU của bạn là: ${code}. Mã có hiệu lực trong 10 phút.` }); };
const validateOtp = (user, purpose, code) => user && user.otpPurpose === purpose && user.otpExpiresAt > new Date() && user.otpHash === hashOtp(String(code || ''));
app.get('/api/health', (_req, res) => res.json({ status: 'ok' }));
app.get('/payment/return', (_req, res) => res.type('html').send('<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>PSIFU Payment</title></head><body style="font-family:system-ui;text-align:center;padding:56px 20px;background:#f8faff;color:#102a56"><h1>Đang xác nhận thanh toán</h1><p>PayOS đã chuyển bạn về PSIFU. Hãy quay lại ứng dụng; Xu chỉ được cộng sau khi webhook được xác minh.</p></body></html>'));
app.get('/payment/cancel', (_req, res) => res.type('html').send('<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>PSIFU Payment</title></head><body style="font-family:system-ui;text-align:center;padding:56px 20px;background:#f8faff;color:#102a56"><h1>Thanh toán chưa hoàn tất</h1><p>Bạn có thể quay lại ứng dụng PSIFU để thử lại khi sẵn sàng.</p></body></html>'));
app.get('/api/courses', async (req, res) => { const filter = { major: req.query.major || 'Kỹ thuật phần mềm', specialization: req.query.specialization || 'NodeJS' }; if (req.query.term) filter.term = req.query.term; res.json((await Course.find(filter).sort({ term: 1, code: 1 })).map(toClient)); });
app.get('/api/users', async (_req, res) => res.json((await User.find().sort({ createdAt: -1 })).map(toClient)));
app.post('/api/users', async (req, res) => { const email = req.body.email?.trim().toLowerCase(); if (!email || !req.body.fullName || !req.body.password) return res.status(400).json({ success: false, msg: 'Thiếu thông tin bắt buộc.' }); if (await User.exists({ email })) return res.status(409).json({ success: false, msg: 'Email/Tài khoản này đã tồn tại!' }); const user = await User.create({ ...req.body, email }); res.status(201).json({ success: true, msg: 'Đăng ký thành công!', user: toClient(user) }); });
app.post('/api/auth/email-verification/send', async (req, res) => { const user = await User.findOne({ email: req.body.email?.trim().toLowerCase() }); if (!user) return res.status(404).json({ success: false, msg: 'Không tìm thấy tài khoản với email này.' }); try { await issueOtp(user, 'verify-email'); res.json({ success: true, msg: 'Mã OTP đã được gửi tới email của bạn.' }); } catch (error) { res.status(503).json({ success: false, msg: error.message }); } });
app.post('/api/auth/email-verification/verify', async (req, res) => { const user = await User.findOne({ email: req.body.email?.trim().toLowerCase() }); if (!validateOtp(user, 'verify-email', req.body.code)) return res.status(400).json({ success: false, msg: 'Mã OTP không đúng hoặc đã hết hạn.' }); user.emailVerified = true; user.otpHash = undefined; user.otpPurpose = undefined; user.otpExpiresAt = undefined; await user.save(); res.json({ success: true, msg: 'Email đã được xác minh.' }); });
app.post('/api/auth/password-reset/send', async (req, res) => { const user = await User.findOne({ email: req.body.email?.trim().toLowerCase() }); if (!user) return res.status(404).json({ success: false, msg: 'Email này chưa có tài khoản PSIFU.' }); try { await issueOtp(user, 'password-reset'); res.json({ success: true, msg: 'Mã đặt lại mật khẩu đã được gửi.' }); } catch (error) { res.status(503).json({ success: false, msg: error.message }); } });
app.post('/api/auth/password-reset/verify', async (req, res) => { const user = await User.findOne({ email: req.body.email?.trim().toLowerCase() }); if (!validateOtp(user, 'password-reset', req.body.code)) return res.status(400).json({ success: false, msg: 'Mã OTP không đúng hoặc đã hết hạn.' }); res.json({ success: true }); });
app.post('/api/auth/password-reset/complete', async (req, res) => { const user = await User.findOne({ email: req.body.email?.trim().toLowerCase() }); if (!req.body.password || req.body.password.length < 6) return res.status(400).json({ success: false, msg: 'Mật khẩu cần có ít nhất 6 ký tự.' }); if (!validateOtp(user, 'password-reset', req.body.code)) return res.status(400).json({ success: false, msg: 'Mã OTP không đúng hoặc đã hết hạn.' }); user.password = req.body.password; user.otpHash = undefined; user.otpPurpose = undefined; user.otpExpiresAt = undefined; await user.save(); res.json({ success: true, msg: 'Đặt lại mật khẩu thành công.' }); });
app.post('/api/auth/login', async (req, res) => {
  const email = req.body.email?.trim().toLowerCase();
  const user = await User.findOne({ email });
  if (!user) return res.status(404).json({ success: false, code: 'EMAIL_NOT_FOUND', msg: 'Email này chưa có tài khoản PSIFU.' });
  if (user.password !== req.body.password) return res.status(401).json({ success: false, code: 'WRONG_PASSWORD', msg: 'Mật khẩu chưa chính xác. Vui lòng thử lại.' });
  if (user.emailVerified === false && !user.protected) return res.status(403).json({ success: false, code: 'EMAIL_NOT_VERIFIED', msg: 'Email chưa được xác minh. Vui lòng kiểm tra hộp thư.' });
  res.json({ success: true, user: toClient(user) });
});
app.patch('/api/users/:email', async (req, res) => { const user = await User.findOneAndUpdate({ email: req.params.email.toLowerCase() }, req.body, { new: true }); if (!user) return res.status(404).json({ success: false }); res.json({ success: true, user: toClient(user) }); });
app.get('/api/users/:email/settings', async (req,res) => { const user=await User.findOne({email:req.params.email.toLowerCase()}); if(!user)return res.status(404).json({success:false}); res.json({notificationPreferences:user.notificationPreferences||{},mentorAvailability:user.mentorAvailability||{accepting:true,slots:[]}}); });
app.patch('/api/users/:email/settings', async (req,res) => { const allowed={}; if(req.body.notificationPreferences)allowed.notificationPreferences=req.body.notificationPreferences; if(req.body.mentorAvailability)allowed.mentorAvailability=req.body.mentorAvailability; const user=await User.findOneAndUpdate({email:req.params.email.toLowerCase()},allowed,{new:true}); if(!user)return res.status(404).json({success:false}); res.json({success:true,notificationPreferences:user.notificationPreferences,mentorAvailability:user.mentorAvailability}); });
app.post('/api/payments/payos/topups', async (req,res) => { const email=req.body.email?.trim().toLowerCase(); const coins=Number(req.body.coins); const packages=[50,100,200,500]; if(!email || !packages.includes(coins)) return res.status(400).json({success:false,msg:'Gói nạp không hợp lệ.'}); if(!payosConfigured()) return res.status(503).json({success:false,msg:'PayOS chưa được cấu hình trên máy chủ. Hãy thêm PAYOS_CLIENT_ID, PAYOS_API_KEY, PAYOS_CHECKSUM_KEY, PAYOS_RETURN_URL và PAYOS_CANCEL_URL.'}); const user=await User.findOne({email}); if(!user) return res.status(404).json({success:false,msg:'Không tìm thấy tài khoản.'}); try { const orderCode=await nextPayosOrderCode(); const amount=coins*1000; const requestData={orderCode,amount,description:`PSIFU ${coins} Xu`,returnUrl:process.env.PAYOS_RETURN_URL,cancelUrl:process.env.PAYOS_CANCEL_URL}; requestData.signature=payosSignature(requestData); const payment=await payosRequest('/v2/payment-requests',{method:'POST',body:JSON.stringify(requestData)}); const order=await PaymentOrder.create({orderCode,userEmail:email,coins,amount,paymentLinkId:payment.paymentLinkId,checkoutUrl:payment.checkoutUrl}); res.status(201).json({success:true,orderCode:order.orderCode,checkoutUrl:order.checkoutUrl,amount:order.amount,status:order.status}); } catch(error){ console.error('PayOS create payment link:',error.message); res.status(502).json({success:false,msg:error.message||'Không thể tạo liên kết PayOS.'}); } });
app.get('/api/payments/payos/orders/:orderCode', async (req,res) => { const order=await PaymentOrder.findOne({orderCode:Number(req.params.orderCode)}); if(!order) return res.status(404).json({success:false,msg:'Không tìm thấy đơn thanh toán.'}); res.json({success:true,orderCode:order.orderCode,status:order.status,coins:order.coins,amount:order.amount,userXu:order.status==='PAID'?(await User.findOne({email:order.userEmail}).select('userXu'))?.userXu:undefined}); });
app.post('/api/payments/payos/webhook', async (req,res) => { try { const payload=req.body||{}; const expected=payosSignature(payload.data||{}); const received=String(payload.signature||''); if(!received || expected.length!==received.length || !crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(received))) return res.status(400).json({success:false,msg:'Webhook signature không hợp lệ.'}); if(payload.code!=='00' || payload.success!==true || payload.data?.code!=='00') return res.status(200).json({success:true,ignored:true}); const existing=await PaymentOrder.findOne({orderCode:Number(payload.data.orderCode)}); if(!existing || existing.status==='PAID') return res.status(200).json({success:true,ignored:true}); if(existing.amount!==Number(payload.data.amount)) return res.status(400).json({success:false,msg:'Số tiền webhook không khớp đơn hàng.'}); const order=await PaymentOrder.findOneAndUpdate({orderCode:existing.orderCode,status:'PENDING'},{$set:{status:'PAID',reference:payload.data.reference,paidAt:new Date()}},{new:true}); if(!order) return res.status(200).json({success:true,ignored:true}); const user=await User.findOneAndUpdate({email:order.userEmail},{$inc:{userXu:order.coins}},{new:true}); if(!user) return res.status(404).json({success:false}); await Transaction.create({userEmail:user.email,type:'PAYOS_TOPUP',amount:order.coins,status:'SUCCESS',metadata:{orderCode:order.orderCode,amountVnd:order.amount,reference:order.reference}}); await Notification.create({userEmail:user.email,title:'Nạp Xu thành công',body:`PayOS đã xác nhận đơn #${order.orderCode}. ${order.coins} Xu đã được cộng vào ví.`,type:'WALLET'}); res.status(200).json({success:true}); } catch(error){ console.error('PayOS webhook:',error.message); res.status(500).json({success:false,msg:'Không thể xử lý webhook.'}); } });
app.post('/api/wallet/withdraw', async (req, res) => { const user = await User.findOne({ email: req.body.email?.toLowerCase() }); const amount = Number(req.body.amount); if (!user || user.role !== 'mentor') return res.status(403).json({ success: false, msg: 'Chỉ Mentor có thể gửi yêu cầu rút tiền.' }); if (!user.bankAccount?.accountNumber) return res.status(400).json({ success: false, msg: 'Hãy thêm tài khoản ngân hàng trước.' }); if (!Number.isInteger(amount) || amount <= 0 || amount > (user.availableXu || 0)) return res.status(400).json({ success: false, msg: 'Số Xu rút không hợp lệ hoặc vượt quá số dư khả dụng.' }); user.availableXu -= amount; await user.save(); const tx = await Transaction.create({ userEmail:user.email, type:'MENTOR_WITHDRAWAL', amount:-amount, status:'PENDING', metadata:{ bankName:user.bankAccount.bankName, accountNumber:user.bankAccount.accountNumber } }); res.status(201).json({ success:true, transaction:toClient(tx), availableXu:user.availableXu }); });
app.get('/api/support-tickets/:email',async(req,res)=>res.json((await SupportTicket.find({reporterEmail:req.params.email.toLowerCase()}).sort({createdAt:-1})).map(toClient)));
app.post('/api/support-tickets',async(req,res)=>{if(!req.body.reporterEmail||!req.body.reason||!req.body.detail?.trim())return res.status(400).json({success:false,msg:'Hãy chọn lý do và mô tả chi tiết sự cố.'});res.status(201).json({success:true,ticket:toClient(await SupportTicket.create(req.body))});});
app.patch('/api/users/:email/role', async (req, res) => { if (!['mentee', 'mentor', 'admin'].includes(req.body.role)) return res.status(400).json({ success: false }); const user = await User.findOne({ email: req.params.email.toLowerCase() }); if (!user || user.protected) return res.status(403).json({ success: false }); user.role = req.body.role; await user.save(); res.json({ success: true }); });
const isPremiumUser=user=>user?.subscription?.plan==='PREMIUM'&&user.subscription.status==='ACTIVE'&&new Date(user.subscription.expiresAt)>new Date();
const subscriptionState=user=>({plan:isPremiumUser(user)?'PREMIUM':'FREE',status:isPremiumUser(user)?'ACTIVE':(user?.subscription?.status||'ACTIVE'),startedAt:user?.subscription?.startedAt||null,expiresAt:user?.subscription?.expiresAt||null,isPremium:isPremiumUser(user)});
app.get('/api/premium/plan',(_req,res)=>res.json(PREMIUM_PLAN));
app.get('/api/premium/subscription/:email',async(req,res)=>{const user=await User.findOne({email:req.params.email.toLowerCase()});if(!user)return res.status(404).json({success:false});res.json(subscriptionState(user));});
app.post('/api/premium/mock-payment/complete',async(req,res)=>{const user=await User.findOne({email:req.body.email?.toLowerCase()});if(!user)return res.status(404).json({success:false});const startedAt=new Date();const expiresAt=new Date(startedAt.getTime()+PREMIUM_PLAN.durationDays*86400000);user.subscription={plan:'PREMIUM',status:'ACTIVE',startedAt,expiresAt};await user.save();await Transaction.create({userEmail:user.email,type:'PREMIUM_SUBSCRIPTION',amount:PREMIUM_PLAN.price,status:'SUCCESS',metadata:{mode:'VNPAY_MOCK'}});await Notification.create({userEmail:user.email,title:'Chào mừng đến PSIFU Premium!',body:'Premium của bạn đã được kích hoạt.',type:'PREMIUM'});res.json({success:true,subscription:subscriptionState(user)});});
app.get('/api/premium/documents/:email',async(req,res)=>{const user=await User.findOne({email:req.params.email.toLowerCase()});if(!isPremiumUser(user))return res.status(403).json({success:false,code:'PREMIUM_REQUIRED',message:'Tài nguyên này cần PSIFU Premium.'});res.json((await PremiumDocument.find()).map(toClient));});
app.post('/api/quiz/access',async(req,res)=>{const user=await User.findOne({email:req.body.email?.toLowerCase()});if(!user)return res.status(404).json({success:false});const period=new Date().toISOString().slice(0,7);if(user.aiQuizUsagePeriod!==period){user.aiQuizUsagePeriod=period;user.aiQuizUsage=0;}const limit=isPremiumUser(user)?PREMIUM_PLAN.premiumAiQuizLimit:PREMIUM_PLAN.freeAiQuizLimit;if(user.aiQuizUsage>=limit){await user.save();return res.status(429).json({success:false,code:isPremiumUser(user)?'LIMIT_REACHED':'PREMIUM_REQUIRED',limit});}user.aiQuizUsage+=1;await user.save();res.json({success:true,remaining:limit-user.aiQuizUsage,plan:subscriptionState(user).plan});});
app.get('/api/notifications/:email',async(req,res)=>res.json((await Notification.find({userEmail:req.params.email.toLowerCase()}).sort({createdAt:-1}).limit(30)).map(toClient)));
app.patch('/api/notifications/:id/read',async(req,res)=>res.json({success:!!await Notification.findByIdAndUpdate(req.params.id,{read:true})}));
app.get('/api/questions', async (_req, res) => res.json((await Question.find().sort({ createdAt: -1 })).map(toClient)));
app.post('/api/questions', async (req, res) => res.status(201).json(toClient(await Question.create(req.body))));
app.get('/api/bookings', async (_req, res) => res.json((await Booking.find().sort({ createdAt: -1 })).map(toClient)));
app.post('/api/bookings', async (req, res) => { if (await Booking.exists({ mentorEmail: req.body.mentorEmail, dateTime: req.body.dateTime })) return res.status(409).json({ success: false, msg: 'Khung giờ này đã có mentee đặt trước.' }); res.status(201).json(toClient(await Booking.create({ ...req.body, meetingLink: req.body.meetingLink || 'https://meet.google.com/psifu-session' }))); });
app.patch('/api/bookings/:id', async (req, res) => res.json({ success: !!await Booking.findByIdAndUpdate(req.params.id, req.body) }));
app.get('/api/chats/:roomId', async (req, res) => res.json((await ChatMessage.find({ roomId: req.params.roomId }).sort({ createdAt: 1 }).limit(25)).map(toClient)));
app.post('/api/chats/:roomId', async (req, res) => res.status(201).json(toClient(await ChatMessage.create({ ...req.body, roomId: req.params.roomId }))));
app.get('/api/mentor-documents', async (_req, res) => res.json((await MentorDocument.find().sort({ createdAt: -1 })).map(toClient)));
app.post('/api/mentor-documents', async (req, res) => res.status(201).json(toClient(await MentorDocument.create(req.body))));
app.use((err, _req, res, _next) => { console.error(err); res.status(500).json({ success: false, msg: 'Lỗi máy chủ.' }); });
const port = process.env.PORT || 4000;
mongoose.connect(process.env.MONGODB_URI).then(async () => { await User.bulkWrite(systemUsers.map(user => ({ updateOne: { filter: { email: user.email }, update: { $setOnInsert: user }, upsert: true } }))); await Course.bulkWrite(courseSeed.map(course => ({ updateOne: { filter: { code: course.code }, update: { $setOnInsert: course }, upsert: true } }))); app.listen(port, '0.0.0.0', () => console.log(`PSIFU API is running on port ${port}`)); }).catch(error => { console.error('Không thể kết nối MongoDB:', error.message); process.exit(1); });
