require('dotenv').config();
const crypto = require('crypto'); const nodemailer = require('nodemailer'); const bcrypt = require('bcryptjs'); const jwt = require('jsonwebtoken'); const rateLimit = require('express-rate-limit');
const express = require('express'); const cors = require('cors'); const mongoose = require('mongoose');
const app = express(); app.use(cors()); app.use(express.json());
const User = mongoose.model('User', new mongoose.Schema({ fullName: { type: String, required: true }, email: { type: String, required: true, unique: true, lowercase: true }, password: { type: String, required: true }, googleSubject: { type: String, unique: true, sparse: true }, role: { type: String, enum: ['mentee', 'mentor', 'admin'], default: 'mentee' }, avatarUrl: String, university: String, academicYear: String, fptK: String, studentId: String, major: String, specialization: String, track: String, currentTerm: String, specialty: String, mentorBio: String, mentorFee: Number, mentorCourses: [String], mentorAvailability: { accepting: { type: Boolean, default: true }, slots: [{ day: String, ranges: [String] }] }, notificationPreferences: { appointment: { type: Boolean, default: true }, community: { type: Boolean, default: true }, chat: { type: Boolean, default: true }, public: { type: Boolean, default: true }, document: { type: Boolean, default: true }, wallet: { type: Boolean, default: true } }, userXu: { type: Number, default: 20 }, availableXu: { type: Number, default: 0 }, escrowXu: { type: Number, default: 0 }, bankAccount: { bankName: String, accountNumber: String, accountHolder: String }, subscription: { plan: { type: String, enum: ['FREE','PREMIUM'], default: 'FREE' }, status: { type: String, enum: ['ACTIVE','EXPIRED','CANCELLED'], default: 'ACTIVE' }, startedAt: Date, expiresAt: Date }, aiQuizUsage: { type: Number, default: 0 }, aiQuizUsagePeriod: String, hasCheckedInToday: { type: Boolean, default: false }, isFirstLogin: { type: Boolean, default: true }, emailVerified: { type: Boolean, default: false }, otpHash: String, otpPurpose: String, otpExpiresAt: Date, protected: { type: Boolean, default: false } }, { timestamps: true, versionKey: false }));
const Course = mongoose.model('Course', new mongoose.Schema({ code: String, name: String, term: String, fee: Number, link: String, major: String, specialization: String, track: { type: String, default: '' } }, { timestamps: true, versionKey: false }));
Course.schema.index({ code: 1, major: 1, specialization: 1, track: 1 }, { unique: true });
const Question = mongoose.model('Question', new mongoose.Schema({ menteeName: String, major: String, currentTerm: String, question: String, status: { type: String, default: 'new' } }, { timestamps: true, versionKey: false }));
const Booking = mongoose.model('Booking', new mongoose.Schema({ mentorEmail: String, mentorName: String, menteeName: String, menteeEmail: String, course: String, dateTime: String, note: String, meetingLink: String, status: { type: String, default: 'Chờ mentor xác nhận' } }, { timestamps: true, versionKey: false }));
const ChatMessage = mongoose.model('ChatMessage', new mongoose.Schema({ roomId: String, user: String, authorEmail: String, text: String }, { timestamps: true, versionKey: false }));
const MentorDocument = mongoose.model('MentorDocument', new mongoose.Schema({ mentorEmail: String, mentorName: String, title: String, fileName: String, fileUri: String, cloudinaryPublicId:String, fileSize:Number, mimeType: String, term: String, course: String, specialty: String, category: String, description: String, fee: { type: Number, default: 15 }, previewPages: { type: Number, default: 2 }, status: { type: String, default: 'DRAFT' }, pages: { type: Number, default: 0 }, unlocks: { type: Number, default: 0 }, revenue: { type: Number, default: 0 } }, { timestamps: true, versionKey: false }));
const PremiumDocument = mongoose.model('PremiumDocument', new mongoose.Schema({ title:String, university:String, major:String, term:String, course:String, description:String, sourceType:{type:String,default:'PREMIUM_LIBRARY'} }, { timestamps:true, versionKey:false }));
const Notification = mongoose.model('Notification', new mongoose.Schema({ userEmail:String, title:String, body:String, type:String, read:{type:Boolean,default:false} }, { timestamps:true, versionKey:false }));
const Transaction = mongoose.model('Transaction', new mongoose.Schema({ userEmail:String, type:String, amount:Number, status:String, metadata:Object }, { timestamps:true, versionKey:false }));
const Payout = mongoose.model('Payout', new mongoose.Schema({ payoutCode:{type:String,unique:true,index:true}, mentorEmail:{type:String,index:true}, amountXu:Number, amountVnd:Number, bankAccount:{bankName:String,accountNumber:String,accountHolder:String,bin:String}, status:{type:String,enum:['PROCESSING','SUCCESS','FAILED','CANCELLED'],default:'PROCESSING'}, provider:{type:String,default:'MANUAL_REVIEW'}, providerReference:String, failureReason:String, completedAt:Date }, { timestamps:true, versionKey:false }));
const DocumentUnlock = mongoose.model('DocumentUnlock', new mongoose.Schema({ userEmail:{type:String,index:true}, documentId:{type:mongoose.Schema.Types.ObjectId,ref:'MentorDocument',index:true} }, { timestamps:true, versionKey:false }));
DocumentUnlock.schema.index({userEmail:1,documentId:1},{unique:true});
const PaymentOrder = mongoose.model('PaymentOrder', new mongoose.Schema({ orderCode:{type:Number,unique:true,index:true}, userEmail:{type:String,index:true}, coins:Number, amount:Number, status:{type:String,enum:['PENDING','PAID','CANCELLED','EXPIRED','FAILED'],default:'PENDING'}, paymentLinkId:String, checkoutUrl:String, reference:String, paidAt:Date }, { timestamps:true, versionKey:false }));
const SupportTicket = mongoose.model('SupportTicket', new mongoose.Schema({ reporterEmail:String, reporterRole:String, bookingId:String, reason:String, detail:String, evidenceNames:[String], status:{type:String,default:'OPEN'} }, { timestamps:true, versionKey:false }));
const PREMIUM_PLAN={code:'PREMIUM_MONTHLY',name:'PSIFU Premium',price:49000,durationDays:30,freeAiQuizLimit:Number(process.env.FREE_AI_QUIZ_LIMIT||3),premiumAiQuizLimit:Number(process.env.PREMIUM_AI_QUIZ_LIMIT||30)};
const systemUsers = [{ fullName: 'PSIFU Admin', email: 'admin@psifu.vn', password: 'admin123', role: 'admin', university: 'PSIFU', userXu: 0, hasCheckedInToday: false, isFirstLogin: false, protected: true }, { fullName: 'Mentor Minh Anh', email: 'mentor.se@psifu.vn', password: 'mentor123', role: 'mentor', specialty: 'Kỹ thuật phần mềm (SE)', university: 'FPT University', userXu: 0, hasCheckedInToday: false, isFirstLogin: false, protected: true }, { fullName: 'Mentor Gia Hân', email: 'mentor.data@psifu.vn', password: 'mentor123', role: 'mentor', specialty: 'Data Science & AI', university: 'FPT University', userXu: 0, hasCheckedInToday: false, isFirstLogin: false, protected: true }, { fullName: 'Mentor Quốc Bảo', email: 'mentor.business@psifu.vn', password: 'mentor123', role: 'mentor', specialty: 'Digital Marketing & Business', university: 'FPT University', userXu: 0, hasCheckedInToday: false, isFirstLogin: false, protected: true }];
const courseSeed = [
['SSL101c','Academic Skills for University Success','Kỳ 1',5],['CSI104','Introduction to Computer Science','Kỳ 1',6],['PRF192','Programming Fundamentals','Kỳ 1',8],['MAE101','Mathematics for Engineering','Kỳ 1',10],['CEA201','Computer Organization and Architecture','Kỳ 1',9],
['PRO192','Object-Oriented Programming','Kỳ 2',10],['MAD101','Discrete Mathematics','Kỳ 2',12],['OSG202','Operating Systems','Kỳ 2',9],['SSG104','Communication and In-Group Working Skills','Kỳ 2',5],['NWC204','Computer Networking','Kỳ 2',8],
['JPD113','Elementary Japanese 1-A1.1','Kỳ 3',7],['CSD201','Data Structures and Algorithms','Kỳ 3',15],['DBI202','Introduction to Databases','Kỳ 3',10],['LAB211','OOP with Java Lab','Kỳ 3',12],['WED201c','Web Design','Kỳ 3',7],
['MAS291','Statistics and Probability','Kỳ 4',11],['JPD123','Elementary Japanese 1-A1.2','Kỳ 4',7],['IOT102','Internet of Things','Kỳ 4',9],['PRJ301','Java Web Application Development','Kỳ 4',14],['SWE201c','Introduction to Software Engineering','Kỳ 4',8],
['SWP391','Application Development Project','Kỳ 5',15],['ITE302c','Ethics in IT','Kỳ 5',5],['SWR302','Software Requirement','Kỳ 5',10],['SWT301','Software Testing','Kỳ 5',11],['FER202','Front-End Web Development with React','Kỳ 5',13],
['ENW493c','Research Methods & Academic Writing Skills','Kỳ 6',8],['OJT202','On the Job Training','Kỳ 6',15],['SWD392','Software Architecture and Design','Kỳ 7',12],['PMG201c','Project Management','Kỳ 7',9],['EXE101','Experiential Entrepreneurship 1','Kỳ 7',10],['SDN302','Server-Side Development with NodeJS, Express, and MongoDB','Kỳ 7',14],['MMA301','Multiplatform Mobile App Development','Kỳ 7',14],
['WDP301','Web Development Project','Kỳ 8',15],['PRM393','Mobile Programming','Kỳ 8',13],['MLN111','Philosophy of Marxism – Leninism','Kỳ 8',6],['EXE201','Experiential Entrepreneurship 2','Kỳ 8',12],['WDU203c','UI/UX Design','Kỳ 8',8],['MLN122','Political Economics of Marxism – Leninism','Kỳ 8',6],
['HCM202','Ho Chi Minh Ideology','Kỳ 9',6],['MLN131','Scientific Socialism','Kỳ 9',6],['VNR202','History of Việt Nam Communist Party','Kỳ 9',6],['SE_GRA_ELE','Graduation Elective - Software Engineering','Kỳ 9',15]
].map(([code,name,term,fee]) => ({ code, name, term, fee, major: 'Computing', specialization: 'SE', track: 'NodeJS', link: `https://drive.google.com/${code.toLowerCase()}_secret` }));

const bbaMcCourseSeed = [
['GDQP','Military Education',0],['TMI101','Traditional Musical Instrument',0],['TRS601','English 6 (University Success)',0],['VOV114','Vovinam 1/3',0],['VOV124','Vovinam 2/3',0],['VOV134','Vovinam 3/3',0],
['DTG111','Visual Design Tools 1',1],['MED201','New Media Technology',1],['MGT103','Introduction to Management',1],['MKT101','Marketing Principles',1],['SSL101c','Academic Skills for University Success',1],
['ACC101','Principles of Accounting',2],['CMC201c','Creative Writing',2],['DTG121','Visual Design Tools 2',2],['MMP201','Media Psychology',2],['SSG104','Communication and In-Group Working Skills',2],
['CCO201','Corporate Communication',3],['MKT208c','Social Media Marketing',3],['PFD201','Photography for Designer',3],['RMC201','Research Methods in Communication',3],['SDP201','Sound Production',3],
['CHN111','Elementary Chinese 1',4],['IFT201c','Innovation and Future Thinking',4],['IPR102','Intellectual Property Rights',4],['VDP201','Video Production',4],['WMC201','Media Writing',4],
['CHN122','Elementary Chinese 2',5],['EVN201','Event Planning',5],['MCO201m','Transmedia Storytelling',5],['MKT304','Integrated Marketing Communications',5],['WDU202c','UI/UX Design',5],
['ENW492c','Academic Writing Skills',6],['OJB202','On-the-job Training',6],
['BRA301','Brand Management',7],['CCM301','Crisis Communications Management',7],['CSP201m','Content Strategy for Professionals',7],['EXE101','Experiential Entrepreneurship 1',7],['MEP301','Multimedia Production Project',7],
['EXE201','Experiential Entrepreneurship 2',8],['MLN111','Philosophy of Marxism - Leninism',8],['MLN122','Political Economics of Marxism - Leninism',8],['MSM201c','Meta Social Media Marketing Management',8],['PMG201c','Project Management',8],['PRE301','Public Relations Principles and Strategies',8],
['GRA497','Capstone Project Multimedia Communications',9],['HCM202','Ho Chi Minh Ideology',9],['MLN131','Scientific Socialism',9],['VNR202','History of Viet Nam Communist Party',9]
].map(([code, name, semester]) => ({ code, name, term: `Kỳ ${semester}`, fee: 0, major: 'Business Administration', specialization: 'MC', track: '', link: `https://drive.google.com/${String(code).toLowerCase()}_secret` }));
// Nguồn: chương trình BA(IB) do người dùng cung cấp.
const baIbCourseSeed = [
['ECO111','Microeconomics',1],['ENM302','Business English - Level: Intermediate',1],['MGT103','Introduction to Management',1],['MKT101','Marketing Principles',1],['SSL101c','Academic Skills for University Success',1],
['ACC101','Principles of Accounting',2],['ECO121','Macroeconomics',2],['ENM402','Business English Level 2',2],['OBE102c','Organizational Behavior',2],['SSG104','Communication and In-Group Working Skills',2],
['ECO201','International Economics',3],['FIN202','Principles of Corporate Finance',3],['HRM202c','Human Resource Management',3],['IBC201','Cross Cultural Management and Negotiation',3],['IBI101','Introduction to International Business',3],
['CHN113','Elementary Chinese 1',4],['IBF301','International Finance',4],['ITA203c','Information System Overview',4],['MAS202','Applied Statistics for Business',4],['SCM201','Supply Chain Management',4],
['CHN123','Elementary Chinese 2',5],['IBS301m','International Business Strategy',5],['IEI301','Import Export',5],['MKT205c','International Marketing',5],['SSB201','Advanced Business Communication',5],
['ENW492c','Academic Writing Skills',6],['OJB202','On-the-job Training',6],
['EXE101','Experiential Entrepreneurship 1',7],['IIP301','International Payment',7],['LAW102','Business Law and Ethics Fundamentals',7],['LAW201c','International Business Law',7],['SCM301m','Procurement and Global Sourcing',7],['EXE201','Experiential Entrepreneurship 2',7],
['LOG311','Customs Operations',8],['MLN111','Philosophy of Marxism - Leninism',8],['MLN122','Political Economics of Marxism and Leninism',8],['PMG201c','Project Management',8],['RMB301','Business Research Methods',8],
['BBA_GRA_ELE','BBA Graduation Thesis Elective',9],['HCM202','HCM Ideology',9],['MLN131','Scientific Socialism',9],['VNR202','History of CPV',9]
].map(([code, name, semester]) => ({ code, name, term: `Kỳ ${semester}`, fee: 0, major: 'Business Administration', specialization: 'BA(IB)', track: '', link: `https://drive.google.com/${String(code).toLowerCase()}_secret` }));
// Nguồn: chương trình IT → SE → .NET do người dùng cung cấp.
const seDotnetCourseSeed = [
['GDQP','Military Education',0],['OTP101','Orientation and General Training Program',0],['TMI101','Traditional Musical Instrument',0],['TRS601','English 6 (University Success)',0],['VOV114','Vovinam 1/3',0],['VOV124','Vovinam 2/3',0],['VOV134','Vovinam 3/3',0],
['CEA201','Computer Organization and Architecture',1],['CSI104','Introduction to Computer Science',1],['MAE101','Mathematics for Engineering',1],['PRF192','Programming Fundamentals',1],['SSL101c','Academic Skills for University Success',1],
['MAD101','Discrete Mathematics',2],['NWC204','Computer Networking',2],['OSG202','Operating Systems',2],['PRO192','Object-Oriented Programming',2],['SSG104','Communication and In-Group Working Skills',2],
['CSD201','Data Structures and Algorithms',3],['JPD113','Elementary Japanese 1-A1.1',3],['LAB211','OOP with Java Lab',3],['WED201c','Web Design',3],
['IOT102','Internet of Things',4],['JPD123','Elementary Japanese 1-A1.2',4],['MAS291','Statistics & Probability',4],['PRJ301','Java Web Application Development',4],['SWE201c','Introduction to Software Engineering',4],
['PRN212','Basic Cross-Platform Application Programming With .NET',5],['SWP391','Software Development Project',5],['SWR302','Software Requirement',5],['SWT301','Software Testing',5],['WDU203c','UI/UX Design',5],
['ENW493c','Research Methods & Academic Writing Skills',6],['OJT202','On-The-Job Training',6],
['EXE101','Experiential Entrepreneurship 1',7],['PMG201c','Project Management',7],['PRN222','Advanced Cross-Platform Application Programming With .NET',7],['PRU213','Game Programming with C#',7],['SWD392','Software Architecture and Design',7],
['EXE201','Experiential Entrepreneurship 2',8],['ITE302c','Ethics in IT',8],['MLN111','Philosophy of Marxism - Leninism',8],['MLN122','Political Economics of Marxism - Leninism',8],['PRM393','Mobile Programming',8],['PRN232','Xây dựng ứng dụng back-end với .NET',8],
['HCM202','HCM Ideology',9],['MLN131','Scientific Socialism',9],['SE_GRA_ELE','Graduation Elective - Software Engineering',9],['VNR202','History of CPV',9]
].map(([code, name, semester]) => ({ code, name, term: `Kỳ ${semester}`, fee: 0, major: 'Computing', specialization: 'SE', track: '.NET', link: `https://drive.google.com/${String(code).toLowerCase()}_secret` }));
// Nguồn: chương trình IT → SE → JS do người dùng cung cấp.
const seJsCourseSeed = [
['GDQP','Military Education',0],['OTP101','Orientation and General Training Program',0],['TMI101','Traditional Musical Instrument',0],['TRS601','English 6 (University Success)',0],['VOV114','Vovinam 1/3',0],['VOV124','Vovinam 2/3',0],['VOV134','Vovinam 3/3',0],
['CEA201','Computer Organization and Architecture',1],['CSI104','Introduction to Computer Science',1],['MAE101','Mathematics for Engineering',1],['PRF192','Programming Fundamentals',1],['SSL101c','Academic Skills for University Success',1],
['MAD101','Discrete Mathematics',2],['NWC204','Computer Networking',2],['OSG202','Operating Systems',2],['PRO192','Object-Oriented Programming',2],['SSG104','Communication and In-Group Working Skills',2],
['CSD201','Data Structures and Algorithms',3],['DBI202','Introduction to Databases',3],['JPD113','Elementary Japanese 1 - A1.1',3],['LAB211','OOP with Java Lab',3],['WED201c','Web Design',3],
['IOT102','Internet of Things',4],['JPD123','Elementary Japanese 1-A1.2',4],['MAS291','Statistics & Probability',4],['PRJ301','Java Web Application Development',4],['SWE201c','Introduction to Software Engineering',4],
['JPD133','Elementary Japanese 1-A1/A2',5],['SWP391','Software Development Project',5],['SWR302','Software Requirement',5],['SWT301','Software Testing',5],['WDU203c','UI/UX Design',5],
['ENW493c','Research Methods & Academic Writing Skills',6],['OJT202','On-The-Job Training',6],
['JPD316','Intermediate Japanese 1-B1/B2',7],['PMG201c','Project Management',7],['SWD392','Software Architecture and Design',7],['SYB302c','Entrepreneurship',7],
['ITE302c','Ethics in IT',8],['JFE301','Japanese IT Fundamentals',8],['JIT401','Information Technology Japanese',8],['MLN111','Philosophy of Marxism - Leninism',8],['MLN122','Political Economics of Marxism - Leninism',8],['PRM393','Mobile Programming',8],
['HCM202','HCM Ideology',9],['MLN131','Scientific Socialism',9],['SE_GRA_ELE','Graduation Elective - Software Engineering',9],['VNR202','History of CPV',9]
].map(([code, name, semester]) => ({ code, name, term: `Kỳ ${semester}`, fee: 0, major: 'Computing', specialization: 'SE', track: 'JS', link: `https://drive.google.com/${String(code).toLowerCase()}_secret` }));

const aiCourseSeed = [
['GDQP','Military Education (Giáo dục quốc phòng)',0],['OTP101','Orientation & General Training Program',0],['TMI101','Traditional Musical Instrument (Nhạc cụ)',0],['TRS601','English 6 (University Success)',0],['VOV114','Vovinam 1/3',0],['VOV124','Vovinam 2/3',0],['VOV134','Vovinam 3/3',0],
['CSI106','Introduction to Computer Science',1],['MAD101','Discrete Mathematics (Toán rời rạc)',1],['MAE101','Mathematics for Engineering',1],['PFP191','Programming Fundamentals with Python',1],['SSL101c','Academic Skills for University Success',1],
['AIG202c','Artificial Intelligence (Nhập môn AI)',2],['CEA201','Computer Organization & Architecture',2],['CSD203','Data Structures and Algorithm with Python',2],['DBI202','Introduction to Databases',2],['SSG104','Communication & In-Group Working Skills',2],
['ADY201m','AI, DS with Python & SQL',3],['ITE303c','Ethics in IT (Đạo đức CNTT)',3],['JPD113','Elementary Japanese 1 - A1.1',3],['MAI391','Mathematics for Machine Learning',3],['MAS291','Statistics & Probability',3],
['AIL303m','Machine Learning (Học máy)',4],['CPV301','Computer Vision (Thị giác máy tính)',4],['DAP391m','AI-DS Project (Đồ án AI & Khoa học DL)',4],['JPD123','Elementary Japanese 1 - A1.2',4],['SWE201c','Introduction to Software Engineering',4],
['AIH301m','AI in Healthcare',5],['ASR301c','AI for Scientific Research',5],['DPL302m','Deep Learning (Học sâu)',5],['DWP301c','Web Development with Python',5],
['NLP301c','Natural Language Processing (Xử lý NN tự nhiên)',6],['OJT202','On-The-Job Training (Kỳ thực tập doanh nghiệp)',6],
['AIM301m','AI for Medicine',7],['DAT301m','AI Development with TensorFlow',7],['ENW493c','Research Methods & Academic Writing',7],['EXE101','Experiential Entrepreneurship 1',7],['PMG201c','Project Management (Quản trị dự án)',7],
['AID301c','AI in Production (Triển khai hệ thống AI)',8],['AIE301m','AI for Trading',8],['EXE201','Experiential Entrepreneurship 2',8],['MLN111','Philosophy of Marxism - Leninism',8],['MLN122','Political Economics of Marxism - Leninism',8],['REL301m','Reinforcement Learning (Học tăng cường)',8],
['AI17_GRA','AI17_GRA_ELE: Graduation Elective / Thesis',9],['HCM202','HCM Ideology (Tư tưởng Hồ Chí Minh)',9],['MLN131','Scientific Socialism (Chủ nghĩa XHKH)',9],['VNR202','History of CPV (Lịch sử Đảng CSVN)',9]
].map(([code, name, semester]) => ({ code, name, term: `Kỳ ${semester}`, fee: 0, major: 'Computing', specialization: 'AI', track: '', link: `https://drive.google.com/${String(code).toLowerCase()}_secret` }));
const allCourseSeeds = [...courseSeed, ...bbaMcCourseSeed, ...baIbCourseSeed, ...seDotnetCourseSeed, ...seJsCourseSeed, ...aiCourseSeed];
const toClient = doc => { const value = doc.toObject ? doc.toObject() : doc; const { password, googleSubject, otpHash, otpPurpose, otpExpiresAt, ...safe } = value; return { ...safe, id: String(value._id), createdAt: value.createdAt || new Date().toISOString() }; };
const JWT_SECRET = process.env.JWT_SECRET;
const PASSWORD_HASH_ROUNDS = 10;
const authLimiter = rateLimit({windowMs:15*60*1000,limit:8,standardHeaders:'draft-8',legacyHeaders:false,message:{success:false,msg:'Bạn đã thử quá nhiều lần. Vui lòng thử lại sau 15 phút.'}});
const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const cleanEmail=value=>String(value||'').trim().toLowerCase();
const validPassword=value=>typeof value==='string'&&value.length>=8&&value.length<=72;
const makeToken=user=>{if(!JWT_SECRET)throw new Error('JWT_SECRET chưa được cấu hình trên máy chủ.');return jwt.sign({sub:String(user._id),email:user.email,role:user.role},JWT_SECRET,{expiresIn:'7d',issuer:'psifu-api'});};
const requireAuth=(req,res,next)=>{try{if(!JWT_SECRET)return res.status(503).json({success:false,msg:'Máy chủ chưa cấu hình JWT_SECRET.'});const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)return res.status(401).json({success:false,msg:'Bạn cần đăng nhập để tiếp tục.'});req.auth=jwt.verify(token,JWT_SECRET,{issuer:'psifu-api'});next();}catch{return res.status(401).json({success:false,msg:'Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.'});}};
const requireRole=(...roles)=>(req,res,next)=>roles.includes(req.auth?.role)?next():res.status(403).json({success:false,msg:'Bạn không có quyền thực hiện thao tác này.'});
const requireSelfOrAdmin=(field='email')=>(req,res,next)=>cleanEmail(req.params[field]||req.body[field])===req.auth?.email||req.auth?.role==='admin'?next():res.status(403).json({success:false,msg:'Bạn chỉ được thao tác trên tài khoản của chính mình.'});
const mailer = process.env.SMTP_HOST ? nodemailer.createTransport({ host: process.env.SMTP_HOST, port: Number(process.env.SMTP_PORT || 587), secure: process.env.SMTP_SECURE === 'true', auth: process.env.SMTP_USER ? { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS } : undefined, connectionTimeout: 15000, greetingTimeout: 15000, socketTimeout: 20000 }) : null;
const hashOtp = code => crypto.createHash('sha256').update(code).digest('hex');
const sendEmail = async ({to,subject,text}) => { if(process.env.RESEND_API_KEY){ const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.RESEND_FROM||'PSIFU <onboarding@resend.dev>',to:[to],subject,text})}); const result=await response.json().catch(()=>({})); if(!response.ok)throw new Error(result.message||result.name||'Resend không thể gửi email.'); return result; } if(!mailer)throw new Error('Chưa cấu hình RESEND_API_KEY hoặc SMTP.'); return mailer.sendMail({from:process.env.SMTP_FROM||process.env.SMTP_USER,to,subject,text}); };
const payosConfigured = () => Boolean(process.env.PAYOS_CLIENT_ID && process.env.PAYOS_API_KEY && process.env.PAYOS_CHECKSUM_KEY && process.env.PAYOS_RETURN_URL && process.env.PAYOS_CANCEL_URL);
const cloudinaryConfigured = () => Boolean(process.env.CLOUDINARY_CLOUD_NAME && process.env.CLOUDINARY_API_KEY && process.env.CLOUDINARY_API_SECRET);
const cloudinarySignature = params => crypto.createHash('sha1').update(`${Object.keys(params).sort().map(key=>`${key}=${params[key]}`).join('&')}${process.env.CLOUDINARY_API_SECRET}`).digest('hex');
const payosSignature = data => crypto.createHmac('sha256', process.env.PAYOS_CHECKSUM_KEY || '').update(Object.keys(data || {}).sort().filter(key => data[key] !== undefined && data[key] !== null).map(key => `${key}=${data[key]}`).join('&')).digest('hex');
const payosRequest = async (path, options = {}) => { const response = await fetch(`https://api-merchant.payos.vn${path}`, { ...options, headers:{ 'Content-Type':'application/json', 'x-client-id':process.env.PAYOS_CLIENT_ID, 'x-api-key':process.env.PAYOS_API_KEY, ...(options.headers||{}) } }); const payload = await response.json().catch(() => ({})); if (!response.ok || payload.code && payload.code !== '00') throw new Error(payload.desc || 'PayOS không thể xử lý yêu cầu thanh toán.'); return payload.data; };
const nextPayosOrderCode = async () => { for(let attempts=0;attempts<8;attempts+=1){ const code=Number(`${Date.now().toString().slice(-8)}${crypto.randomInt(10,100)}`); if(!await PaymentOrder.exists({orderCode:code})) return code; } throw new Error('Không thể tạo mã đơn thanh toán.'); };
const issueOtp = async (user, purpose) => { const code = crypto.randomInt(100000, 1000000).toString(); user.otpHash = hashOtp(code); user.otpPurpose = purpose; user.otpExpiresAt = new Date(Date.now() + 10 * 60 * 1000); await user.save(); await sendEmail({to:user.email,subject:purpose === 'verify-email' ? 'PSIFU – Mã xác minh email' : 'PSIFU – Mã đặt lại mật khẩu',text:`Mã OTP PSIFU của bạn là: ${code}. Mã có hiệu lực trong 10 phút.`}); };
const validateOtp = (user, purpose, code) => user && user.otpPurpose === purpose && user.otpExpiresAt > new Date() && user.otpHash === hashOtp(String(code || ''));
// Sensitive financial/profile routes require a valid identity before their handlers run.
app.use('/api/mentors/:email/bank-account',requireAuth,requireSelfOrAdmin());
app.use('/api/payouts/:email',requireAuth,requireSelfOrAdmin());
app.use('/api/payouts',requireAuth,(req,res,next)=>req.method==='POST'?requireSelfOrAdmin()(req,res,next):next());
app.get('/api/health', (_req, res) => res.json({ status: 'ok' }));
app.get('/payment/return', (_req, res) => res.type('html').send('<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>PSIFU Payment</title></head><body style="font-family:system-ui;text-align:center;padding:56px 20px;background:#f8faff;color:#102a56"><h1>Đang xác nhận thanh toán</h1><p>PayOS đã chuyển bạn về PSIFU. Hãy quay lại ứng dụng; Xu chỉ được cộng sau khi webhook được xác minh.</p></body></html>'));
app.get('/payment/cancel', (_req, res) => res.type('html').send('<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>PSIFU Payment</title></head><body style="font-family:system-ui;text-align:center;padding:56px 20px;background:#f8faff;color:#102a56"><h1>Thanh toán chưa hoàn tất</h1><p>Bạn có thể quay lại ứng dụng PSIFU để thử lại khi sẵn sàng.</p></body></html>'));
app.get('/api/courses', async (req, res) => { const filter = { major: req.query.major || 'Computing', specialization: req.query.specialization || 'SE' }; if (req.query.track !== undefined) filter.track = req.query.track; if (req.query.term) filter.term = req.query.term; res.json((await Course.find(filter).sort({ term: 1, code: 1 })).map(toClient)); });
app.get('/api/users', async (_req, res) => res.json((await User.find().sort({ createdAt: -1 })).map(toClient)));
app.post('/api/users',authLimiter, async (req,res)=>{const email=cleanEmail(req.body.email),fullName=String(req.body.fullName||'').trim(),password=req.body.password;if(!emailPattern.test(email))return res.status(400).json({success:false,msg:'Email không hợp lệ.'});if(fullName.length<2||fullName.length>80)return res.status(400).json({success:false,msg:'Họ tên phải từ 2 đến 80 ký tự.'});if(!validPassword(password))return res.status(400).json({success:false,msg:'Mật khẩu phải dài từ 8 đến 72 ký tự.'});if(!['mentee','mentor'].includes(req.body.role||'mentee'))return res.status(400).json({success:false,msg:'Vai trò đăng ký không hợp lệ.'});if(await User.exists({email}))return res.status(409).json({success:false,msg:'Email/Tài khoản này đã tồn tại!'});const user=await User.create({...req.body,email,fullName,password:await bcrypt.hash(password,PASSWORD_HASH_ROUNDS),role:req.body.role||'mentee'});res.status(201).json({success:true,msg:'Đăng ký thành công!',user:toClient(user)});});
app.post('/api/auth/email-verification/send', async (req, res) => { const user = await User.findOne({ email: req.body.email?.trim().toLowerCase() }); if (!user) return res.status(404).json({ success: false, msg: 'Không tìm thấy tài khoản với email này.' }); try { await issueOtp(user, 'verify-email'); res.json({ success: true, msg: 'Mã OTP đã được gửi tới email của bạn.' }); } catch (error) { res.status(503).json({ success: false, msg: error.message }); } });
app.post('/api/auth/email-verification/verify', async (req, res) => { const user = await User.findOne({ email: req.body.email?.trim().toLowerCase() }); if (!validateOtp(user, 'verify-email', req.body.code)) return res.status(400).json({ success: false, msg: 'Mã OTP không đúng hoặc đã hết hạn.' }); user.emailVerified = true; user.otpHash = undefined; user.otpPurpose = undefined; user.otpExpiresAt = undefined; await user.save(); res.json({ success: true, msg: 'Email đã được xác minh.' }); });
app.post('/api/auth/password-reset/send', async (req, res) => { const user = await User.findOne({ email: req.body.email?.trim().toLowerCase() }); if (!user) return res.status(404).json({ success: false, msg: 'Email này chưa có tài khoản PSIFU.' }); try { await issueOtp(user, 'password-reset'); res.json({ success: true, msg: 'Mã đặt lại mật khẩu đã được gửi.' }); } catch (error) { console.error('Password-reset OTP delivery failed:', error.message); res.status(503).json({ success: false, msg: error.message }); } });
app.post('/api/auth/password-reset/verify', async (req, res) => { const user = await User.findOne({ email: req.body.email?.trim().toLowerCase() }); if (!validateOtp(user, 'password-reset', req.body.code)) return res.status(400).json({ success: false, msg: 'Mã OTP không đúng hoặc đã hết hạn.' }); res.json({ success: true }); });
app.post('/api/auth/password-reset/complete', authLimiter, async (req,res)=>{const user=await User.findOne({email:cleanEmail(req.body.email)});if(!validPassword(req.body.password))return res.status(400).json({success:false,msg:'Mật khẩu phải dài từ 8 đến 72 ký tự.'});if(!validateOtp(user,'password-reset',req.body.code))return res.status(400).json({success:false,msg:'Mã OTP không đúng hoặc đã hết hạn.'});user.password=await bcrypt.hash(req.body.password,PASSWORD_HASH_ROUNDS);user.otpHash=undefined;user.otpPurpose=undefined;user.otpExpiresAt=undefined;await user.save();res.json({success:true,msg:'Đặt lại mật khẩu thành công.'});});
app.post('/api/auth/login', authLimiter, async (req, res) => {
  const email = req.body.email?.trim().toLowerCase();
  const user = await User.findOne({ email });
  if (!user) return res.status(404).json({ success: false, code: 'EMAIL_NOT_FOUND', msg: 'Email này chưa có tài khoản PSIFU.' });
  const passwordOk=await bcrypt.compare(String(req.body.password||''),user.password).catch(()=>false); const legacyPasswordOk=!passwordOk&&user.password===req.body.password;
  if (!passwordOk&&!legacyPasswordOk) return res.status(401).json({ success: false, code: 'WRONG_PASSWORD', msg: 'Mật khẩu chưa chính xác. Vui lòng thử lại.' });
  res.json({ success: true, user: toClient(user), accessToken:makeToken(user) });
  if(legacyPasswordOk||bcrypt.getRounds(user.password)>PASSWORD_HASH_ROUNDS){bcrypt.hash(req.body.password,PASSWORD_HASH_ROUNDS).then(password=>User.updateOne({_id:user._id},{$set:{password}})).catch(()=>{});}
});
app.post('/api/auth/google', authLimiter, async (req, res) => {
  const idToken = String(req.body.idToken || '');
  const clientId = process.env.GOOGLE_WEB_CLIENT_ID;
  if (!clientId) return res.status(503).json({ success: false, msg: 'Đăng nhập Google chưa được cấu hình trên máy chủ.' });
  if (!idToken || idToken.length > 4096) return res.status(400).json({ success: false, msg: 'Google ID token không hợp lệ.' });
  try {
    const response = await fetch(`https://oauth2.googleapis.com/tokeninfo?id_token=${encodeURIComponent(idToken)}`);
    const payload = await response.json().catch(() => ({}));
    if (!response.ok || payload.aud !== clientId || !['accounts.google.com', 'https://accounts.google.com'].includes(payload.iss) || !['true', true].includes(payload.email_verified) || !emailPattern.test(payload.email || '') || !payload.sub) {
      return res.status(401).json({ success: false, msg: 'Không thể xác minh tài khoản Google này.' });
    }
    const email = cleanEmail(payload.email);
    let user = await User.findOne({ $or: [{ googleSubject: payload.sub }, { email }] });
    if (user && user.googleSubject && user.googleSubject !== payload.sub) return res.status(409).json({ success: false, msg: 'Email này đã được liên kết với một tài khoản Google khác.' });
    if (!user) {
      const fullName = String(payload.name || email.split('@')[0]).trim().slice(0, 80) || 'PSIFU Member';
      user = await User.create({ fullName, email, password: await bcrypt.hash(crypto.randomBytes(32).toString('hex'), PASSWORD_HASH_ROUNDS), googleSubject: payload.sub, avatarUrl: payload.picture || '', emailVerified: true, role: 'mentee', isFirstLogin: true });
    } else {
      user.googleSubject = payload.sub;
      user.emailVerified = true;
      if (!user.avatarUrl && payload.picture) user.avatarUrl = payload.picture;
      await user.save();
    }
    res.json({ success: true, user: toClient(user), accessToken: makeToken(user) });
  } catch (error) {
    console.error('Google sign-in verification:', error.message);
    res.status(502).json({ success: false, msg: 'Không thể xác minh Google lúc này. Vui lòng thử lại.' });
  }
});
app.patch('/api/users/:email',requireAuth,requireSelfOrAdmin(), async (req,res)=>{const allowed=['fullName','avatarUrl','university','academicYear','fptK','studentId','major','specialization','track','currentTerm','mentorBio','mentorFee','mentorCourses','mentorAvailability','notificationPreferences','isFirstLogin'];const updates={};for(const key of allowed)if(req.body[key]!==undefined)updates[key]=req.body[key];if(updates.fullName!==undefined&&(String(updates.fullName).trim().length<2||String(updates.fullName).trim().length>80))return res.status(400).json({success:false,msg:'Họ tên phải từ 2 đến 80 ký tự.'});if(updates.mentorFee!==undefined&&(!Number.isInteger(Number(updates.mentorFee))||updates.mentorFee<0||updates.mentorFee>10000))return res.status(400).json({success:false,msg:'Mức phí Mentor không hợp lệ.'});const user=await User.findOneAndUpdate({email:req.params.email.toLowerCase()},{$set:updates},{new:true});if(!user)return res.status(404).json({success:false});res.json({success:true,user:toClient(user)});});
app.get('/api/users/:email/settings', async (req,res) => { const user=await User.findOne({email:req.params.email.toLowerCase()}); if(!user)return res.status(404).json({success:false}); res.json({notificationPreferences:user.notificationPreferences||{},mentorAvailability:user.mentorAvailability||{accepting:true,slots:[]}}); });
app.patch('/api/users/:email/settings',requireAuth,requireSelfOrAdmin(),async(req,res)=>{const allowed={};if(req.body.notificationPreferences&&typeof req.body.notificationPreferences==='object')allowed.notificationPreferences=req.body.notificationPreferences;if(req.body.mentorAvailability&&typeof req.body.mentorAvailability==='object')allowed.mentorAvailability=req.body.mentorAvailability;const user=await User.findOneAndUpdate({email:req.params.email.toLowerCase()},{$set:allowed},{new:true});if(!user)return res.status(404).json({success:false});res.json({success:true,notificationPreferences:user.notificationPreferences,mentorAvailability:user.mentorAvailability});});
app.post('/api/uploads/cloudinary-signature',async(req,res)=>{const email=req.body.email?.trim().toLowerCase();const user=await User.findOne({email});if(!user||user.role!=='mentor')return res.status(403).json({success:false,msg:'Chỉ Mentor được tải tài liệu lên.'});if(!cloudinaryConfigured())return res.status(503).json({success:false,msg:'Cloudinary chưa được cấu hình trên máy chủ.'});const fileName=String(req.body.fileName||'document.pdf');if(!fileName.toLowerCase().endsWith('.pdf'))return res.status(400).json({success:false,msg:'PSIFU chỉ hỗ trợ tệp PDF.'});const timestamp=Math.floor(Date.now()/1000);const safeEmail=email.replace(/[^a-z0-9]/gi,'_');const params={folder:`psifu/mentor-documents/${safeEmail}`,public_id:`doc_${timestamp}_${crypto.randomUUID().slice(0,8)}`,timestamp};res.json({success:true,cloudName:process.env.CLOUDINARY_CLOUD_NAME,apiKey:process.env.CLOUDINARY_API_KEY,timestamp,folder:params.folder,publicId:params.public_id,signature:cloudinarySignature(params)});});
app.post('/api/payments/payos/topups', async (req,res) => { const email=req.body.email?.trim().toLowerCase(); const coins=Number(req.body.coins); const packages=[50,100,200,500]; if(!email || !packages.includes(coins)) return res.status(400).json({success:false,msg:'Gói nạp không hợp lệ.'}); if(!payosConfigured()) return res.status(503).json({success:false,msg:'PayOS chưa được cấu hình trên máy chủ. Hãy thêm PAYOS_CLIENT_ID, PAYOS_API_KEY, PAYOS_CHECKSUM_KEY, PAYOS_RETURN_URL và PAYOS_CANCEL_URL.'}); const user=await User.findOne({email}); if(!user) return res.status(404).json({success:false,msg:'Không tìm thấy tài khoản.'}); try { const orderCode=await nextPayosOrderCode(); const amount=coins*1000; const requestData={orderCode,amount,description:`PSIFU ${coins} Xu`,returnUrl:process.env.PAYOS_RETURN_URL,cancelUrl:process.env.PAYOS_CANCEL_URL,items:[{name:`PSIFU ${coins} Xu`,quantity:1,price:amount}]}; requestData.signature=payosSignature({orderCode,amount,description:requestData.description,returnUrl:requestData.returnUrl,cancelUrl:requestData.cancelUrl}); const payment=await payosRequest('/v2/payment-requests',{method:'POST',body:JSON.stringify(requestData)}); const order=await PaymentOrder.create({orderCode,userEmail:email,coins,amount,paymentLinkId:payment.paymentLinkId,checkoutUrl:payment.checkoutUrl}); res.status(201).json({success:true,orderCode:order.orderCode,checkoutUrl:order.checkoutUrl,qrCode:payment.qrCode,amount:order.amount,status:order.status}); } catch(error){ console.error('PayOS create payment link:',error.message); res.status(502).json({success:false,msg:error.message||'Không thể tạo liên kết PayOS.'}); } });
app.get('/api/payments/payos/orders/:orderCode', async (req,res) => { const order=await PaymentOrder.findOne({orderCode:Number(req.params.orderCode)}); if(!order) return res.status(404).json({success:false,msg:'Không tìm thấy đơn thanh toán.'}); res.json({success:true,orderCode:order.orderCode,status:order.status,coins:order.coins,amount:order.amount,userXu:order.status==='PAID'?(await User.findOne({email:order.userEmail}).select('userXu'))?.userXu:undefined}); });
app.post('/api/payments/payos/webhook', async (req,res) => { try { const payload=req.body||{}; const expected=payosSignature(payload.data||{}); const received=String(payload.signature||''); if(!received || expected.length!==received.length || !crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(received))) return res.status(400).json({success:false,msg:'Webhook signature không hợp lệ.'}); if(payload.code!=='00' || payload.success!==true || payload.data?.code!=='00') return res.status(200).json({success:true,ignored:true}); const existing=await PaymentOrder.findOne({orderCode:Number(payload.data.orderCode)}); if(!existing || existing.status==='PAID') return res.status(200).json({success:true,ignored:true}); if(existing.amount!==Number(payload.data.amount)) return res.status(400).json({success:false,msg:'Số tiền webhook không khớp đơn hàng.'}); const order=await PaymentOrder.findOneAndUpdate({orderCode:existing.orderCode,status:'PENDING'},{$set:{status:'PAID',reference:payload.data.reference,paidAt:new Date()}},{new:true}); if(!order) return res.status(200).json({success:true,ignored:true}); const user=await User.findOneAndUpdate({email:order.userEmail},{$inc:{userXu:order.coins}},{new:true}); if(!user) return res.status(404).json({success:false}); await Transaction.create({userEmail:user.email,type:'PAYOS_TOPUP',amount:order.coins,status:'SUCCESS',metadata:{orderCode:order.orderCode,amountVnd:order.amount,reference:order.reference}}); await Notification.create({userEmail:user.email,title:'Nạp Xu thành công',body:`PayOS đã xác nhận đơn #${order.orderCode}. ${order.coins} Xu đã được cộng vào ví.`,type:'WALLET'}); res.status(200).json({success:true}); } catch(error){ console.error('PayOS webhook:',error.message); res.status(500).json({success:false,msg:'Không thể xử lý webhook.'}); } });
app.put('/api/mentors/:email/bank-account',async(req,res)=>{const email=req.params.email.trim().toLowerCase(),bank=req.body.bankAccount||{};const required=['bankName','accountNumber','accountHolder'];if(required.some(key=>!String(bank[key]||'').trim()))return res.status(400).json({success:false,msg:'Hãy nhập đủ ngân hàng, số tài khoản và tên chủ tài khoản.'});if(!/^\d{6,19}$/.test(String(bank.accountNumber)))return res.status(400).json({success:false,msg:'Số tài khoản phải gồm 6–19 chữ số.'});const user=await User.findOneAndUpdate({email,role:'mentor'},{$set:{bankAccount:{bankName:String(bank.bankName).trim(),accountNumber:String(bank.accountNumber).trim(),accountHolder:String(bank.accountHolder).trim().toUpperCase(),bin:String(bank.bin||'').trim()}}},{new:true});if(!user)return res.status(404).json({success:false,msg:'Không tìm thấy tài khoản Mentor.'});res.json({success:true,bankAccount:user.bankAccount});});
app.post('/api/payouts',async(req,res)=>{const email=req.body.email?.trim().toLowerCase(),amountXu=Number(req.body.amountXu);if(!email||!Number.isInteger(amountXu)||amountXu<50)return res.status(400).json({success:false,msg:'Số Xu rút tối thiểu là 50 Xu.'});const user=await User.findOneAndUpdate({email,role:'mentor',availableXu:{$gte:amountXu},'bankAccount.accountNumber':{$exists:true,$ne:''}},{$inc:{availableXu:-amountXu}},{new:true});if(!user)return res.status(400).json({success:false,msg:'Số dư khả dụng không đủ hoặc bạn chưa thêm tài khoản ngân hàng.'});try{const payoutCode=`PO-${Date.now()}-${crypto.randomUUID().slice(0,6).toUpperCase()}`;const payout=await Payout.create({payoutCode,mentorEmail:email,amountXu,amountVnd:amountXu*1000,bankAccount:user.bankAccount,status:'PROCESSING'});await Transaction.create({userEmail:email,type:'MENTOR_PAYOUT',amount:-amountXu,status:'PROCESSING',metadata:{payoutCode,bankName:user.bankAccount.bankName,accountNumber:user.bankAccount.accountNumber}});await Notification.create({userEmail:email,title:'Yêu cầu rút Xu đang xử lý',body:`Lệnh ${payoutCode} rút ${amountXu} Xu đang chờ đối soát.`,type:'WALLET'});res.status(201).json({success:true,payout:toClient(payout),availableXu:user.availableXu});}catch(error){await User.findOneAndUpdate({email},{$inc:{availableXu:amountXu}});throw error;}});
app.get('/api/payouts/:email',async(req,res)=>{const email=req.params.email.trim().toLowerCase();res.json((await Payout.find({mentorEmail:email}).sort({createdAt:-1}).limit(50)).map(toClient));});
app.get('/api/payouts/:email/:payoutCode',async(req,res)=>{const payout=await Payout.findOne({mentorEmail:req.params.email.trim().toLowerCase(),payoutCode:req.params.payoutCode});if(!payout)return res.status(404).json({success:false,msg:'Không tìm thấy lệnh Payout.'});res.json({success:true,payout:toClient(payout)});});
app.get('/api/support-tickets/:email',async(req,res)=>res.json((await SupportTicket.find({reporterEmail:req.params.email.toLowerCase()}).sort({createdAt:-1})).map(toClient)));
app.post('/api/support-tickets',async(req,res)=>{if(!req.body.reporterEmail||!req.body.reason||!req.body.detail?.trim())return res.status(400).json({success:false,msg:'Hãy chọn lý do và mô tả chi tiết sự cố.'});res.status(201).json({success:true,ticket:toClient(await SupportTicket.create(req.body))});});
app.patch('/api/users/:email/role', async (req, res) => { if (!['mentee', 'mentor', 'admin'].includes(req.body.role)) return res.status(400).json({ success: false }); const user = await User.findOne({ email: req.params.email.toLowerCase() }); if (!user || user.protected) return res.status(403).json({ success: false }); user.role = req.body.role; await user.save(); res.json({ success: true }); });
const isPremiumUser=user=>user?.subscription?.plan==='PREMIUM'&&user.subscription.status==='ACTIVE'&&new Date(user.subscription.expiresAt)>new Date();
const subscriptionState=user=>({plan:isPremiumUser(user)?'PREMIUM':'FREE',status:isPremiumUser(user)?'ACTIVE':(user?.subscription?.status||'ACTIVE'),startedAt:user?.subscription?.startedAt||null,expiresAt:user?.subscription?.expiresAt||null,isPremium:isPremiumUser(user)});
app.get('/api/premium/plan',(_req,res)=>res.json(PREMIUM_PLAN));
app.get('/api/premium/subscription/:email',async(req,res)=>{const user=await User.findOne({email:req.params.email.toLowerCase()});if(!user)return res.status(404).json({success:false});res.json(subscriptionState(user));});
app.post('/api/premium/mock-payment/complete',async(req,res)=>{const user=await User.findOne({email:req.body.email?.toLowerCase()});if(!user)return res.status(404).json({success:false});const startedAt=new Date();const expiresAt=new Date(startedAt.getTime()+PREMIUM_PLAN.durationDays*86400000);user.subscription={plan:'PREMIUM',status:'ACTIVE',startedAt,expiresAt};await user.save();await Transaction.create({userEmail:user.email,type:'PREMIUM_SUBSCRIPTION',amount:PREMIUM_PLAN.price,status:'SUCCESS',metadata:{mode:'VNPAY_MOCK'}});await Notification.create({userEmail:user.email,title:'Chào mừng đến PSIFU Premium!',body:'Premium của bạn đã được kích hoạt.',type:'PREMIUM'});res.json({success:true,subscription:subscriptionState(user)});});
app.get('/api/premium/documents/:email',async(req,res)=>{const user=await User.findOne({email:req.params.email.toLowerCase()});if(!isPremiumUser(user))return res.status(403).json({success:false,code:'PREMIUM_REQUIRED',message:'Tài nguyên này cần PSIFU Premium.'});res.json((await PremiumDocument.find()).map(toClient));});
app.post('/api/quiz/access',async(req,res)=>{const user=await User.findOne({email:req.body.email?.toLowerCase()});if(!user)return res.status(404).json({success:false});const period=new Date().toISOString().slice(0,7);if(user.aiQuizUsagePeriod!==period){user.aiQuizUsagePeriod=period;user.aiQuizUsage=0;}const limit=isPremiumUser(user)?PREMIUM_PLAN.premiumAiQuizLimit:PREMIUM_PLAN.freeAiQuizLimit;if(user.aiQuizUsage>=limit){await user.save();return res.status(429).json({success:false,code:isPremiumUser(user)?'LIMIT_REACHED':'PREMIUM_REQUIRED',limit});}user.aiQuizUsage+=1;await user.save();res.json({success:true,remaining:limit-user.aiQuizUsage,plan:subscriptionState(user).plan});});
app.get('/api/notifications/:email',async(req,res)=>res.json((await Notification.find({userEmail:req.params.email.toLowerCase()}).sort({createdAt:-1}).limit(30)).map(toClient)));
app.patch('/api/notifications/:id/read',async(req,res)=>res.json({success:!!await Notification.findByIdAndUpdate(req.params.id,{read:true})}));
app.get('/api/questions', async (_req, res) => res.json((await Question.find().sort({ createdAt: -1 })).map(toClient)));
app.post('/api/questions', async (req, res) => res.status(201).json(toClient(await Question.create(req.body))));
app.get('/api/bookings', async (_req, res) => res.json((await Booking.find().sort({ createdAt: -1 })).map(toClient)));
app.post('/api/bookings', async (req, res) => { if (await Booking.exists({ mentorEmail: req.body.mentorEmail, dateTime: req.body.dateTime })) return res.status(409).json({ success: false, msg: 'Khung giờ này đã có mentee đặt trước.' }); res.status(201).json(toClient(await Booking.create({ ...req.body, meetingLink: req.body.meetingLink || 'https://meet.google.com/psifu-session' }))); });
app.patch('/api/bookings/:id', async (req, res) => res.json({ success: !!await Booking.findByIdAndUpdate(req.params.id, req.body) }));
app.get('/api/chats/:roomId', async (req, res) => res.json((await ChatMessage.find({ roomId: req.params.roomId }).sort({ createdAt: 1 }).limit(25)).map(toClient)));
app.post('/api/chats/:roomId', async (req, res) => res.status(201).json(toClient(await ChatMessage.create({ ...req.body, roomId: req.params.roomId }))));
const catalogDocument = doc => { const item=toClient(doc); delete item.fileUri; delete item.cloudinaryPublicId; return item; };
app.get('/api/mentor-documents', async (req, res) => { const filter={}; if(req.query.status)filter.status=req.query.status; if(req.query.mentorEmail)filter.mentorEmail=req.query.mentorEmail.toLowerCase(); const documents=await MentorDocument.find(filter).sort({createdAt:-1}); res.json((req.query.catalog==='true'?documents.map(catalogDocument):documents.map(toClient))); });
app.post('/api/mentor-documents', async (req, res) => res.status(201).json(toClient(await MentorDocument.create(req.body))));
app.get('/api/document-unlocks/:email',async(req,res)=>{const unlocks=await DocumentUnlock.find({userEmail:req.params.email.toLowerCase()}).select('documentId');res.json(unlocks.map(item=>String(item.documentId)));});
app.post('/api/mentor-documents/:id/unlock',async(req,res)=>{const email=req.body.email?.trim().toLowerCase();const document=await MentorDocument.findOne({_id:req.params.id,status:'PUBLISHED'});if(!email||!document)return res.status(404).json({success:false,msg:'Không tìm thấy tài liệu đã xuất bản.'});const exists=await DocumentUnlock.exists({userEmail:email,documentId:document._id});if(exists)return res.json({success:true,alreadyUnlocked:true,userXu:(await User.findOne({email}).select('userXu'))?.userXu});const fee=Number(document.fee||0);const user=await User.findOneAndUpdate({email,userXu:{$gte:fee}},{$inc:{userXu:-fee}},{new:true});if(!user)return res.status(400).json({success:false,msg:'Bạn không đủ Xu để mở khóa tài liệu.'});try{await DocumentUnlock.create({userEmail:email,documentId:document._id});await MentorDocument.findByIdAndUpdate(document._id,{$inc:{unlocks:1,revenue:fee}});await Transaction.create({userEmail:email,type:'DOCUMENT_UNLOCK',amount:-fee,status:'SUCCESS',metadata:{documentId:String(document._id),title:document.title}});res.status(201).json({success:true,userXu:user.userXu});}catch(error){await User.findOneAndUpdate({email},{$inc:{userXu:fee}});if(error?.code===11000)return res.json({success:true,alreadyUnlocked:true,userXu:(await User.findOne({email}).select('userXu'))?.userXu});throw error;}});
app.get('/api/mentor-documents/:id/access',async(req,res)=>{const email=req.query.email?.trim().toLowerCase();const document=await MentorDocument.findOne({_id:req.params.id,status:'PUBLISHED'});if(!email||!document)return res.status(404).json({success:false,msg:'Không tìm thấy tài liệu.'});const unlocked=Number(document.fee||0)===0||await DocumentUnlock.exists({userEmail:email,documentId:document._id});if(!unlocked)return res.status(403).json({success:false,msg:'Hãy mở khóa tài liệu trước.'});res.json({success:true,document:{...catalogDocument(document),fileUri:document.fileUri}});});
app.use((err, _req, res, _next) => { console.error(err); res.status(500).json({ success: false, msg: 'Lỗi máy chủ.' }); });
const port = process.env.PORT || 4000;
mongoose.connect(process.env.MONGODB_URI).then(async () => { await User.bulkWrite(systemUsers.map(user => ({ updateOne: { filter: { email: user.email }, update: { $setOnInsert: user }, upsert: true } }))); await Course.collection.dropIndex('code_1').catch(() => null); await Course.collection.dropIndex('code_1_major_1_specialization_1').catch(() => null); await Course.collection.createIndex({ code: 1, major: 1, specialization: 1, track: 1 }, { unique: true }); await Course.bulkWrite(allCourseSeeds.map(course => ({ updateOne: { filter: { code: course.code, major: course.major, specialization: course.specialization, track: course.track }, update: { $set: course }, upsert: true } }))); app.listen(port, '0.0.0.0', () => console.log(`PSIFU API is running on port ${port}`)); }).catch(error => { console.error('Không thể kết nối MongoDB:', error.message); process.exit(1); });
